# -*- coding: utf-8 -*-
# RLR · Perfiles de la estructura de proyecto — Ricardo López Reyero
P = {}

P['Director de Proyecto'] = dict(
    linea='Dirección', reporta='Dirección general de la empresa', esquema='direccion',
    mision='Entregar el corredor con el estándar de 50 años, en plazo y en costo, cuidando el costo de todo su ciclo de vida y no sólo el de la obra.',
    importa='Es el único que reanuda un colado detenido y el único que autoriza, por escrito, una desviación de la especificación. Si este puesto falla, el organigrama entero se desactiva desde arriba.',
    responde=['El costo total del ciclo de vida del corredor, no sólo el costo de obra.', 'El programa general: frentes, colchones, movilización y liberaciones.',
              'El equilibrio entre Producción, Calidad, Logística y Soporte: que ninguna línea se coma a otra.', 'La relación con el cliente, la supervisión independiente y las dependencias.',
              'La seguridad de todas las personas del proyecto.'],
    autoridad=['Reanudar un colado detenido por Calidad o por Seguridad, dejando por escrito qué cambió.', 'Autorizar por escrito cualquier desviación de la especificación, con su justificación técnica.',
               'Contratar y remover a gerentes y jefes; aprobar compras mayores dentro del presupuesto.', 'No le toca: detener a Calidad para cumplir el programa, ni aceptar un precio por debajo del piso.'],
    experiencia=['12 años o más en construcción carretera, con al menos un corredor completo de pavimento rígido dirigido de principio a fin.',
                 'Haber vivido un proyecto que se complicó (atrasos, fallas de calidad, conflictos con el cliente) y saber contar qué hizo.',
                 'Manejo de presupuestos de más de mil millones de pesos y de equipos de más de 100 personas.'],
    escolaridad=['Ingeniería civil titulada; maestría en construcción, vías terrestres o administración de proyectos deseable.', 'Deseable: certificación en dirección de proyectos y conocimiento de contratos de obra pública y APP.'],
    persona=['Pregunta "¿por qué?" antes de preguntar "¿cuánto nos costó?" cuando Calidad detiene el colado.', 'Decide con datos del tablero, no con la última persona que habló.',
             'Sostiene un "no" frente al cliente, a la presión política o a su propio equipo cuando la especificación está en juego.', 'Da crédito hacia abajo y responsabilidad hacia arriba.',
             'Está en el frente de noche al menos dos veces por semana, sin avisar.'],
    alertas=['Presume obras "entregadas antes de tiempo" sin mencionar cómo quedaron a los cinco años.', 'Ve a Calidad como un freno que hay que administrar.',
             'No puede nombrar un error propio ni lo que aprendió de él.', 'Habla de metros y presupuesto, nunca de drenaje, curado o agua añadida.'],
    preguntas=[('Cuénteme de un colado que usted detuvo o que le detuvieron. ¿Qué pasó después?', 'Que respaldó la detención, entendió la causa y cambió algo en el proceso, no que buscó un culpable.'),
               ('El cliente pide acelerar 30 % el programa. ¿Qué hace?', 'Que acelera clonando frentes y liberando derecho de vía, nunca apretando un solo tren ni recortando curado.'),
               ('Le ofrecen bajar la losa de 27 a 24 cm para cerrar el contrato. ¿Qué responde?', 'Que el espesor se ajusta por tránsito con ingeniería; el drenaje, el suelo, el agua/cemento y el curado no se negocian nunca.'),
               ('¿Cómo mide si un frente va a pararse la próxima semana?', 'Colchones de los frentes previos y kilómetros liberados por delante.')],
    prueba='Caso escrito de 2 horas: se le entrega el tablero de una semana real con un colchón cayendo, dos camiones rechazados y un predio sin liberar. Debe decidir qué hace el lunes, a quién llama y qué deja por escrito. Se evalúa con el Gerente de calidad presente.',
    indicadores=['Avance contra programa sin tocar los colchones mínimos.', 'Cero desviaciones sin firma; núcleos, IRI y permeabilidad dentro de especificación.',
                 'Margen del proyecto contra presupuesto.', 'Cero accidentes graves.', 'A los años 2 y 5: suavidad, agrietamiento y drenes del tramo entregado.'],
    dia=[('06:00', 'Junta de cierre con las cuatro líneas y el tablero de la noche.'), ('Mañana', 'Liberaciones, cliente, compras mayores y visitas a frentes de día.'),
         ('17:30', 'Revisa cómo se armó la noche; resuelve lo que ninguna línea puede resolver sola.'), ('Noche (2 por semana)', 'Recorre el tren sin avisar; habla con operadores y laboratoristas.'),
         ('Lunes', 'Junta de las dos semanas que vienen: colchones, liberaciones y mantenimiento mayor.')],
    saber=['La especificación completa de 50 años y el porqué de cada requisito; el orden para recortar si no alcanza el presupuesto (se recorta desde abajo, nunca el drenaje ni el agua/cemento).',
           'Contratos de obra pública, APP y conservación por disponibilidad: pago por desempeño, descuentos automáticos, indexación y ventana de revisión cada 5 años.',
           'El cotizador del proyecto: precio, piso de precio, capital de trabajo y anualidad de conservación.', 'La aritmética de la obra: 2,270 m³ por km, 227 m³/h, un camión cada 2 minutos.',
           'Las seis cosas que detienen el tren y la séptima (el predio sin liberar).', 'Cómo se estructura el variable de cada línea y el candado de calidad.'],
    numeros=[('500 km-carril', 'lo que cuela un frente al año (1 km de 2 carriles por noche, 250 noches)'), ('20 km', 'derecho de vía liberado siempre por delante; bajo 10 km se levanta la alarma'),
             ('3 días', 'colchón mínimo de cada frente sobre el siguiente'), ('5 %', 'del presupuesto a supervisión independiente y laboratorio con autoridad de rechazo'),
             ('10 %', 'de la producción del día se pierde con una hora de paro del tren')],
    errores=['Reanudar un colado sin entender por qué se detuvo.', 'Firmar un precio por debajo del piso "para no perder el contrato".',
             'Dejar que Calidad reporte a Producción, aunque sea de palabra.', 'Comprar flotilla sin tres años de volumen contratado.'],
    capacitacion=[('Semana 1', 'Lectura completa de la especificación y del modelo de negocio; recorrido de todos los frentes y del tramo de prueba con el Gerente de calidad.'),
                  ('Semanas 2 a 4', 'Una noche completa en cada puesto crítico del tren (planta, despacho, laboratorio, pavimentadora). Revisión del contrato con el área jurídica y del cotizador con administración.'),
                  ('Tramo de prueba', 'Dirige la evaluación de las tres variantes y la decisión de cuál se escala, con datos del laboratorio.'),
                  ('Primer año', 'Revisión trimestral con la dirección general: tablero, margen, gente y cliente.')],
    certificaciones=['Taller de tecnología del concreto para pavimentos (con el Gerente de calidad).', 'Actualización en contratos de obra pública y APP.', 'Liderazgo de equipos en turno nocturno y seguridad en frentes abiertos al tránsito.'],
    comprobacion=['¿Qué tiene que quedar escrito antes de reanudar un colado detenido?', '¿Qué indicador avisa con días de anticipación que un frente se va a parar?',
                  '¿Qué se recorta primero si no alcanza el presupuesto, y qué nunca?', '¿Cuál es el piso de precio del corredor y de dónde sale?'],
    siguiente='Dirección de varios corredores o de la línea de conservación por disponibilidad de la empresa.',
)

P['Gerente de calidad'] = dict(
    linea='Calidad', reporta='Director de Proyecto', esquema='calidad_dir',
    mision='Garantizar que lo construido sea exactamente lo especificado, medido y documentado, para que el pavimento llegue a los 50 años.',
    importa='Es el puesto más difícil de llenar y el más subestimado. Rechaza camiones, detiene colados y para la obra sin pedir permiso a nadie.',
    responde=['El diseño de mezcla validado con los agregados reales del banco.', 'El plan de control: qué se mide, cuándo, por quién y con qué criterio de aceptación.',
              'La aceptación por núcleos, vigas, aire, permeabilidad, contracción y suavidad.', 'La trazabilidad: cada metro colado con su camión, su temperatura y sus ensayos.',
              'El tramo de prueba y la decisión técnica de qué variante se escala.'],
    autoridad=['Rechazar camiones, detener el tren y suspender la noche, sin pedir permiso.', 'Rechazar un banco de agregado, un lote de cemento o de acero que no cumpla.',
               'Pedir al Director que no se reanude hasta resolver la causa.', 'No le toca: dirigir la producción ni negociar el avance.'],
    experiencia=['10 años o más en materiales y tecnología del concreto, al menos 5 en pavimentos rígidos.', 'Idealmente del lado de la supervisión o de la dependencia: ya sabe decir que no.',
                 'Haber diseñado mezclas con ceniza volante o escoria y haber manejado laboratorio acreditado.'],
    escolaridad=['Ingeniería civil o química; maestría en materiales o en tecnología del concreto deseable.', 'Certificaciones de laboratorio y técnico de concreto (tipo ACI) vigentes; conocimiento de normas ASTM y NMX.'],
    persona=['Firme sin ser rígido: explica el porqué de cada rechazo.', 'Incorruptible y visible: no negocia la especificación en privado.',
             'Curioso: quiere saber por qué salió mal una viga, no sólo que salió mal.', 'Escribe todo: si no está registrado, no pasó.'],
    alertas=['Habla de "llenar formatos" y no de decidir.', 'Dice que "con experiencia no hace falta medir".', 'Nunca ha rechazado un camión o no recuerda la última vez.', 'Busca quedar bien con Producción.'],
    preguntas=[('Son las 3 a. m. y llega un camión a 32 °C. El residente le pide dejarlo pasar porque la planta ya enfrió los siguientes. ¿Qué hace?', 'Lo rechaza, registra la causa y verifica que la planta corrija; no se cuela concreto fuera de especificación.'),
               ('¿Por qué la permeabilidad importa más que la resistencia para durar 50 años?', 'Porque un concreto puede ser resistente y permeable a la vez; el agua y los agentes entran por los poros conectados.'),
               ('¿Qué hace si los núcleos de un tramo salen 1.5 cm abajo del espesor?', 'Aplica la penalización del contrato, analiza la causa (rasante, modelo 3D, base) y ajusta el control antes de la siguiente noche.'),
               ('¿Cómo valida que el agregado no es reactivo?', 'Con expansión menor a 0.10 % a 16 días (ASTM C1260) y petrografía del banco, antes de contratarlo.')],
    prueba='Revisión de un expediente real de laboratorio con errores sembrados (una viga mal curada, un aire fuera de rango, un certificado vencido): debe encontrarlos en una hora y decir qué decide con cada uno.',
    indicadores=['Porcentaje de metros con trazabilidad completa.', 'Permeabilidad menor a 1,500 coulombs y contracción ≤ 400 microstrain en los ensayos del mes.',
                 'Núcleos con espesor completo; IRI de aceptación ≤ 1.0 m/km.', 'Cero camiones aceptados fuera de especificación.'],
    dia=[('06:00', 'Junta de cierre: rechazos de la noche y su causa.'), ('Mañana', 'Revisa ensayos, núcleos y vigas; visita banco y planta.'), ('Tarde', 'Libera tramos, revisa el plan de la noche y la temperatura esperada.'),
         ('Noche (varias por semana)', 'Recorre el frente con el laboratorista de turno.'), ('Lunes', 'Presenta tendencias de calidad en la junta de las dos semanas.')],
    saber=['La dosificación completa: cementante 320–350 kg/m³ con 20–25 % de ceniza clase F; agua/cementante ≤ 0.42; aire 5–7 % con espaciamiento ≤ 0.20 mm; revenimiento 3–5 cm; MR 48 kg/cm² a 28 días.',
           'Durabilidad medida: permeabilidad menor a 1,500 coulombs o resistividad ≥ 20 kΩ·cm; contracción ≤ 400 microstrain a 28 días; expansión menor a 0.10 % (ASTM C1260).',
           'Curado interno con pómez presaturada: medir la humedad del agregado en cada bachada; si entra seco, roba agua en lugar de darla.',
           'Evaporación en el frente y cuándo no se cuela; método de madurez para abrir a tráfico (MR 30 kg/cm²).', 'Especificación por desempeño: la mezcla puede evolucionar si cumple los resultados medidos.',
           'Acero en CRCP: 0.70 %, #6 cada 15 cm, a un tercio del espesor sobre sillas, recubrimiento mínimo de 7 cm; anclajes terminales obligatorios.'],
    numeros=[('≤ 30 °C', 'temperatura del concreto en la descarga'), ('≤ 0.42', 'agua/cementante'), ('5–7 %', 'aire incluido'), ('≤ 75 min', 'mezclado a colocación, el peor camión del turno'),
             ('< 0.5 kg/m²/h', 'evaporación máxima de la noche'), ('< 1,500 C', 'permeabilidad'), ('MR 48', 'kg/cm² a 28 días en vigas')],
    errores=['Aceptar un camión "sólo esta vez".', 'Especificar por ingrediente y no por desempeño.', 'Dejar que el laboratorista nocturno reporte al superintendente.', 'No medir sulfatos antes de estabilizar con cal.'],
    capacitacion=[('Semana 1', 'Especificación completa, banco de caliza, planta y ensayos de validación del diseño de mezcla.'),
                  ('Semanas 2 a 4', 'Monta el plan de control y los formatos digitales con el ingeniero de datos; entrena al jefe de laboratorio y a los laboratoristas en los criterios de rechazo.'),
                  ('Tramo de prueba', 'Diseña, instrumenta y evalúa las tres variantes (con curado interno, sin él, con capa inferior de RCC).'),
                  ('Primer año', 'Informe trimestral de durabilidad al Director y a la supervisión independiente.')],
    certificaciones=['Técnico de concreto y laboratorio (tipo ACI), vigente.', 'Curado interno y agregados ligeros.', 'Sensores de madurez y humedad interna.'],
    comprobacion=['¿Qué dos ensayos especifican la durabilidad directamente?', '¿Qué pasa si el pómez entra seco a la mezcla?', '¿Con qué resistencia se abre a tráfico y cómo se verifica?', '¿A quién reportas, y a quién no?'],
    siguiente='Dirección técnica de la empresa o del área de ingeniería, datos y estándar (la fuente 5 del negocio).',
)

P['Gerente de logística'] = dict(
    linea='Logística y equipo', reporta='Director de Proyecto', esquema='direccion',
    mision='Que nunca falte concreto en el frente: el intervalo de dos minutos, el inventario de cemento y ceniza y la disponibilidad de las cuatro máquinas críticas.',
    importa='La restricción real de una obra de pavimento no es la máquina: es la cadena de suministro. Este puesto es un problema de flujo, no de fierro.',
    responde=['El flujo planta–acarreo–frente y el intervalo promedio entre descargas.', 'Inventarios de cemento, ceniza, agregado, acero, diésel y refacciones.',
              'La disponibilidad de planta, pavimentadora, enfriadora y máquina de textura y curado.', 'Los contratos con transportistas, cementera, acería y bancos de agregado.',
              'Los saltos de planta cada 15–20 km, programados como una actividad más.'],
    autoridad=['Ordenar compras y reabastecimientos dentro del presupuesto.', 'Decidir la ubicación de la planta y el calendario de sus saltos.',
               'Exigir a los transportistas el cumplimiento de la cláusula de mando del despachador.', 'No le toca: aceptar concreto fuera de especificación para no parar.'],
    experiencia=['8 años o más en operaciones o cadena de suministro con ritmos continuos (industria, minería, concreto premezclado).', 'Manejo de flotas de más de 20 unidades con GPS.',
                 'No es indispensable venir de la construcción: a veces es mejor que venga de la logística industrial.'],
    escolaridad=['Ingeniería industrial, civil o afín; formación en logística o investigación de operaciones deseable.', 'Manejo de tableros, rutas y modelos de inventario.'],
    persona=['Piensa en flujo y en cuellos de botella.', 'Tiene la ruta de acarreo cronometrada y sabe a qué hora se pone lento cada cruce.', 'Negocia firme con proveedores y cumple lo que promete.', 'Se adelanta: pide antes de que falte.'],
    alertas=['Resuelve la falta de camiones "comprando más camiones".', 'No conoce el costo de una hora de paro.', 'Habla de maquinaria y no de ciclos.'],
    preguntas=[('La planta está a 15 km y el intervalo sube a 3.5 minutos. ¿Qué mueve primero?', 'Revisa ciclo y cruces, reserva de camiones y adelanta el salto de planta; no apura la pavimentadora.'),
               ('¿Cuántos días de autonomía de cemento y ceniza tiene que haber en silos?', 'Dos días de colado.'),
               ('Un transportista no acepta que su chofer responda al despachador. ¿Qué hace?', 'No lo contrata: la cláusula de mando es condición.'),
               ('¿Cómo decide cuándo mover la planta?', 'Antes de que el frente pase de 10 km de distancia; se programa con días de anticipación y se prueba 4 horas antes de reanudar.')],
    prueba='Ejercicio con datos de ciclo de camiones (GPS de una noche real): identificar las tres causas del intervalo largo y proponer el plan de la noche siguiente, con números.',
    indicadores=['Intervalo promedio entre camiones ≤ 2.5 min.', 'Camiones fuera de ciclo: cero.', 'Minutos de paro del tren atribuibles a suministro.', 'Disponibilidad de las cuatro máquinas críticas.', 'Días de autonomía de silos siempre ≥ 2.'],
    dia=[('06:00', 'Junta de cierre: intervalos, paros por suministro y camiones fuera de ciclo.'), ('Mañana', 'Proveedores, inventarios y mantenimiento del tren.'), ('17:30', 'Arma la noche con el despachador y el jefe de planta: m³, camiones y temperatura.'), ('Noche', 'Guardia por teléfono; recorre planta y ruta al menos una noche por semana.')],
    saber=['La aritmética: 227 m³/h ÷ 8 m³ = 28 descargas por hora; camiones según distancia: 15 a 5 km, 22 a 10 km, 29 a 15 km, más 15 % de reserva.', 'Límite duro: el concreto se coloca dentro de 60 a 90 minutos del mezclado, menos con calor.',
           'Planta de 250–280 m³/h: nunca al 100 % de su capacidad nominal.', 'Las cuatro máquinas críticas no tienen sustituto a media noche: planta, pavimentadora, enfriadora y textura y curado; cada una con su plan escrito de falla.', 'Contratos anuales indexados de cemento, ceniza y acero; crédito de proveedores a 60 días.'],
    numeros=[('2 min', 'un camión por descarga, toda la noche'), ('≤ 10 km', 'distancia planta–colado'), ('2 días', 'autonomía de silos'), ('15 %', 'camiones de reserva'), ('4 h', 'prueba continua de la planta antes de cada reubicación')],
    errores=['Apurar la pavimentadora para "recuperar" un intervalo largo.', 'Dejar que un camión salga del ciclo a cargar diésel.', 'Mover la planta sin prueba de 4 horas.'],
    capacitacion=[('Semana 1', 'Recorre banco, planta, ruta y frente; cronometra la ruta a distintas horas.'), ('Semanas 2 a 4', 'Monta el tablero de despacho con el ingeniero de datos; firma contratos con la cláusula de mando.'),
                  ('Tramo de prueba', 'Opera la planta y el acarreo del tramo como ensayo general.'), ('Primer año', 'Revisión mensual de costo de acarreo y de disponibilidad de máquinas.')],
    certificaciones=['Gestión de flotas y telemetría.', 'Seguridad en patios de planta y en rutas nocturnas.'],
    comprobacion=['¿Cuántos camiones hacen falta a 10 km, con reserva?', '¿Cuánto tiempo máximo puede pasar entre mezclado y colocación?', '¿Cuáles son las cuatro máquinas críticas?', '¿Por qué la planta se mueve con el frente?'],
    siguiente='Dirección de operaciones de varios corredores.',
)

P['Ingeniero de datos'] = dict(
    linea='Soporte', reporta='Director de Proyecto', esquema='direccion',
    mision='Hacer que el tablero se llene solo, desde la planta, el GPS, la pavimentadora y los sensores, para que todos decidan con datos todos los días.',
    importa='En una obra tradicional este puesto no existe y alguien llena un Excel los viernes. Aquí, sin él, el tablero de doce indicadores muere en el mes tres.',
    responde=['El tablero diario de doce indicadores, listo a las 06:00.', 'La integración de datos: planta, GPS de camiones, control 3D, sensores de madurez y laboratorio.',
              'El modelo digital 3D del corredor y el as-built.', 'La trazabilidad de cada metro colado.', 'Los respaldos y la seguridad de la información.'],
    autoridad=['Definir cómo se captura y se valida cada dato.', 'Marcar un dato como no confiable y exigir su corrección.', 'No le toca: cambiar un dato para que "se vea mejor".'],
    experiencia=['4 años o más en integración de datos, tableros o sistemas de campo; ideal con experiencia en construcción, minería o manufactura.', 'Haber conectado equipos reales (PLC, GPS, sensores) a un tablero.'],
    escolaridad=['Ingeniería en sistemas, civil, industrial o afín.', 'Manejo de bases de datos, APIs, SQL y un lenguaje de programación; nociones de topografía y modelos 3D.'],
    persona=['Técnico híbrido: entiende la obra y los sistemas.', 'Obsesivo con la calidad del dato.', 'Explica simple: un operador entiende su tablero.', 'Automatiza lo que se repite.'],
    alertas=['Propone capturar a mano "mientras tanto".', 'No ha pisado una obra.', 'Diseña tableros con cuarenta indicadores.'],
    preguntas=[('¿Cómo obtiene los minutos de paro del tren sin que nadie los capture?', 'Del control 3D de la pavimentadora (velocidad cero con timestamp) cruzado con la causa que registra el residente.'),
               ('El GPS de un camión se cae a media noche. ¿Qué pasa con el intervalo?', 'Respaldo con el ticket de planta y la hora de descarga; el dato se marca y se corrige.'),
               ('¿Qué hace si un jefe le pide quitar un rechazo del tablero?', 'No lo hace y lo reporta al Director: el tablero dice la verdad o no sirve.')],
    prueba='Con archivos de muestra (tickets de planta, GPS y ensayos), armar en 3 horas un tablero con metros, intervalo, temperatura y rechazos, y explicar cómo lo automatizaría.',
    indicadores=['Tablero publicado a las 06:00 todos los días.', 'Porcentaje de datos capturados automáticamente.', 'Trazabilidad completa por metro colado.', 'Cero pérdidas de información.'],
    dia=[('05:00–06:00', 'Cierra y valida el tablero de la noche.'), ('06:00', 'Junta de cierre: explica los datos, no los opina.'), ('Día', 'Integraciones, as-built, modelo 3D y soporte a topografía y laboratorio.'), ('17:30', 'Prepara el tablero de la noche.')],
    saber=['Los doce indicadores del tablero, su meta y quién los reporta.', 'Fuentes: la planta entrega m³, hora y temperatura por camión; el GPS da ciclo e intervalo; el control 3D da metros, velocidad y paros; los sensores dan madurez.',
           'Modelo digital 3D cargado en motoconformadoras, pavimentadora y rovers, verificado contra puntos físicos.', 'Sensores embebidos: abrir a tráfico y cortar juntas con dato, no con calendario.', 'Mantenimiento por excepción: el activo avisa qué 300 metros necesitan atención.'],
    numeros=[('12', 'indicadores del tablero'), ('06:00', 'hora en que el tablero tiene que estar listo'), ('3', 'indicadores rey: minutos de paro, colchones y km liberados')],
    errores=['Tableros que dependen de captura manual.', 'Datos sin fecha ni fuente.', 'Maquillar un número.'],
    capacitacion=[('Semana 1', 'Una noche completa en el frente y un día en planta; inventario de fuentes de datos.'), ('Semanas 2 a 4', 'Integraciones y primer tablero automático con datos reales.'),
                  ('Tramo de prueba', 'Instrumenta las tres variantes y publica sus datos.'), ('Primer año', 'Tablero del activo para la conservación por disponibilidad.')],
    certificaciones=['Topografía con GNSS y modelos 3D.', 'Seguridad de la información.'],
    comprobacion=['¿De dónde sale cada uno de los tres indicadores rey?', '¿Qué haces si una fuente de datos falla de noche?', '¿Para qué sirven los sensores de madurez?'],
    siguiente='Líder de ingeniería de datos y del tablero del activo (servicio de la fuente 5 del negocio).',
)

P['Responsable de liberaciones'] = dict(
    linea='Soporte', reporta='Director de Proyecto', esquema='direccion',
    mision='Que siempre haya 20 kilómetros de derecho de vía liberados por delante del colado: predios, ductos, líneas y permisos resueltos.',
    importa='Administra el riesgo más caro de todos: un frente detenido semanas por un predio, con toda la flotilla y la nómina corriendo.',
    responde=['El semáforo semanal de liberaciones por kilómetro.', 'Acuerdos con propietarios, ejidos y comunidades.', 'Reubicación de ductos, líneas eléctricas y cruces con dependencias.',
              'Permisos ambientales y de dependencias antes de que el frente llegue.'],
    autoridad=['Negociar acuerdos dentro de los parámetros autorizados por el Director.', 'Levantar la alarma cuando lo liberado baja de 10 km y pedir frenar a propósito bajo 5 km.', 'No le toca: prometer lo que no está autorizado.'],
    experiencia=['6 años o más en gestión de derecho de vía, liberación de predios o relación con comunidades en obra de infraestructura.', 'Trato con dependencias federales, estatales y municipales, y con propietarios.'],
    escolaridad=['Derecho, ingeniería, arquitectura o ciencias sociales; conocimiento de régimen agrario y de trámites ambientales.'],
    persona=['Escucha antes de ofrecer.', 'Cumple lo que acuerda y lo deja por escrito.', 'Paciente y constante: da seguimiento semanal a cada pendiente.', 'Íntegro: jamás ofrece nada fuera de la ley.'],
    alertas=['Presume "arreglos rápidos" sin papeles.', 'Habla mal de las comunidades.', 'No sabe cuánto cuesta una semana de frente parado.'],
    preguntas=[('Un propietario se niega en el km 14 y el frente está en el km 2. ¿Qué hace esta semana?', 'Escala, abre alternativas (trazo, acceso, plazo) y avisa al Director con fecha; no espera a que el frente llegue.'),
               ('¿Qué significa el semáforo en rojo?', 'Menos de 5 km liberados: se frena a propósito para no quedar atrapados.')],
    prueba='Presentar en 45 minutos un plan de liberación de 20 km con tres predios difíciles, un ducto y una línea eléctrica, con fechas y responsables.',
    indicadores=['Kilómetros liberados por delante, cada semana (≥ 20).', 'Días de frente detenido por liberación: cero.', 'Acuerdos firmados y cumplidos.'],
    dia=[('Lunes', 'Presenta el semáforo en la junta de las dos semanas.'), ('Semana', 'Visitas a propietarios, dependencias y comunidades.'), ('Viernes', 'Actualiza el semáforo por kilómetro.')],
    saber=['El semáforo: verde ≥ 20 km, amarillo bajo 10 km (alarma), rojo bajo 5 km (se frena a propósito).', 'Los tiempos reales de cada dependencia para cruces y reubicaciones.', 'El impacto social de la obra: empleo local, accesos, polvo y ruido.'],
    numeros=[('20 km', 'liberados por delante, siempre'), ('10 km', 'alarma'), ('5 km', 'se frena a propósito')],
    errores=['Enterarse del problema cuando el frente ya llegó.', 'Acuerdos de palabra.', 'Prometer lo que no está autorizado.'],
    capacitacion=[('Semana 1', 'Recorre los primeros 40 km del corredor con topografía; inventario de predios y cruces.'), ('Semanas 2 a 4', 'Arma el semáforo y el plan de 20 km; primeras reuniones con dependencias.'), ('Primer año', 'Revisión mensual con el Director.')],
    certificaciones=['Gestión social y derecho de vía.', 'Trámites ambientales (manifestación de impacto ambiental).'],
    comprobacion=['¿Cuántos km liberados debe haber siempre y qué pasa bajo 10 y bajo 5?', '¿Por qué un acuerdo de palabra no sirve?'],
    siguiente='Gerencia de relación con comunidades y derecho de vía de varios corredores.',
)
