# -*- coding: utf-8 -*-
# RLR · Perfiles de Mando y staff — Ricardo López Reyero
P = {}

P['Superintendente de frente'] = dict(
    linea='Producción', reporta='Director de Proyecto', esquema='mando',
    mision='Dirigir los cinco frentes escalonados para que el tren de colado nunca alcance terreno sin preparar ni sin liberar, cuidando los colchones antes que los metros.',
    importa='Es el dueño del único indicador que avisa con días de anticipación que el frente se va a parar: el colchón de cada frente. Un superintendente que persigue metros sin ver colchones choca el tren contra el drenaje en tres semanas.',
    responde=['El avance de los cinco frentes: terracería, drenaje, base, colado y acabado, a 1 km por día cada uno.',
              'Los colchones: que cada frente lleve al menos 3 días de ventaja sobre el siguiente, medidos todos los días en días al ritmo actual.',
              'Los kilómetros liberados por delante, junto con el Responsable de liberaciones: nunca menos de 20 km.',
              'La secuencia de campo: acero dos días adelante, base lista días antes, drenaje semanas antes.',
              'El mando de los cabos de terracería, drenaje, base y acabado, del residente de colado y de los topógrafos.',
              'La subida de ritmo al arranque: 400–600 m por noche en la semana 13 y ritmo pleno hasta las semanas 14 a 16.'],
    autoridad=['Mover gente, horas y equipo rentado de un frente a otro para reforzar un colchón que baja del mínimo.',
               'Frenar a propósito el colado cuando un frente previo se le acerca, en lugar de correr hasta chocar.',
               'Asignar y cambiar cabos de frente, con visto bueno del Director.',
               'No le toca: pedirle a Calidad que deje pasar un camión, ni reanudar un colado detenido; eso es sólo del Director.'],
    experiencia=['8 a 15 años en campo carretero, con al menos 3 dirigiendo varios frentes a la vez en pavimento rígido o terracerías de autopista.',
                 'Haber llevado un frente que se atrasó y saber contar cómo lo recuperó sin sacrificar calidad.',
                 'Mando directo de más de 60 personas y de flotilla pesada en turnos de día y de noche.'],
    escolaridad=['Ingeniería civil o técnico en construcción con experiencia equivalente comprobable: aquí la experiencia vale más que el título.',
                 'Manejo de programa de obra, lectura de planos, secciones y modelo 3D.',
                 'Deseable: curso de seguridad en construcción (NOM-031-STPS) y de concreto para pavimentos.'],
    persona=['Recorre el corredor completo todos los días en camioneta y sabe de memoria en qué kilómetro está cada frente.',
             'Detecta que el drenaje se está quedando atrás antes de que alguien se lo reporte.',
             'Pide ayuda temprano: prefiere reforzar un frente el martes que explicar un paro el viernes.',
             'Respeta a Calidad en público y en privado; nunca discute un rechazo delante de la cuadrilla.',
             'Da órdenes claras y cortas por radio, y confirma que se entendieron.'],
    alertas=['Mide su éxito sólo en metros colados.', 'Habla de "sacar el trabajo" y nunca de colchones o de liberaciones.',
             'Cuenta con orgullo noches en que "le apretó" a la pavimentadora para recuperar tiempo.', 'Dice que el laboratorio "le frena la obra".'],
    preguntas=[('El drenaje trae 1.5 días de colchón y el colado va a ritmo pleno. ¿Qué hace hoy?', 'Refuerza el drenaje de inmediato (gente, horas, equipo rentado) y, si no alcanza, baja a propósito el ritmo del colado; nunca deja que el colchón llegue a cero.'),
               ('¿Por qué no conviene que un frente se adelante demasiado?', 'Porque la zanja de dren abierta de más se azolva y la base expuesta se contamina: se mantiene el colchón, no se maximiza.'),
               ('Son las 23:00 y el laboratorista rechaza tres camiones seguidos. ¿Qué hace usted?', 'Nada contra el rechazo: pregunta la causa, llama al jefe de planta para que corrija desde la planta y registra los minutos de paro con su causa.'),
               ('El cliente quiere 1.5 km por noche. ¿Qué le propone?', 'Clonar el frente desde el otro extremo del corredor, no acelerar un solo tren.')],
    prueba='Recorrido de campo de medio día en un frente real o en el tramo de prueba: con el programa y los datos de avance de una semana, debe decir en qué kilómetro está cada frente, calcular los colchones en días al ritmo actual, detectar el frente en riesgo y presentar en 20 minutos el plan de refuerzo de la semana siguiente. Aprueba si identifica el colchón crítico y propone un refuerzo con números sin tocar el curado ni la temperatura.',
    indicadores=['Metros colados contra programa del trimestre.', 'Colchón de cada frente previo ≥ 3 días, todos los días.',
                 'Kilómetros liberados por delante ≥ 20.', 'Minutos de paro del tren atribuibles a frentes previos: cero.', 'Cero accidentes con tiempo perdido en sus frentes.'],
    dia=[('06:00', 'Junta de cierre: reporta colchones y kilómetros liberados; escucha minutos de paro con causa.'),
         ('07:00–12:00', 'Recorre los cinco frentes en orden, de terracería a acabado; habla con cada cabo en su frente.'),
         ('Mediodía', 'Revisa con topografía y con el laboratorio lo que se libera para mañana; ajusta el programa de la semana.'),
         ('16:00–19:00', 'Arranque del tren: verifica que el acero de pasado mañana está puesto y que el residente recibe todo listo.'),
         ('Lunes', 'Junta de las dos semanas con el Director: colchones, liberaciones y refuerzos.')],
    saber=['El escalonamiento: cinco frentes a 1 km por día cada uno, el colado siempre el último, colchón mínimo de 3 días de cada frente sobre el siguiente.',
           'Las tres reglas del colchón: se mide todos los días en días de ventaja; nadie lo gasta para verse bien; si baja del mínimo, se refuerza ese frente de inmediato.',
           'Reforzar un frente cuesta miles; parar el tren cuesta cientos de miles. Una hora de paro del tren es el 10 % de la producción del día.',
           'El acero va dos días adelante porque la cuadrilla de varilla es la única parte que no se acelera comprando una máquina; si el acero limita, se duplica esa cuadrilla.',
           'La sección tipo: 2 carriles de 4.20 m (8.40 m) por 27 cm = 2.27 m³ por metro, 2,270 m³ por kilómetro, 227 m³ por hora en 10 horas.',
           'La receta de abajo hacia arriba y lo que cada frente entrega: subrasante 30 cm al 95 % Proctor modificado punto por punto, subbase drenante con geotextil y dren de borde de 10 cm con salidas cada 60–100 m, base de concreto pobre de 15–20 cm, interfaz de 4–6 cm, losa CRCP de 27 cm.',
           'El semáforo de liberaciones: verde ≥ 20 km, alarma bajo 10 km, freno a propósito bajo 5 km.',
           'Cuando el corredor es largo, no se acelera un frente: se clona.'],
    numeros=[('3 días', 'colchón mínimo de cada frente sobre el siguiente'), ('20 km', 'derecho de vía liberado siempre por delante'),
             ('1,000 m', 'meta de colado por noche a ritmo pleno'), ('2 días', 'lo que va el acero adelante del colado'),
             ('10 %', 'de la producción del día que se pierde con una hora de paro'), ('400–600 m', 'ritmo de arranque en la semana 13, antes de subir a pleno')],
    errores=['Correr el colado hasta alcanzar al drenaje, en lugar de frenar a propósito.', 'Dejar que el acero se ponga "al día" en lugar de dos días adelante.',
             'Adelantar de más la zanja de dren o la base para que el avance "se vea bien".', 'Presionar al laboratorista, aunque sea con la mirada.',
             'Prometer 1 km desde la primera noche y arrastrar el retraso desde la semana 13.'],
    capacitacion=[('Días 2 a 5', 'Recorre el corredor completo con el Director y el Responsable de liberaciones; lee la especificación y el programa; conoce a los cinco cabos en su frente.'),
                  ('Semanas 2 a 4', 'Monta con el Ingeniero de datos la medición diaria de colchones; una noche completa junto al residente de colado y una en planta con el jefe de planta.'),
                  ('Tramo de prueba', 'Dirige la construcción de los 500 m con las tres variantes; entrena a los cabos en la secuencia y en la regla del colchón.'),
                  ('Primer trimestre', 'Revisión con el Director de colchones, paros por frentes previos y seguridad; ajuste del programa de subida a ritmo pleno.')],
    certificaciones=['NOM-031-STPS: seguridad en obras de construcción (curso de mandos).', 'Taller de tecnología del concreto para pavimentos, con el Gerente de calidad.',
                     'Programación y control de obra con tablero y modelo 3D.', 'Liderazgo de cuadrillas en turno nocturno.'],
    comprobacion=['¿Cómo se mide el colchón y cuál es el mínimo?', '¿Qué haces si el colchón del drenaje baja de 3 días?',
                  '¿Por qué el acero va dos días adelante?', '¿Cuántos kilómetros liberados debe haber y qué pasa bajo 10 y bajo 5?'],
    siguiente='Director de Proyecto de un corredor, empezando por el segundo frente clonado.',
)

P['Residente de colado'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='mando',
    mision='Dirigir el tren de colado cada noche para colar 1,000 metros sin parar, con cero agua añadida y curado inmediato, y reportar cada minuto de paro con su causa.',
    importa='Es el dueño del tren de 19:00 a 05:00. De su criterio depende que la pavimentadora no se detenga y que, cuando se detenga, la causa quede escrita y no se repita.',
    responde=['Los metros colados de la noche (meta ≥ 1,000 m).', 'Los minutos de paro del tren con su causa (meta < 30 min): el insumo principal de la junta de las 06:00.',
              'La coordinación entre colocadora, pavimentadora, textura y curado, y la distancia correcta entre ellas.',
              'El arranque del tren entre 16:00 y 19:00: planta, primeras revolturas, torres de luz y acero revisado.',
              'El mando del cabo de colado y, a través de él, de toda la cuadrilla nocturna.'],
    autoridad=['Parar el tren sin consultar a nadie cuando algo pone en riesgo la calidad o a la gente.',
               'Ajustar la velocidad de la pavimentadora dentro de 1 a 2 metros por minuto según llega el concreto.',
               'Mandar colocar rompevientos o suspender el colado de la noche si la evaporación sube de 0.5 kg/m²·h.',
               'No le toca: reanudar un colado detenido por Calidad o Seguridad (eso es sólo del Director), ni aceptar un camión que el laboratorista rechazó.'],
    experiencia=['5 a 10 años en pavimento rígido, con al menos 2 temporadas de colado con pavimentadora de cimbra deslizante en autopista o aeropuerto.',
                 'Haber vivido una noche que salió mal (junta fría, camión rechazado en cadena, falla de máquina) y saber explicar qué cambió después.',
                 'Experiencia en concreto reforzado continuo o, al menos, en losa con pasajuntas y control 3D.'],
    escolaridad=['Ingeniería civil titulada.', 'Deseable: certificación de técnico de campo en concreto (ACI Grade I) y curso de pavimentos de concreto.'],
    persona=['Conoce por nombre a los operadores de las cuatro máquinas críticas y sabe qué le duele a cada una.',
             'Mantiene la calma por radio a las 3 de la mañana; habla corto y en voz baja.',
             'Escribe la causa del paro en el momento, no al final del turno.', 'Respeta un rechazo del laboratorio sin discutirlo frente a la cuadrilla.',
             'Camina el tren varias veces por noche, no lo dirige desde la camioneta.'],
    alertas=['Presume noches de "récord" sin hablar de paros ni de curado.', 'Dice que "un poco de agua" ayuda a la pavimentadora.',
             'No sabe cuánto concreto lleva un metro de losa.', 'Culpa siempre a la planta o a los camiones y nunca a la organización del tren.'],
    preguntas=[('La pavimentadora espera concreto cada 5 minutos. ¿Qué hace con la velocidad?', 'Baja la velocidad para mantenerla en movimiento continuo, llama al despachador y registra la causa; nunca acelera después para "recuperar".'),
               ('El viento sube y la evaporación calculada llega a 0.6 kg/m²·h. ¿Qué hace?', 'Rompevientos, niebla si aplica, membrana a doble dosis inmediata; si no baja de 0.5, suspende y lo deja escrito.'),
               ('¿Por qué importa la distancia entre la colocadora y la pavimentadora?', 'Si se separa de más, el concreto pierde trabajabilidad antes de entrar al molde; si la textura y curado se retrasa, la superficie se seca al aire.'),
               ('Un acabador le pide agua para cerrar una orilla. ¿Qué responde?', 'Que no: se corrige con el equipo y el aditivo que manda el laboratorio, nunca con agua.')],
    prueba='Una noche completa en el tramo de prueba o en un frente real, a la sombra del residente titular: debe llevar el registro de paros minuto a minuto con causa, calcular la evaporación cada hora con la estación del frente y decidir en voz alta tres situaciones planteadas por el Gerente de calidad. Aprueba si su registro coincide con el control 3D de la pavimentadora en ± 5 minutos y ninguna decisión viola las tres reglas.',
    indicadores=['Metros colados por noche contra meta.', 'Minutos de paro del tren con causa (< 30 min por noche).', 'Cero juntas frías no planeadas.',
                 'IRI del tramo colado ≤ 1.0 m/km.', 'Cero accidentes con tiempo perdido en el tren.'],
    dia=[('16:00', 'Llega al frente; revisa acero de esta noche, base, interfaz y rasante con topografía.'),
         ('17:30', 'Junta para armar la noche con jefe de planta, despachador y laboratorio: m³, camiones, temperatura y riesgos.'),
         ('19:00', 'Arranca el tren; confirma primeras revolturas aceptadas por el laboratorio.'),
         ('19:00–05:00', 'Camina el tren; registra cada paro con su causa; vigila evaporación y curado.'),
         ('05:00–06:00', 'Cierre: junta de construcción del día si la hay, limpieza y revisión del tablero.'),
         ('06:00', 'Presenta metros y minutos de paro con causa en la junta de cierre.')],
    saber=['El tren: colocadora-esparcidora, pavimentadora de cimbra deslizante con control 3D, máquina de textura y curado, y pasarela; viajan en serie a 1–2 m por minuto.',
           'La pavimentadora nunca se detiene: cada paro deja una junta fría, una marca y un punto débil que no se repara después.',
           '227 m³ por hora = 28 camiones de 8 m³ por hora = uno cada 2 minutos, 10 horas seguidas.',
           'Revenimiento de 3–5 cm en la descarga; concreto a 30 °C o menos; peor camión del turno ≤ 75 minutos del mezclado a la colocación.',
           'CRCP: losa de 27 cm, acero #6 cada 15 cm y #4 cada 90 cm, a un tercio del espesor sobre sillas con 7 cm de recubrimiento; carril de 4.20 m con la raya a 3.60 m; hombro amarrado con #4 cada 75 cm.',
           'Curado: membrana a doble dosis inmediatamente después de texturizar, evaporación < 0.5 kg/m²·h; un curado descuidado pierde hasta 40 % de la resistencia.',
           'Juntas de construcción al final de la noche con el acero pasado y reforzado según el plano; nunca una junta improvisada.'],
    numeros=[('1,000 m', 'meta de la noche'), ('< 30 min', 'paro máximo del tren por noche'), ('2 min', 'intervalo entre camiones'),
             ('1–2 m/min', 'velocidad del tren'), ('< 0.5 kg/m²·h', 'evaporación máxima'), ('≤ 30 °C', 'temperatura del concreto en la descarga')],
    errores=['Acelerar la pavimentadora para recuperar metros después de un paro.', 'Permitir agua añadida "sólo en la orilla".',
             'Dejar que la máquina de textura y curado se atrase del resto del tren.', 'Reportar un paro sin causa, o con la causa equivocada.',
             'Recortar las tres horas de arranque del tren cuando hay prisa.'],
    capacitacion=[('Días 2 a 5', 'Noches completas con el residente saliente o con el superintendente; recorre planta y ruta con el despachador.'),
                  ('Semana 2', 'Aprende el tablero con el Ingeniero de datos: de dónde salen los minutos de paro y los metros.'),
                  ('Tramo de prueba', 'Dirige el colado de las tres variantes y entrena a la cuadrilla en los tres días de capacitación: agua, temperatura y curado hasta que se repitan solos.'),
                  ('Primer trimestre', 'Revisión mensual con el superintendente de paros por causa y acciones tomadas.')],
    certificaciones=['ACI Concrete Field Testing Technician Grade I.', 'Curso de pavimentos de concreto con cimbra deslizante y CRCP.',
                     'NOM-031-STPS: seguridad en obras de construcción.', 'Control 3D de maquinaria.'],
    comprobacion=['¿Cuántos m³ lleva un metro de losa y cuántos camiones por hora pide la noche?', '¿Qué haces si el concreto llega cada 5 minutos?',
                  '¿Cuándo no se cuela, aunque todo esté listo?', '¿Quién reanuda el tren si Calidad lo detuvo?'],
    siguiente='Superintendente de frente.',
    pedimos=['Escribir la causa de cada paro en el momento en que pasa.'],
)

P['Jefe de planta'] = dict(
    linea='Logística', reporta='Gerente de logística', esquema='frente',
    mision='Producir 227 m³ por hora de concreto dentro de especificación, a 30 °C o menos, sin una sola interrupción durante el turno.',
    importa='La planta es una de las cuatro máquinas que no tienen sustituto a media noche. Un concreto caliente o mal dosificado se corrige en la planta, nunca en el frente.',
    responde=['La dosificación exacta de cada bachada según el diseño de mezcla vigente.', 'La temperatura del concreto: agua con hielo o enfriada, agregado sombreado y prehumedecido.',
              'La humedad del agregado ligero presaturado en cada bachada.', 'La continuidad de la planta: básculas calibradas, bandas, silos con autonomía de 2 días.',
              'Los m³ producidos contra los m³ teóricos colocados (± 3 %).', 'La prueba de 4 horas continuas antes de cada reubicación.'],
    autoridad=['Detener la producción si una báscula, un silo o el enfriamiento fallan.', 'Ajustar la corrección por humedad de los agregados en cada bachada.',
               'Pedir al almacén y al mantenimiento las refacciones y paros preventivos de la planta.',
               'No le toca: cambiar el diseño de mezcla, ni subir el agua para "aflojar" la mezcla; eso es del laboratorio y el agua no se sube nunca.'],
    experiencia=['5 años o más operando o dirigiendo una planta central de concreto de más de 150 m³/h, en premezclado, presas, aeropuertos o pavimentos.',
                 'Haber corregido humedad de agregados, calibrado básculas y trabajado con hielo o agua enfriada en verano.',
                 'Deseable: haber movido y reinstalado una planta móvil.'],
    escolaridad=['Técnico en construcción, mecánica o industrial, o preparatoria con experiencia comprobable.', 'Saber leer un diseño de mezcla y una hoja de calibración.'],
    persona=['Llega antes de que arranque la planta y revisa silos, hielo y agregados antes de producir.', 'Lleva su bitácora por hora sin que se la pidan.',
             'Avisa temprano: si el hielo no alcanza para la noche, lo dice a las 17:30, no a las 23:00.', 'Ordenado y limpio: la planta se ve como se opera.'],
    alertas=['Dice que la humedad del agregado "se ve a ojo".', 'Ha "aflojado" mezclas con agua para que el cliente no se queje.',
             'No sabe cada cuándo calibró las básculas de su última planta.', 'Culpa siempre al laboratorio de los rechazos.'],
    preguntas=[('A las 22:00 el agregado grueso sube a 34 °C. ¿Qué hace?', 'Más hielo o agua más fría, riego y sombra del acopio, y avisa al laboratorio; no espera a que los camiones sean rechazados.'),
               ('El pómez presaturado llega con menos humedad de la esperada. ¿Qué pasa y qué hace?', 'Si entra seco roba agua a la mezcla: se detiene esa fracción, se vuelve a saturar y se ajusta la dosificación con el laboratorio.'),
               ('¿Cómo sabe que la planta está dando lo que dice?', 'Calibración de básculas, comparación de m³ producidos contra m³ colocados (± 3 %) y consumo de cemento por m³.'),
               ('¿Por qué la planta no debe trabajar al 100 % de su capacidad nominal?', 'Porque falla el primer día caluroso; por eso se instala de 250–280 m³/h para producir 227.')],
    prueba='Un turno de 4 horas en la planta del proyecto con el jefe de planta titular y el laboratorista: debe arrancar, hacer la corrección por humedad de agregados, sostener la temperatura de salida bajo 30 °C y llevar la bitácora por hora. Aprueba si ningún camión se rechaza por temperatura o revenimiento atribuible a la planta y su diferencia de m³ producidos contra teóricos queda dentro de ± 3 %.',
    indicadores=['m³ colocados contra m³ teóricos dentro de ± 3 %.', 'Camiones rechazados por causa de planta: cero.', 'Minutos de paro del tren por falla de planta.',
                 'Temperatura máxima de salida ≤ 30 °C en el 100 % de la noche.', 'Autonomía de silos ≥ 2 días al cierre de cada turno.'],
    dia=[('16:00', 'Revisa silos, hielo o enfriadora, humedad de agregados y básculas; arranca la planta.'),
         ('17:30', 'Junta para armar la noche: m³, ritmo de camiones, temperatura esperada.'),
         ('18:00–19:00', 'Primeras revolturas de prueba con el laboratorista hasta que pasan.'),
         ('19:00–05:00', 'Produce al ritmo del despachador; corrige humedad y temperatura cada hora; bitácora por hora.'),
         ('05:00–06:00', 'Cierre de producción, limpieza de mezcladora, reporte de m³ y consumos al tablero.')],
    saber=['El diseño de mezcla: cementante 320–350 kg/m³ con 20–25 % de ceniza volante clase F, agua/cementante ≤ 0.42, revenimiento 3–5 cm, aire 5–7 %.',
           'Corrección por humedad: el agua que traen los agregados se descuenta del agua de la mezcla; el agua total nunca sube.',
           'Curado interno: 20–25 % de la arena se sustituye por pómez o tezontle presaturado 24 a 72 horas antes; se mide su humedad en cada bachada.',
           'Enfriamiento: agua con hielo o enfriada, agregado sombreado y prehumedecido; el concreto sale a 30 °C o menos y se corrige aquí, no en el frente.',
           'Capacidad instalada de 250–280 m³/h para sostener 227 m³/h; nunca al 100 % de la nominal.',
           'Silos de cemento y ceniza con 2 días de autonomía; refacciones críticas en sitio: bandas, sensores, bombas.',
           'La planta salta cada 15–20 km para quedar a menos de 10 km del colado, y no se reanuda sin 4 horas continuas de prueba a 250 m³/h con producto que pasa laboratorio.'],
    numeros=[('227 m³/h', 'lo que tiene que sostener la planta toda la noche'), ('250–280 m³/h', 'capacidad instalada'),
             ('≤ 30 °C', 'temperatura de salida del concreto'), ('± 3 %', 'm³ colocados contra teóricos'), ('2 días', 'autonomía de silos'), ('4 h', 'prueba continua después de cada reubicación')],
    errores=['Subir el agua para "aflojar" una mezcla dura.', 'No medir la humedad del pómez y dejarlo entrar seco.',
             'Esperar a que el laboratorio rechace para empezar a enfriar.', 'Dejar un silo bajar de la autonomía de 2 días.'],
    capacitacion=[('Días 2 a 5', 'Turnos junto al jefe de planta del otro turno; recorre banco de caliza, acopio de pómez y silos.'),
                  ('Semana 2', 'Calibración de básculas con mantenimiento y laboratorio; corrección por humedad paso a paso.'),
                  ('Tramo de prueba', 'Produce las mezclas de las tres variantes; practica la prueba de 4 horas.'),
                  ('Primer año', 'Participa en cada reubicación de planta y en su prueba de arranque.')],
    certificaciones=['Operación y calibración de plantas centrales de concreto (curso del fabricante o equivalente).', 'NOM-004-STPS: protección en maquinaria y equipo.',
                     'NOM-017-STPS: equipo de protección personal.', 'Técnico de campo en concreto (ACI Grade I) deseable.'],
    comprobacion=['¿Cómo corriges la mezcla si el agregado viene mojado?', '¿Qué pasa si el pómez entra seco?',
                  '¿Qué haces si el concreto sale a 31 °C?', '¿Qué se prueba antes de reanudar después de mover la planta?'],
    siguiente='Gerente de logística de un frente, o jefe de plantas de varios frentes.',
)

P['Jefe de laboratorio'] = dict(
    linea='Calidad', reporta='Gerente de calidad', esquema='calidad',
    mision='Dirigir el laboratorio del frente para que cada capa, cada camión y cada metro colado se mida, se registre y se libere sólo si cumple.',
    importa='Es quien convierte la especificación en ensayos de todos los días. Si el laboratorio mide mal o tarde, la obra avanza a ciegas y los defectos aparecen hasta el año ocho.',
    responde=['El plan de ensayos del frente: qué se mide, dónde, cada cuánto y con qué criterio.', 'Las liberaciones de subrasante, subbase, base e interfaz antes de que el siguiente frente las cubra.',
              'Los ensayos del concreto: temperatura, revenimiento, aire por camión, vigas a 28 y 90 días, madurez.',
              'El mando de laboratoristas, laboratoristas de turno, núcleos y mediciones, y operador de perfilómetro.',
              'La trazabilidad de cada resultado con su fecha, su hora, su ubicación y quién lo midió.'],
    autoridad=['Rechazar camiones, capas y materiales que no cumplan, y detener el tren sin pedir permiso.', 'No liberar una capa aunque el frente siguiente esté esperando.',
               'Retirar de la medición a un laboratorista que falsea o no sigue el método.', 'No le toca: cambiar la especificación ni aceptar desviaciones; eso sólo existe firmado por el Director.'],
    experiencia=['8 años o más en laboratorio de concreto y materiales, al menos 3 en pavimentos rígidos o en obra de autopista.',
                 'Haber dirigido un laboratorio de campo y un equipo de laboratoristas, con ensayos de compactación, concreto fresco y endurecido.',
                 'Haber rechazado concreto o capas en obra y sostenido el rechazo.'],
    escolaridad=['Ingeniería civil o química.', 'ACI Concrete Field Testing Technician Grade I y técnico de laboratorio vigentes; conocimiento de normas NMX-C del ONNCCE y ASTM.'],
    persona=['Tiene criterio propio: explica cada rechazo con el dato y la norma.', 'Revisa en campo lo que firma, no desde la oficina.',
             'Enseña con paciencia: sus laboratoristas saben el porqué de cada método.', 'Ordenado: cada muestra con etiqueta, cada viga con su camión.'],
    alertas=['Cree que lo importante es "tener los formatos llenos".', 'Nunca ha visto fallar una viga ni sabe por qué pasa.',
             'Acepta resultados "promedio" cuando la especificación pide punto por punto.', 'Se siente parte de Producción.'],
    preguntas=[('La compactación de la subrasante da 96 % de promedio, pero dos puntos salen 91 %. ¿La libera?', 'No: se verifica punto por punto; esos dos puntos son la bolsa blanda donde se parte la losa. Se recompactan y se vuelven a medir.'),
               ('Las vigas de una noche salen bajas a 28 días y el aire estuvo en rango. ¿Qué revisa?', 'Curado de las vigas, temperatura, agua/cementante real de planta, humedad del pómez y el registro de los camiones de esa noche.'),
               ('¿Cómo decide cuándo se abre a tráfico un tramo?', 'Con el método de madurez calibrado: MR 30 kg/cm² alcanzados según los sensores, no por días de calendario.'),
               ('El superintendente le pide liberar la base antes para ganar un día. ¿Qué hace?', 'Libera sólo con los ensayos completos; si hay prisa, adelanta sus ensayos, no los omite.')],
    prueba='Medio día en el laboratorio de campo: se le entregan cinco resultados reales con errores sembrados (un aire medido fuera de tiempo, una viga sin curar, una compactación por promedio, un certificado de cemento vencido, una temperatura sin hora). Debe encontrar al menos cuatro, decir qué decide con cada uno y luego ejecutar frente al Gerente de calidad un ensayo de aire y uno de revenimiento con el método correcto.',
    indicadores=['Capas liberadas con ensayos completos punto por punto: 100 %.', 'Trazabilidad completa de cada camión y cada viga.',
                 'Cero camiones aceptados fuera de especificación.', 'Resultados publicados en el tablero antes de las 06:00.', 'Cero accidentes en el laboratorio y en el frente.'],
    dia=[('06:00', 'Junta de cierre: rechazos de la noche con su causa, temperatura máxima, peor tiempo de mezclado y evaporación.'),
         ('07:00–13:00', 'Liberaciones del día en terracería, drenaje y base; revisa vigas y núcleos.'),
         ('Tarde', 'Revisa plan de ensayos con el Gerente de calidad; programa laboratoristas.'),
         ('17:30', 'Junta para armar la noche: temperatura esperada y riesgos de mezcla.'),
         ('Noche', 'Disponible por radio; visita el tren sin avisar al menos dos noches por semana.')],
    saber=['Subrasante: 30 cm al 95 % Proctor modificado verificado punto por punto; arcilla con índice plástico > 20 se estabiliza con cal al 3–5 %; sulfatos se miden antes y sobre ~0.1 % no se estabiliza con cal ni cemento.',
           "Base de concreto pobre f'c 100–150 kg/cm², 15–20 cm; interfaz bituminosa de 4–6 cm continua.",
           'Concreto fresco por camión: temperatura ≤ 30 °C, revenimiento 3–5 cm, aire 5–7 % con espaciamiento ≤ 0.20 mm, tiempo de mezclado a colocación ≤ 75 min en el peor camión.',
           'Concreto endurecido: MR 48 kg/cm² a 28 días en vigas y también a 90 días; permeabilidad < 1,500 coulombs o resistividad ≥ 20 kΩ·cm; contracción ≤ 400 microstrain.',
           'Madurez: curva calibrada con la mezcla real; abrir a tráfico con MR 30 kg/cm².',
           'Aceptación por núcleos con penalización por espesor faltante; IRI de aceptación ≤ 1.0 m/km.',
           'Curado interno: la humedad del pómez se mide en cada bachada; si entra seco, roba agua.'],
    numeros=[('95 %', 'Proctor modificado, punto por punto'), ('≤ 30 °C', 'concreto en la descarga'), ('5–7 %', 'aire incluido'),
             ('MR 48', 'kg/cm² a 28 días en vigas'), ('MR 30', 'kg/cm² para abrir a tráfico, por madurez'), ('≤ 1.0 m/km', 'IRI de aceptación')],
    errores=['Liberar por promedio lo que se especificó punto por punto.', 'Estabilizar con cal sin medir sulfatos.',
             'Curar mal las vigas y creer que falló el concreto (o al revés).', 'Dejar que un laboratorista nocturno reporte al residente.'],
    capacitacion=[('Días 2 a 5', 'Con el Gerente de calidad: especificación completa, diseño de mezcla validado y plan de control.'),
                  ('Semanas 2 a 4', 'Monta el laboratorio de campo, verifica equipos y entrena a laboratoristas en métodos y criterios de rechazo.'),
                  ('Tramo de prueba', 'Instrumenta y mide las tres variantes; calibra la curva de madurez con la mezcla real.'),
                  ('Primer año', 'Auditoría trimestral de métodos de sus laboratoristas por el Gerente de calidad.')],
    certificaciones=['ACI Concrete Field Testing Technician Grade I y ACI Concrete Laboratory Testing Technician.', 'Normas NMX-C del ONNCCE para concreto y agregados.',
                     'Laboratorio bajo NMX-EC-17025-IMNC (acreditación ante la EMA).', 'Sensores de madurez y humedad interna.'],
    comprobacion=['¿Por qué se verifica la compactación punto por punto y no por promedio?', '¿Qué mides antes de estabilizar con cal?',
                  '¿Con qué resistencia se abre a tráfico y cómo la verificas?', '¿A quién reportas, y a quién no?'],
    siguiente='Gerente de calidad de un corredor.',
)

P['Laboratorista'] = dict(
    linea='Calidad', reporta='Jefe de laboratorio', esquema='calidad',
    mision='Medir, con el método correcto y a tiempo, cada capa y cada muestra de concreto que le toque, y rechazar lo que no cumpla sin pedir permiso a nadie.',
    importa='Es el que tiene el termómetro, el cono y la olla de aire en la mano. Si mide mal, el laboratorio entero decide mal. Rota entre el día y la noche, así que conoce la obra completa.',
    responde=['Las pruebas de compactación y humedad de subrasante, subbase y base, punto por punto.', 'Temperatura, revenimiento y aire del concreto cuando cubre el tren.',
              'El colado, curado y transporte de vigas y cilindros, cada uno con su camión.', 'La lectura de sensores de madurez y humedad interna.',
              'La captura de cada resultado en la tableta, con hora, ubicación y camión.'],
    autoridad=['Rechazar un camión o una capa que no cumpla, sin pedir permiso.', 'Pedir que se detenga el trabajo en una capa hasta terminar su ensayo.',
               'No le toca: cambiar el diseño de mezcla ni decidir desviaciones; y nunca recibe órdenes de Producción sobre un resultado.'],
    experiencia=['2 años o más como laboratorista de campo en concreto y terracerías, con pruebas de compactación, revenimiento, aire y colado de especímenes.',
                 'Haber trabajado turnos nocturnos en obra.', 'Deseable: experiencia con densímetro nuclear o equipo equivalente y con sensores de madurez.'],
    escolaridad=['Preparatoria o técnico en construcción o laboratorio.', 'Saber usar tableta y hacer operaciones básicas; licencia de manejo deseable.'],
    persona=['Hace el ensayo completo aunque tengan prisa: no se salta pasos.', 'Dice lo que midió, aunque no le guste a nadie.',
             'Cuida su equipo: limpia el cono y la olla después de cada prueba.', 'Pregunta cuando no entiende un resultado.'],
    alertas=['Dice que "ya sabe" cuánto da una prueba sin hacerla.', 'Ha cambiado un resultado para no parar la obra.', 'No sabe cómo se curan las vigas.'],
    preguntas=[('El cabo te dice que la capa "ya está" y que no hace falta medir ese tramo. ¿Qué haces?', 'Mido todos los puntos que marca el plan; sin medición no se libera.'),
               ('¿Qué pasa si una viga se queda al sol toda la mañana antes de curarla?', 'Sale baja y hace creer que el concreto falló; las vigas se curan como dice la norma, desde el primer momento.'),
               ('Un camión da 31 °C. ¿Qué haces?', 'Lo rechazo, lo registro con la hora y aviso al jefe de planta y al jefe de laboratorio.')],
    prueba='En campo, 3 horas, con el Jefe de laboratorio: hacer 5 pruebas de compactación en subrasante, un revenimiento, una prueba de aire y colar dos vigas con su etiqueta, capturando todo en la tableta. Aprueba si los métodos son correctos paso a paso, los resultados coinciden con los del jefe dentro de la tolerancia de la norma y la captura queda completa.',
    indicadores=['Ensayos del plan hechos a tiempo: 100 %.', 'Resultados capturados completos (hora, ubicación, camión) antes del cierre del turno.',
                 'Vigas y cilindros bien curados y trazables: cero perdidos.', 'Cero accidentes.'],
    dia=[('Turno de día', 'Compactación y humedad en terracería y base; liberaciones con el jefe de laboratorio.'),
         ('Tarde', 'Cura y traslada vigas; lee sensores de madurez de las losas recientes.'),
         ('Turno de noche (cuando rota)', 'En el tren con el laboratorista de turno: temperatura, revenimiento y aire; cuela vigas.'),
         ('Cierre del turno', 'Sube los resultados a la tableta y entrega el turno por escrito.')],
    saber=['Compactación: 95 % Proctor modificado punto por punto en los 30 cm de subrasante; un punto bajo no se compensa con un promedio alto.',
           'Concreto: ≤ 30 °C en la descarga, revenimiento 3–5 cm, aire 5–7 %; se mide dentro de los primeros minutos de la descarga, del tercio medio del camión.',
           'Vigas: se cuelan, se identifican con su camión y hora, y se curan desde el primer momento; se ensayan a 28 y a 90 días (MR 48 kg/cm² a 28).',
           'Madurez: los sensores dicen cuándo la losa llega a MR 30 kg/cm² para abrir a tráfico.',
           'Pómez presaturado: se mide su humedad en cada bachada; si entra seco, roba agua.',
           'Sulfatos: se miden antes de echar cal o cemento a un suelo; sobre ~0.1 % no se estabiliza así.'],
    numeros=[('95 %', 'Proctor modificado, cada punto'), ('3–5 cm', 'revenimiento'), ('5–7 %', 'aire'), ('≤ 30 °C', 'temperatura del concreto'), ('28 y 90 días', 'edades de ensayo de vigas')],
    errores=['Medir el aire o el revenimiento tarde, cuando el concreto ya cambió.', 'Dejar vigas sin curar o sin etiqueta.',
             'Anotar un resultado "de memoria" o redondeado a favor.', 'Aceptar una orden de Producción sobre un resultado.'],
    capacitacion=[('Días 2 a 5', 'Con el jefe de laboratorio: cada método paso a paso y práctica en el laboratorio de campo.'),
                  ('Semana 2', 'Turnos de día en terracería y base; primera noche en el tren junto al laboratorista de turno.'),
                  ('Tramo de prueba', 'Mide las tres variantes y aprende a leer sensores de madurez y humedad.'),
                  ('Mes 3', 'Examen práctico con el jefe de laboratorio para quedar solo en turno.')],
    certificaciones=['ACI Concrete Field Testing Technician Grade I.', 'Normas NMX-C del ONNCCE: muestreo, revenimiento, aire y elaboración de especímenes.',
                     'Manejo seguro de densímetro nuclear, si se usa (licencia de la autoridad nuclear).', 'NOM-017-STPS: equipo de protección personal.'],
    comprobacion=['¿Por qué no sirve el promedio en compactación?', '¿Cuándo y de qué parte del camión se toma la muestra?',
                  '¿Qué haces con una viga recién colada?', '¿A quién le avisas cuando rechazas un camión?'],
    siguiente='Laboratorista de turno (nocturno, con autoridad sobre cada camión) y después Jefe de laboratorio.',
)

P['Topógrafo · control 3D'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='frente',
    mision='Mantener el modelo digital 3D del corredor correcto y verificado en cada máquina y en cada rover, para que cada capa quede en su nivel exacto y quede registrada como se construyó.',
    importa='Sin estacas ni hilos, la rasante, el espesor de 27 cm y el bombeo de 2 % dependen de que el modelo y la estación base estén bien. Un error de modelo se cuela en kilómetros antes de que alguien lo note.',
    responde=['El modelo digital 3D cargado en motoconformadoras, extendedora, pavimentadora y rovers.', 'La estación base GNSS y los 4 rovers: calibrados y verificados contra puntos físicos.',
              'Los niveles de cada capa antes de que el siguiente frente la cubra.', 'El as-built: espesor y geometría reales de cada metro colado.',
              'El trazo de drenes, salidas cada 60–100 m y cabezales.'],
    autoridad=['Detener una máquina que trabaja con un modelo equivocado o sin señal confiable.', 'No entregar niveles de una capa fuera de tolerancia al siguiente frente.',
               'Pedir corrección de rasante antes de que el tren cuele sobre ella.', 'No le toca: cambiar el proyecto geométrico sin la firma del Director.'],
    experiencia=['4 años o más en topografía de obra carretera, con al menos 2 operando control de maquinaria 3D con GNSS (no sólo estación total).',
                 'Haber cargado y verificado modelos en motoconformadoras o pavimentadoras.', 'Experiencia en levantamiento as-built y en trabajo nocturno.'],
    escolaridad=['Técnico o ingeniero topógrafo, o ingeniería civil.', 'Manejo de software de diseño y modelos de superficie; lectura de secciones y planos.'],
    persona=['Verifica contra un punto físico antes de confiar en la pantalla.', 'Explica a los operadores con calma qué ven en su pantalla y qué significa.',
             'Detallista con los datos: nombra y respalda cada archivo.', 'Se mueve rápido entre frentes y responde por radio.'],
    alertas=['Nunca ha trabajado con control 3D, sólo con estación total.', 'No revisa la estación base al empezar el turno.', 'Dice que "unos centímetros no importan".'],
    preguntas=[('La pavimentadora da 25.5 cm en un tramo según el control 3D. ¿Qué revisas?', 'Modelo cargado, nivel de la base e interfaz, calibración de sensores y base GNSS; aviso al residente antes de que avance más.'),
               ('¿Cada cuándo verificas el modelo contra puntos físicos?', 'Al inicio de cada turno y cada vez que cambia algo (máquina, base, modelo), con puntos de control conocidos.'),
               ('¿Por qué importa el bombeo transversal de 2 %?', 'Porque el agua tiene que salir hacia el dren de borde; una zona plana guarda agua bajo la losa.')],
    prueba='Medio día en el tramo de prueba: debe instalar y verificar la estación base, comprobar un rover contra tres puntos de control, cargar un modelo en una máquina y levantar el as-built de 100 m de base. Aprueba si sus verificaciones cierran dentro de la tolerancia del proyecto y el levantamiento queda completo y nombrado correctamente.',
    indicadores=['Capas entregadas dentro de tolerancia al primer intento.', 'Minutos de paro del tren por modelo o señal: cero.',
                 'As-built del metro colado completo y entregado en 24 horas.', 'Espesor de losa confirmado por núcleos sin faltantes.'],
    dia=[('Inicio de turno', 'Verifica estación base y rovers contra puntos de control.'), ('Día', 'Niveles de subrasante, subbase y base; trazo de drenes y salidas.'),
         ('16:00–19:00 (turno de noche)', 'Revisa rasante e interfaz frente al tren; verifica modelo en la pavimentadora.'),
         ('Noche', 'Soporte al tren por radio; cuida la señal y la base GNSS.'), ('Cierre', 'Descarga datos del control 3D y prepara el as-built.')],
    saber=['Sección: dos carriles de 4.20 m con la raya a 3.60 m, losa de 27 cm, hombro de concreto amarrado.',
           'Capas: subrasante 30 cm, subbase drenante 15–20 cm, base 15–20 cm, interfaz 4–6 cm, losa 27 cm; el espesor de la losa depende de que la base esté en su nivel.',
           'Bombeo transversal de 2 % sin zonas planas; rasante de la losa al menos 80 cm arriba del nivel más alto del agua subterránea.',
           'Dren de borde perforado de 10 cm con salidas cada 60–100 m, cabezal visible y registro de limpieza.',
           'Estación base GNSS + 4 rovers; modelo verificado contra puntos físicos antes de cada turno.',
           'El control 3D de la pavimentadora también registra metros, velocidad y paros: ese dato alimenta el tablero.',
           'Acero a un tercio del espesor desde arriba con 7 cm de recubrimiento: la altura de sillas se revisa contra el nivel de la base.'],
    numeros=[('27 cm', 'espesor de losa'), ('2 %', 'bombeo transversal'), ('80 cm', 'altura mínima de rasante sobre el agua subterránea'),
             ('60–100 m', 'separación de salidas del dren'), ('1 + 4', 'estación base y rovers del frente')],
    errores=['Confiar en la pantalla sin verificar contra un punto físico.', 'Dejar pasar una base alta: la losa sale delgada y se descubre en los núcleos.',
             'Perder o sobrescribir datos del as-built.', 'Dejar zonas planas sin bombeo.'],
    capacitacion=[('Días 2 a 5', 'Con el topógrafo del otro turno: puntos de control, estación base y modelos del corredor.'),
                  ('Semana 2', 'Con el Ingeniero de datos: cómo sale el as-built y el dato de paros del control 3D.'),
                  ('Tramo de prueba', 'Carga y verifica modelos en todas las máquinas; levanta el as-built de las tres variantes.'),
                  ('Mes 3', 'Revisión con el superintendente de capas al primer intento y paros por modelo.')],
    certificaciones=['Control de maquinaria 3D con GNSS (curso del fabricante o equivalente).', 'NOM-031-STPS: seguridad en obras de construcción.',
                     'Trabajo seguro junto a maquinaria en movimiento.'],
    comprobacion=['¿Cada cuándo y cómo verificas el modelo?', '¿Qué pasa con la losa si la base queda alta?',
                  '¿Cuál es el bombeo transversal y por qué?', '¿Qué registra el control 3D además de niveles?'],
    siguiente='Jefe de topografía de varios frentes o apoyo del Ingeniero de datos en modelo digital y as-built.',
)

P['Despachador de camiones'] = dict(
    linea='Logística', reporta='Gerente de logística', esquema='frente',
    mision='Hacer llegar un camión de 8 m³ a la pavimentadora cada 2 minutos, toda la noche, sin que ninguno se salga del ciclo.',
    importa='No es un radioperador: es el controlador de tráfico aéreo de la obra. Administra el recurso más escaso, la continuidad, y un buen despachador vale más que un camión adicional.',
    responde=['El intervalo promedio entre descargas (meta ≤ 2.5 minutos).', 'Que ningún camión se salga del ciclo: ni a cargar diésel, ni a otro lado.',
              'El orden de carga en planta según el avance del tren.', 'La reserva de camiones (15 %) y su entrada cuando uno falla.',
              'El registro de ciclos, retrasos y causas para el tablero.'],
    autoridad=['Mandar sobre todos los choferes, propios y subcontratados: esa cláusula está firmada en el contrato del transportista.',
               'Sacar de la ruta a un chofer que no respeta el ciclo o maneja inseguro, y meter uno de reserva.', 'Pedir a planta que retrase o acelere la carga según el tren.',
               'No le toca: aceptar un camión rechazado por el laboratorio ni mandarlo "a otro lado del frente".'],
    experiencia=['3 años o más despachando flotilla en concreto premezclado, minería o transporte con ritmo continuo, con GPS en vivo.',
                 'Haber manejado 20 o más unidades a la vez en turno nocturno.', 'Deseable: haber sido chofer de revolvedora.'],
    escolaridad=['Preparatoria terminada o técnico en logística.', 'Manejo de tablero de GPS, radio y tableta.'],
    persona=['Ve el tablero y sabe quién va a llegar tarde antes de que llegue tarde.', 'Habla claro y firme por radio, sin gritar.',
             'Se gana el respeto de los choferes: justo con todos, propios y subcontratados.', 'No se distrae: su pantalla es el frente.'],
    alertas=['Resuelve todo "pidiendo más camiones".', 'No sabe calcular un ciclo.', 'Le cuesta dar órdenes a choferes de otra empresa.'],
    preguntas=[('La planta está a 10 km. ¿Cuántos camiones necesitas y por qué?', 'Unos 22 más 15 % de reserva: el ciclo es de ~47 minutos y hacen falta 28 descargas por hora.'),
               ('Un chofer avisa que va a cargar diésel a la gasolinera. ¿Qué respondes?', 'Que no: el diésel se carga en el patio de planta, fuera del ciclo del tren; si hace falta, entra un camión de reserva.'),
               ('El intervalo sube a 3.5 minutos en la última hora. ¿Qué revisas?', 'En qué parte del ciclo se pierde (carga, ruta, cruce, descarga), lo corrige con la reserva y avisa al residente para bajar la velocidad del tren.')],
    prueba='Una noche completa junto al despachador titular, con el tablero de GPS: debe llevar el registro de ciclos, anticipar al menos tres retrasos antes de que pasen y decidir la entrada de la reserva. Después, en 30 minutos, calcula la flotilla para 5, 10 y 15 km. Aprueba si el intervalo de su hora a cargo queda ≤ 2.5 min y sus cálculos coinciden con la tabla del proyecto.',
    indicadores=['Intervalo promedio entre camiones ≤ 2.5 min.', 'Camiones fuera de ciclo: cero.', 'Minutos de paro del tren por falta de concreto.',
                 'Tiempo del peor camión de mezclado a colocación ≤ 75 min.', 'Cero accidentes de tránsito de la flotilla.'],
    dia=[('17:30', 'Junta para armar la noche: m³, camiones, distancia y cruces lentos.'), ('18:00', 'Revisa choferes presentes, diésel cargado en patio y reserva lista.'),
         ('19:00–05:00', 'Despacha un camión cada 2 minutos; vigila el GPS; mete la reserva cuando uno falla.'),
         ('05:00–06:00', 'Cierra ciclos, anota causas de retraso y entrega el intervalo al tablero.')],
    saber=['227 m³/h ÷ 8 m³ = 28 descargas por hora: un camión cada 2 minutos durante 10 horas.',
           'Ciclo = carga 6 min + ida + descarga 6 min + maniobra 5 min + regreso, a 40 km/h promedio: ~32 min a 5 km, ~47 a 10 km, ~62 a 15 km.',
           'Camiones necesarios: 15 a 5 km, 22 a 10 km, 29 a 15 km, más 15 % de reserva; a 25 km (44 camiones) es inviable por tiempo.',
           'Límite duro: el concreto se coloca dentro de 60 a 90 minutos del mezclado, menos con calor; el peor camión del turno ≤ 75 min.',
           'Diésel y baños en el patio de planta; ruta levantada y cronometrada antes de arrancar.',
           'La cláusula de mando: el chofer responde al despachador de la obra, no a su patrón.'],
    numeros=[('2 min', 'intervalo meta entre camiones'), ('≤ 2.5 min', 'intervalo promedio aceptable'), ('28', 'descargas por hora'),
             ('8 m³', 'por camión'), ('15 %', 'camiones de reserva'), ('60–90 min', 'máximo del mezclado a la colocación')],
    errores=['Dejar que un camión salga del ciclo a cargar diésel.', 'Mandar los camiones en bola y dejar huecos después.',
             'Esperar a que el tren se detenga para meter la reserva.', 'Aceptar que un chofer subcontratado "obedezca a su patrón".'],
    capacitacion=[('Días 2 a 5', 'Noches junto al despachador del otro turno; recorre y cronometra la ruta a distintas horas.'),
                  ('Semana 2', 'Tablero de GPS con el Ingeniero de datos; conoce a cada chofer y cada transportista.'),
                  ('Tramo de prueba', 'Despacha el colado de prueba y practica la entrada de la reserva.'),
                  ('Mes 3', 'Revisión con el Gerente de logística de intervalos y causas.')],
    certificaciones=['Gestión de flotillas y GPS.', 'Comunicación por radio y protocolos de emergencia en ruta.', 'NOM-031-STPS: seguridad en obras de construcción.'],
    comprobacion=['¿Cuántos camiones hacen falta a 10 km, con reserva?', '¿Dónde se carga el diésel y por qué?',
                  '¿Cuánto tiempo máximo puede pasar del mezclado a la colocación?', '¿A quién obedece un chofer subcontratado en esta obra?'],
    siguiente='Jefe de despacho de varios frentes o coordinador de acarreo con el Gerente de logística.',
)

P['Seguridad e higiene'] = dict(
    linea='Seguridad', reporta='Director de Proyecto', esquema='seguridad',
    mision='Cuidar que cada persona del frente regrese completa a su casa, y que el frente nocturno abierto al tránsito no lastime a nadie de afuera.',
    importa='El colado es de noche, con camiones cada 2 minutos y un carril abierto al tránsito a unos metros. Este puesto no reporta a Producción para que nadie pueda cambiar seguridad por metros.',
    responde=['El plan de tránsito y desvíos autorizado, con señalización nocturna completa todas las noches.', 'El equipo de protección de todos y su uso correcto.',
              'Las pláticas de seguridad diarias, las inducciones del Día 1 y los recorridos de inspección.', 'La investigación de todo incidente y casi-accidente el mismo día.',
              'El mando de los señaleros de control de tránsito.', 'Higiene: agua, sombra, baños, comedor y prevención de golpe de calor.'],
    autoridad=['Detener cualquier trabajo inseguro, en cualquier frente, sin pedir permiso.', 'Retirar del frente a una persona sin equipo, cansada o bajo efecto de alcohol o sustancias.',
               'No dejar arrancar el colado si la señalización nocturna está incompleta.', 'No le toca: decidir la producción ni negociar la seguridad por avance.'],
    experiencia=['4 años o más como responsable de seguridad en obra carretera o de infraestructura con tránsito abierto y trabajo nocturno.',
                 'Haber implementado señalización de obra en carretera e investigado accidentes.', 'Experiencia con maquinaria pesada y con cuadrillas grandes.'],
    escolaridad=['Técnico o licenciatura en seguridad industrial, ingeniería o afín.', 'Conocimiento de NOM-031-STPS, NOM-086-SCT2 (señalamiento en obras viales) y demás NOM de la STPS aplicables.'],
    persona=['Está en el frente, no en la oficina: se le ve de noche.', 'Firme y respetuoso: corrige sin humillar.',
             'Escucha los casi-accidentes y agradece que se los cuenten.', 'Constante: la plática de cada día se da aunque llueva o haya prisa.'],
    alertas=['Ve la seguridad como "papeles para la auditoría".', 'Nunca ha detenido un trabajo.', 'Culpa siempre al trabajador en los accidentes.'],
    preguntas=[('Son las 19:05 y faltan conos y una flecha luminosa en el desvío. El residente quiere arrancar. ¿Qué haces?', 'No se arranca hasta que la señalización esté completa; lo registro y aviso al Director si hay presión.'),
               ('Un ayudante se marea a las 14:00 en terracería. ¿Qué haces?', 'Lo retiro a la sombra, hidratación, atención médica, y reviso descansos e hidratación de toda la cuadrilla.'),
               ('Alguien te cuenta un casi-accidente que no reportó. ¿Qué haces con él?', 'Le agradezco, lo registro, lo investigo el mismo día y comparto la lección sin castigar a quien lo contó.')],
    prueba='Recorrido de 3 horas en un frente nocturno real o en el tramo de prueba: debe revisar la señalización contra el plan de desvíos, el equipo de protección y la zona de la pavimentadora, y entregar una lista de hallazgos con acciones. Luego dar una plática de 5 minutos a la cuadrilla. Aprueba si encuentra los hallazgos sembrados (al menos cuatro de cinco) y la cuadrilla entiende la plática.',
    indicadores=['Cero accidentes con tiempo perdido y cero incidentes con terceros.', 'Señalización nocturna auditada sin faltantes antes de cada arranque.',
                 'Pláticas diarias dadas: 100 %.', 'Casi-accidentes reportados e investigados el mismo día.'],
    dia=[('06:00', 'Junta de cierre: incidentes y casi-accidentes de la noche.'), ('07:00', 'Plática de seguridad en los frentes de día.'),
         ('Día', 'Recorridos en terracería, drenaje, base y acabado; calor, zanjas, maquinaria.'),
         ('18:00–19:00', 'Revisa señalización y desvíos contra el plan antes de arrancar el tren; plática a la cuadrilla nocturna.'),
         ('Noche (el turno de noche)', 'Recorre el tren y el desvío; supervisa a los señaleros.')],
    saber=['Frente nocturno abierto al tránsito: plan de desvíos autorizado, conos, trafitambos, flechas luminosas y señaleros; chaleco clase 3 de noche.',
           'Zonas de peligro: detrás de máquinas en reversa, entre dos máquinas, en la descarga de camiones cada 2 minutos y en la losa fresca (sólo por la pasarela).',
           'Zanjas del dren: protección de taludes y acceso seguro.', 'Calor: hidratación, sombra y descanso en turnos de día; el golpe de calor se detiene de inmediato.',
           'Torres de iluminación LED (8) y generadores de respaldo: sin luz no hay colado seguro.', 'Cualquiera detiene el trabajo por seguridad sin consecuencias, aunque se equivoque.',
           'Ruido y polvo en planta y en cortadoras: tapones y protección respiratoria.'],
    numeros=[('0', 'accidentes con tiempo perdido'), ('clase 3', 'chaleco de noche'), ('8', 'torres de luz del frente nocturno'),
             ('4', 'señaleros por noche'), ('Mismo día', 'para reportar e investigar un casi-accidente')],
    errores=['Dejar arrancar el colado con la señalización incompleta.', 'Castigar a quien reporta un casi-accidente.',
             'Hacer la seguridad desde la oficina.', 'Ignorar el cansancio del turno nocturno.'],
    capacitacion=[('Días 2 a 5', 'Recorre todos los frentes de día y de noche; revisa el plan de tránsito y desvíos con la dependencia.'),
                  ('Semana 2', 'Entrena a los señaleros y arma las pláticas diarias; prepara la inducción del Día 1 para cada ingreso.'),
                  ('Tramo de prueba', 'Simulacros de emergencia nocturna: atropellamiento, golpe de calor, falla de iluminación.'),
                  ('Primer año', 'Auditoría trimestral con el Director.')],
    certificaciones=['NOM-031-STPS (construcción) y NOM-030-STPS (servicios preventivos de seguridad).', 'NOM-086-SCT2: señalamiento y dispositivos en zonas de obras viales.',
                     'Primeros auxilios y respuesta a emergencias.', 'NOM-017-STPS (equipo de protección) y NOM-004-STPS (maquinaria).'],
    comprobacion=['¿Qué revisas antes de dejar arrancar el tren?', '¿Qué haces con un casi-accidente?',
                  '¿Cuáles son las zonas de peligro del tren?', '¿A quién reportas y por qué no a Producción?'],
    siguiente='Gerente de seguridad de varios frentes o del corredor completo.',
)

P['Almacén y refacciones'] = dict(
    linea='Logística', reporta='Gerente de logística', esquema='frente',
    mision='Tener en el almacén del frente, controlada y lista, cada refacción, insumo y equipo de protección que se necesite, para que no falte un sensor a las 2 de la mañana.',
    importa='Una falla de 20 minutos se vuelve una noche perdida si la refacción está a 40 km. Las refacciones críticas de las cuatro máquinas clave tienen que estar aquí, contadas y a la mano.',
    responde=['El inventario de refacciones críticas de planta, pavimentadora, enfriadora y máquina de textura y curado.', 'Mínimos y máximos de insumos: membrana de curado, sillas, EPP, filtros, bandas, mangueras, sensores.',
              'Entradas y salidas con vale y firma, en el sistema, el mismo día.', 'Pedidos a tiempo para que nada baje del mínimo.', 'El orden y la limpieza del almacén.'],
    autoridad=['Pedir reposición cuando algo baja del mínimo.', 'Negar una salida sin vale o sin firma autorizada.',
               'Rechazar material que llega dañado o fuera de lo pedido.', 'No le toca: comprar fuera de presupuesto ni cambiar marcas o especificaciones de refacción.'],
    experiencia=['2 años o más como almacenista en obra, taller de maquinaria pesada o minería.', 'Manejo de inventario con sistema y vales.',
                 'Deseable: conocer refacciones de maquinaria (filtros, bandas, mangueras hidráulicas).'],
    escolaridad=['Preparatoria terminada o técnico.', 'Manejo de computadora, hoja de cálculo o sistema de inventario.'],
    persona=['Ordenado: todo tiene un lugar con etiqueta.', 'Confiable: los números cuadran.', 'Responde rápido cuando el mecánico llama de noche.', 'Previsor: pide antes de que falte.'],
    alertas=['Lleva el inventario "en la cabeza".', 'No le gusta que le cuenten el almacén.', 'Ha perdido material sin saber explicar cómo.'],
    preguntas=[('A las 2 a. m. el mecánico de turno necesita un sensor de la pavimentadora. ¿Cómo lo encuentra?', 'Por la lista de refacciones críticas y su ubicación; hay protocolo de acceso nocturno con vale y registro.'),
               ('Quedan 3 tambos de membrana de curado. ¿Cuántos días alcanzan?', 'Depende del consumo por noche a doble dosis; si no alcanza para el tiempo de entrega del proveedor más reserva, ya se pidió.'),
               ('¿Qué haces si llega una manguera distinta a la pedida?', 'No la recibo como buena; la aparto, aviso al jefe de mantenimiento y pido la correcta.')],
    prueba='Un día en el almacén: conteo cíclico de 30 artículos contra el sistema, localizar en 5 minutos tres refacciones críticas de la lista y calcular los días de membrana de curado con el consumo real. Aprueba si el conteo coincide con el sistema o explica cada diferencia, y encuentra las refacciones a tiempo.',
    indicadores=['Refacciones críticas de las cuatro máquinas presentes: 100 %.', 'Diferencias de inventario en conteos cíclicos menores al 1 %.',
                 'Minutos de paro del tren por falta de refacción: cero.', 'Salidas con vale y firma: 100 %.'],
    dia=[('07:00', 'Revisa lo que salió de noche con el reporte del mecánico de turno.'), ('Mañana', 'Recibe material, revisa contra pedido y acomoda.'),
         ('Tarde', 'Conteo cíclico; pedidos de reposición; entrega de insumos para la noche (membrana, sillas, EPP).'),
         ('Antes de las 17:00', 'Deja listo lo que pide el tren y las llaves del acceso nocturno registradas.')],
    saber=['Las cuatro máquinas que no tienen sustituto a media noche: planta, pavimentadora, enfriadora y máquina de textura y curado; sus refacciones críticas salen del manual de cada una.',
           'Refacciones típicas críticas: bandas, mangueras hidráulicas, sensores del control 3D, vibradores, bombas, filtros.',
           'Membrana de curado a doble dosis: el consumo por noche se calcula sobre 8,400 m² de losa por kilómetro de dos carriles (más hombro).',
           'Acero en sillas: la cuadrilla de acero trabaja dos días adelante; las sillas y amarres tienen que estar antes que ellos.',
           'EPP para todos: casco, chaleco clase 3, botas con casquillo, lentes, guantes, tapones.',
           'Mínimo = consumo diario × días de entrega del proveedor + reserva.'],
    numeros=[('4', 'máquinas críticas con refacciones en sitio'), ('2 a. m.', 'la hora en que no puede faltar nada'),
             ('< 1 %', 'diferencia máxima en conteos'), ('2 días', 'lo que va el acero adelante: sus insumos van antes')],
    errores=['Dejar que una refacción crítica se acabe sin pedirla.', 'Entregar sin vale "porque es urgente".',
             'Guardar sin etiqueta o en otro lugar.', 'No revisar el material que llega.'],
    capacitacion=[('Días 2 a 5', 'Con el jefe de mantenimiento: la lista de refacciones críticas de cada máquina y dónde va cada una.'),
                  ('Semana 2', 'Sistema de inventario, vales y protocolo de acceso nocturno con el Gerente de logística.'),
                  ('Tramo de prueba', 'Surte el colado de prueba y ajusta mínimos con el consumo real.'),
                  ('Mes 3', 'Revisión de conteos y paros por refacción con el Gerente de logística.')],
    certificaciones=['Control de inventarios y almacenes.', 'NOM-006-STPS: manejo y almacenamiento de materiales.', 'Manejo seguro de sustancias (membrana, aditivos, lubricantes).'],
    comprobacion=['¿Cuáles son las cuatro máquinas críticas?', '¿Cómo calculas el mínimo de un artículo?',
                  '¿Qué pasa si el mecánico necesita algo a las 2 a. m.?', '¿Por qué los insumos del acero van antes que la cuadrilla?'],
    siguiente='Jefe de almacén de varios frentes o comprador de la gerencia de logística.',
)
