# -*- coding: utf-8 -*-
# RLR · Perfiles de los frentes de día (terracería, drenaje y base) — Ricardo López Reyero
P = {}

# ─────────────────────────── Frente 1 · Terracería ───────────────────────────

P['Cabo de frente'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='frente',
    mision='Entregar cada día 1 km de subrasante pareja, compactada al 95 % Proctor modificado en sus 30 cm superiores y verificada punto por punto, sin gastar el colchón de 3 días.',
    importa='La terracería es la capa que se hace primero y la que casi nadie revisa. Una bolsa blanda que este cabo deja pasar hoy es la grieta transversal que aparece "sin razón" en el año 6, y ya no hay forma de llegar a ella sin romper la losa.',
    responde=['El avance diario de su frente y los días de colchón sobre el drenaje, medidos cada tarde.',
              'La uniformidad de la subrasante: que no quede ninguna bolsa blanda, aunque el promedio del laboratorio salga bien.',
              'Que el sulfato se mida antes de meter cal, y que la cal entre a la dosis y profundidad que fija el laboratorio.',
              'La humedad de compactación: que las pipas rieguen parejo y a tiempo, no cuando ya se secó la capa.',
              'Las seis máquinas, sus seis operadores, sus seis ayudantes y sus dos regadores: bitácora, orden y seguridad.',
              'Entregar al cabo de drenaje un tramo liberado por el laboratorio y por topografía, no "casi listo".'],
    autoridad=['Detener una máquina o un tramo cuando ve una bolsa blanda, lodo, piedra grande o capa demasiado gruesa.',
               'Pedir al laboratorio una prueba adicional en cualquier punto que le dé mala espina, sin justificarlo.',
               'Mover gente y máquinas dentro de su frente para sostener el colchón.',
               'No le toca: liberar un tramo sin la firma del laboratorio, ni meter cal sin el resultado de sulfatos.'],
    experiencia=['5 años o más en terracerías de carretera o autopista, al menos 2 como cabo o sobrestante de una cuadrilla con motoconformadora, compactadores y pipas.',
                 'Haber trabajado con control de compactación por laboratorio (densidades en campo) y saber leer un reporte de Proctor.',
                 'Haber estabilizado suelos con cal o cemento, o haber sustituido material arcilloso en al menos una obra.',
                 'Deseable: haber trabajado con motoconformadora con control 3D o GPS, sin estacas.'],
    escolaridad=['Secundaria terminada como mínimo; bachillerato técnico en construcción deseable.',
                 'Leer planos de secciones y perfiles, hacer cuentas de volumen y porcentaje, y llenar la bitácora en tableta.'],
    persona=['Camina el tramo completo cada día; no manda desde la camioneta.',
             'Pisa la subrasante, la ve moverse bajo la llanta de un camión cargado y detiene ahí mismo.',
             'Explica el porqué a su gente: "parejo" le importa más que "duro".',
             'Pide el laboratorio antes de que se lo pidan; no le molesta que le rechacen un tramo.',
             'Llega antes que su cuadrilla y se va después de revisar la última capa.'],
    alertas=['Presume que "a ojo" sabe cuándo ya quedó compactado.',
             'Dice que la arcilla "se arregla con más rodillo".',
             'No sabe qué es el sulfato ni por qué se mide antes de la cal.',
             'Habla de metros por día y nunca de humedad, capas o bolsas blandas.'],
    preguntas=[('El laboratorio dice que el tramo promedia 97 %, pero en un punto salió 91 %. ¿Qué haces?', 'Que no libera el tramo: abre el punto, busca la causa (humedad, material, espesor) y lo corrige; el promedio no manda, manda el peor punto.'),
               ('Encuentras arcilla que se pega a la bota y se agrieta al secarse. ¿Qué pides antes de meter cal?', 'Índice plástico y sulfatos; si el sulfato pasa de 0.1 %, no se mete cal hasta que Calidad decida el tratamiento.'),
               ('Vas un día arriba del drenaje y el superintendente te pide adelantarte dos más. ¿Qué respondes?', 'Que mantiene el colchón pero no lo infla: la subrasante expuesta días de más se moja, se seca y se echa a perder.'),
               ('Una pipa falla a media mañana en pleno verano. ¿Cómo reorganizas?', 'Baja el tramo que se compacta ese día, prioriza la humedad de lo ya tendido, pide pipa de reemplazo; no compacta seco "para no parar".')],
    prueba='Medio día en campo, en un tramo de 200 m preparado: debe revisar el tramo caminándolo, marcar con pintura los puntos donde pediría densidad, detectar al menos dos defectos sembrados (una zona húmeda de más y una capa suelta demasiado gruesa), organizar a una cuadrilla de prueba para corregirlos y explicar al final qué liberaría y qué no. Aprueba si encuentra los defectos, no libera nada sin laboratorio y su cuadrilla trabaja segura.',
    indicadores=['Metros de subrasante liberados contra 1,000 m diarios.', 'Días de colchón sobre el drenaje, siempre ≥ 3.',
                 'Cero puntos bajo 95 % Proctor modificado en lo liberado.', 'Tramos rechazados por laboratorio o topografía y su causa.', 'Cero accidentes con tiempo perdido en su cuadrilla.'],
    dia=[('06:00', 'Junta de cierre: das los días de colchón de tu frente y lo que te puede frenar hoy.'),
         ('06:30', 'Plática de seguridad de 5 minutos con toda tu cuadrilla y revisión de máquinas antes de encender.'),
         ('07:00–13:00', 'Tendido, riego y compactación por capas; caminas el tramo y pides densidades donde dudas.'),
         ('13:00–16:30', 'Correcciones, perfilado final con la motoconformadora y recorrido con topografía y laboratorio.'),
         ('17:00', 'Entregas el tramo liberado al cabo de drenaje y cierras la bitácora con metros, pruebas y colchón.')],
    saber=['La subrasante son los 30 cm superiores del terreno, compactados al 95 % Proctor modificado, verificados punto por punto. El enemigo no es el suelo débil: es el suelo desigual.',
           'Capas sueltas de 20 a 25 cm; nunca compactes una capa más gruesa "para avanzar", porque el rodillo aprieta arriba y abajo queda flojo.',
           'Humedad de compactación dentro de ±2 % de la óptima del Proctor. Seca no compacta; mojada hace colchón y bombea.',
           'Arcilla expansiva (índice plástico mayor a 20): se estabiliza con cal al 3–5 % en 30 cm o se sustituye. Antes de la cal, sulfatos: arriba de 0.1 % la cal forma un mineral que levanta el pavimento años después.',
           'Motoconformadora con control 3D: la rasante viene del modelo digital, no de estacas; tolerancia de ±1.5 cm y bombeo transversal del 2 %, sin zonas planas donde el agua se quede.',
           'La subrasante se hace más ancha que lo que va encima: sobresale unos 60 cm por lado de la losa, para que las orillas también queden apoyadas.',
           'Una bolsa blanda se abre, se saca el material malo y se rellena compactando por capas; nunca se "tapa" con más rodillo ni con material encima.',
           'Prueba de rodillo cargado: un camión de volteo lleno que pasa despacio y no deja huella ni hace ondular el suelo. Lo que se mueve, se corrige.'],
    numeros=[('30 cm', 'profundidad de la subrasante compactada'), ('95 %', 'Proctor modificado, en cada punto, no en promedio'),
             ('IP > 20', 'arcilla expansiva: cal al 3–5 % o sustitución'), ('0.1 %', 'sulfatos: arriba de esto no entra cal sin decisión de Calidad'),
             ('2 %', 'bombeo transversal de la subrasante'), ('3 días', 'colchón mínimo sobre el drenaje')],
    errores=['Liberar un tramo por el promedio del laboratorio sin ver el peor punto.',
             'Meter cal sin haber medido sulfatos.',
             'Compactar seco en verano "porque la pipa no llegó".',
             'Tapar una bolsa blanda con material nuevo en lugar de sacarla.',
             'Adelantarse días de más: la subrasante expuesta se moja, se agrieta y hay que rehacerla.'],
    capacitacion=[('Días 2 a 5', 'Recorre los primeros 20 km liberados con el topógrafo y el jefe de laboratorio; aprende el modelo 3D del corredor y los resultados de sulfatos e índice plástico por tramo.'),
                  ('Semana 2', 'Trabaja lado a lado con el laboratorista de terracerías: Proctor, densidades en campo, humedad y cómo se lee cada reporte.'),
                  ('Tramo de prueba', 'Construye la subrasante de los 500 m del tramo de prueba con toda su cuadrilla; es su ensayo general y su examen.'),
                  ('Mes 2 a 3', 'Revisión semanal con el superintendente de su colchón, tramos rechazados y accidentes; curso de supervisión de cuadrillas.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción) y NOM-004-STPS (seguridad en maquinaria), con constancia DC-3.',
                     'Manejo seguro de cal y estabilizantes (NOM-010-STPS agentes químicos y hojas de datos de seguridad).',
                     'Primeros auxilios y respuesta a golpe de calor.',
                     'Curso interno de control de compactación con el laboratorio del proyecto.'],
    comprobacion=['¿Qué manda para liberar un tramo: el promedio o el peor punto? ¿Por qué?',
                  '¿Qué tienes que medir antes de meter cal, y cuál es el límite?',
                  '¿Qué haces con una bolsa blanda?',
                  '¿Por qué no conviene adelantarte días de más sobre el drenaje?'],
    siguiente='Cabo de colado (el tren) o, con dos años de colchón sano y cero rechazos, apoyo al superintendente en varios frentes.',
    pedimos=['Caminar el tramo completo todos los días antes de liberarlo.'],
)

P['Operador de maquinaria'] = dict(
    linea='Producción', reporta='Cabo de frente', esquema='frente',
    mision='Operar la motoconformadora, el compactador, la excavadora o el cargador del frente de terracería para dejar una subrasante pareja, a rasante y compactada por igual en cada metro.',
    importa='En este frente la uniformidad depende de las manos del operador: una pasada de menos en una orilla o una capa más gruesa en un tramo es exactamente la bolsa blanda que parte la losa años después.',
    responde=['Operar su máquina según el plan del cabo: capas, número de pasadas, velocidad y traslapes.',
              'La rasante que dicta el control 3D (motoconformadora) o la compactación pareja de orilla a orilla (compactador).',
              'La revisión diaria de su máquina antes de encender: niveles, fugas, llantas o rodillo, luces, alarma de reversa.',
              'La bitácora de horas y fallas, para que el mantenimiento se haga antes de que se rompa.',
              'Avisar de inmediato cualquier suelo que "se mueve", se pega o bombea bajo la máquina.'],
    autoridad=['Detener su máquina si ve a alguien en su zona ciega o si el suelo no está en condiciones.',
               'Negarse a operar una máquina con una falla de frenos, dirección, alarma o cinturón.',
               'Pedir al cabo que llame al laboratorio cuando algo no le cuadra.',
               'No le toca: cambiar el modelo 3D, las pasadas o el espesor de capa por su cuenta.'],
    experiencia=['3 años o más operando en terracerías de carretera al menos una de estas: motoconformadora (ideal con control 3D o GPS), compactador vibratorio liso de 12 t, compactador pata de cabra, excavadora de 20 t o cargador frontal.',
                 'Haber trabajado con laboratorio de compactación en campo y conocer lo que es una capa rechazada.',
                 'Para motoconformadora: haber perfilado subrasante o base con tolerancia de centímetros.'],
    escolaridad=['Primaria terminada como mínimo, secundaria deseable; saber leer y escribir.',
                 'Constancia de habilidades (DC-3) de la máquina que opera o disposición a certificarse en el primer mes.'],
    persona=['Revisa su máquina todos los días aunque nadie lo vea.',
             'Mantiene la misma velocidad y el mismo patrón de pasadas toda la jornada, sin prisas al final del día.',
             'Busca con la mirada al ayudante antes de moverse y respeta sus señales.',
             'Dice "esto no quedó" cuando algo no quedó, aunque ya sean las 4 de la tarde.'],
    alertas=['Dice que "le da unas pasadas más y ya" a cualquier problema.',
             'No sabe qué revisar en su máquina antes de encenderla.',
             'Presume de lo rápido que trabaja, nunca de lo parejo.',
             'Ha tenido accidentes en reversa y los cuenta como mala suerte.'],
    preguntas=[('Vas compactando y en un tramo el suelo ondula detrás del rodillo. ¿Qué haces?', 'Que se detiene y avisa al cabo: es humedad de más o material malo; seguir pasando lo empeora.'),
               ('¿Cómo compactas una orilla?', 'Traslapando al menos 15–20 cm cada pasada y llegando hasta la orilla; la orilla sin compactar es la bolsa blanda.'),
               ('El control 3D de la motoconformadora pierde señal. ¿Qué haces?', 'Se detiene, avisa a topografía y no sigue "a ojo"; lo que perfila sin modelo se tiene que rehacer.'),
               ('¿Qué revisas antes de encender?', 'Aceite, refrigerante, hidráulico, fugas, llantas o rodillo, frenos, luces, alarma de reversa y cinturón.')],
    prueba='Dos horas en la máquina que solicita, en un tramo de prueba: motoconformadora, perfilar 100 m a rasante con el control 3D (aprueba con ±1.5 cm en los puntos que mide topografía); compactador, compactar una capa de 100 m con el patrón indicado (aprueba si el laboratorio no encuentra puntos bajo 95 %); excavadora o cargador, cargar volteos sin golpear la caja y sin derramar. En todos los casos se evalúa la revisión previa de la máquina y la operación segura con un ayudante cerca.',
    indicadores=['Tramos rechazados por laboratorio o topografía atribuibles a su máquina: cero.', 'Horas de paro de su máquina por falla evitable.',
                 'Bitácora de revisión diaria completa.', 'Cero incidentes con personas o con otras máquinas.'],
    dia=[('06:30', 'Plática de seguridad y revisión de tu máquina antes de encender; anota en la bitácora.'),
         ('07:00–13:00', 'Operas según el plan del cabo: capas, pasadas y velocidad parejas.'),
         ('13:00', 'Comida a la sombra; tu máquina queda apagada y estacionada fuera del paso.'),
         ('13:30–16:30', 'Correcciones que marquen laboratorio y topografía; perfilado o compactación final.'),
         ('16:30–17:00', 'Limpias la máquina, reportas fallas al taller y dejas la bitácora con horas.')],
    saber=['La subrasante son 30 cm compactados al 95 % Proctor modificado, parejos en cada punto. Una pasada de menos en una orilla es una bolsa blanda.',
           'Capas sueltas de 20 a 25 cm; si te tienden más gruesa, avisa antes de compactar.',
           'Compactador liso de 12 t: velocidad baja y constante, traslape de 15–20 cm, siempre el mismo número de pasadas en todo el ancho. Pata de cabra para arcilla; liso para cerrar la superficie.',
           'Motoconformadora con control 3D: el modelo digital manda la altura; tu trabajo es mantener la cuchilla estable, sin brincos ni cambios de velocidad. Bombeo del 2 %, sin zonas planas.',
           'Si el suelo ondula, se pega al rodillo o brota agua, no sigas: es humedad de más o material malo.',
           'Nunca muevas ni pises con la máquina una estaca de control o un punto de topografía.',
           'Reversa: sólo con alarma sonando y con el ayudante a la vista. Si no lo ves, te detienes.'],
    numeros=[('30 cm', 'espesor de subrasante compactada'), ('95 %', 'Proctor modificado en cada punto'), ('20–25 cm', 'capa suelta máxima antes de compactar'),
             ('±1.5 cm', 'tolerancia de rasante con control 3D'), ('15–20 cm', 'traslape entre pasadas del compactador')],
    errores=['Compactar una capa demasiado gruesa "para avanzar".', 'Dejar las orillas sin compactar.', 'Perfilar a ojo cuando falla el control 3D.',
             'Encender sin revisar la máquina y romperla a media mañana.'],
    capacitacion=[('Días 2 a 5', 'Opera acompañado de un operador con experiencia del proyecto; aprende el patrón de pasadas, la bitácora y las señales con los ayudantes.'),
                  ('Semana 2', 'Motoconformadoras: curso del control 3D con el topógrafo. Compactadores: cómo se mide la densidad y cómo leer un rechazo del laboratorio.'),
                  ('Tramo de prueba', 'Opera en los 500 m del tramo de prueba; ahí se calibra cuántas pasadas necesita cada suelo.'),
                  ('Mes 2 a 3', 'Evaluación de su bitácora y tramos rechazados; certificación DC-3 de su máquina si no la tenía.')],
    certificaciones=['Constancia DC-3 de habilidades en la máquina que opera (motoconformadora, compactador, excavadora o cargador).',
                     'NOM-004-STPS (seguridad en maquinaria) y NOM-031-STPS (seguridad en construcción).',
                     'Operación de control de máquina 3D GNSS, para los operadores de motoconformadora.'],
    comprobacion=['¿Cuánto traslapas entre pasadas del compactador y por qué importan las orillas?',
                  '¿Qué haces si el suelo ondula detrás del rodillo?',
                  '¿Qué haces si pierdes la señal del control 3D?',
                  '¿Qué tienes que ver antes de dar reversa?'],
    siguiente='Operador de la extendedora o de los rodillos del frente de base, o cabo de frente con dos años de bitácora limpia.',
)

P['Ayudante general'] = dict(
    linea='Producción', reporta='Cabo de frente', esquema='frente',
    mision='Ser los ojos del operador en el piso: guiar a las máquinas con seguridad, limpiar la capa de piedras y basura, y avisar de cualquier suelo que se mueva, bombee o se vea distinto.',
    importa='El ayudante es el que está a pie sobre la subrasante: ve primero la bolsa blanda, la piedra grande o la estaca pisada. Y es quien evita el accidente más común de una terracería: la persona atropellada por una máquina en reversa.',
    responde=['Guiar a su operador con señales claras en maniobras, reversa y carga de volteos.',
              'Retirar piedras grandes, raíces, basura y material orgánico de la capa antes de compactar.',
              'Cuidar las estacas y los puntos de control de topografía; avisar si alguno se movió.',
              'Apoyar al laboratorio y al topógrafo: marcar puntos, cargar equipo, abrir calas.',
              'Colocar y retirar conos y señales del frente, y mantener limpia el área de trabajo.'],
    autoridad=['Detener cualquier máquina con la señal de alto si ve a alguien en peligro.',
               'Avisar al cabo de cualquier suelo que ondule, bombee o se vea distinto, sin esperar permiso.',
               'Negarse a entrar a la zona de una máquina si el operador no lo ha visto.',
               'No le toca: operar una máquina sin estar certificado, ni mover una estaca de topografía.'],
    experiencia=['1 año o más como ayudante o peón en obra de terracería, carretera o construcción pesada, trabajando junto a maquinaria.',
                 'Conocer las señales de mano para guiar máquinas y camiones.',
                 'No es indispensable experiencia previa si tiene buena condición física y ganas de aprender el oficio.'],
    escolaridad=['Saber leer y escribir; primaria terminada deseable.'],
    persona=['Siempre está donde el operador lo puede ver.',
             'Se agacha a recoger la piedra aunque nadie le haya dicho.',
             'Pregunta cuando no entiende en lugar de adivinar.',
             'Llega puntual, con su equipo completo y con agua.',
             'Avisa lo que ve, aunque le parezca poca cosa.'],
    alertas=['Dice que "ya sabe" cómo cuidarse de las máquinas y no usa chaleco.',
             'Ha tenido varios trabajos cortos sin razón clara.',
             'Le parece exagerado revisar la capa a pie.'],
    preguntas=[('Un volteo va a dar reversa y tú estás detrás. ¿Qué haces?', 'Que se quita de la línea de la reversa, se pone donde el chofer lo vea y le da la señal; nunca camina detrás.'),
               ('Ves que el suelo se hunde y sale agua cuando pasa un camión. ¿Qué haces?', 'Avisar de inmediato al cabo y marcar el lugar.'),
               ('Encuentras una estaca de topografía tirada. ¿La vuelves a poner?', 'No: avisa al cabo y al topógrafo, porque ya no está en su lugar exacto.')],
    prueba='Una jornada de prueba en el frente, acompañado: debe dar las señales de mano correctas para guiar un volteo en reversa y a una motoconformadora, limpiar 50 m de capa de piedras y basura, y reconocer una zona húmeda sembrada. Aprueba si nunca se pone en la zona ciega de una máquina, entiende y da las señales, y avisa lo que ve.',
    indicadores=['Asistencia y puntualidad.', 'Cero incidentes con máquinas en su zona.', 'Capas rechazadas por basura o piedra: cero.', 'Avisos de campo al cabo que resultaron en correcciones.'],
    dia=[('06:30', 'Plática de seguridad; revisas tu equipo: casco, chaleco, botas, lentes, guantes y agua.'),
         ('07:00–13:00', 'Guías a tu operador, limpias la capa, cuidas estacas y apoyas al laboratorio.'),
         ('13:00', 'Comida y descanso a la sombra.'),
         ('13:30–16:30', 'Correcciones, calas y marcas; ayudas a colocar la señalización del día siguiente.'),
         ('16:30–17:00', 'Limpieza del área, retiro de herramienta y reporte al cabo de lo que viste.')],
    saber=['La subrasante son los 30 cm de suelo donde se va a apoyar toda la carretera. Tiene que quedar pareja: una piedra grande, una raíz o un hoyo tapado con basura es un punto débil que dura 50 años.',
           'Saca de la capa cualquier piedra más grande que tu puño, raíces, plásticos y tierra negra con hierbas.',
           'Las señales de mano: alto (palma al frente), avanzar, reversa, girar y bajar la cuchilla. Siempre donde el operador te vea; si no te ve, no te acercas.',
           'Nunca camines detrás de una máquina en reversa ni entre dos máquinas. Antes de acercarte, busca los ojos del operador y espera su señal.',
           'Si ves que el suelo se hunde, se mueve como gelatina o sale agua al pasar un camión, avisa y marca el lugar con pintura o una estaca.',
           'Una estaca o punto de topografía movido ya no sirve: no lo vuelvas a poner, avisa.',
           'La cal quema la piel y los ojos: si hay estabilización, lentes cerrados, guantes, manga larga y cubrebocas, y nunca te pongas del lado del viento.'],
    numeros=[('30 cm', 'la capa de suelo que se compacta y que tú revisas'), ('1 puño', 'piedra más grande que eso, se saca'),
             ('1 km', 'lo que avanza tu frente cada día'), ('2 litros', 'agua mínima que traes a la mano en la mañana, y se rellena')],
    errores=['Caminar detrás de una máquina en reversa.', 'Dejar piedras o basura en la capa porque "el rodillo la entierra".',
             'Volver a clavar una estaca que se cayó.', 'Callarte algo que viste raro en el suelo.'],
    capacitacion=[('Días 2 a 5', 'Acompaña a un ayudante con experiencia; aprende las señales de mano y la zona ciega de cada máquina del frente.'),
                  ('Semana 2', 'Apoya al laboratorio y a topografía: cómo se toma una densidad, qué es un punto de control y por qué no se toca.'),
                  ('Tramo de prueba', 'Trabaja en los 500 m del tramo de prueba y toma el curso de seguridad y calidad del proyecto.'),
                  ('Mes 3 a 6', 'Si quiere crecer, empieza a practicar en una máquina con un operador certificado, en horas controladas.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción): curso básico con constancia DC-3.',
                     'Señales de mano para maniobras de maquinaria (NOM-004-STPS).',
                     'Uso de equipo de protección personal (NOM-017-STPS) y manejo seguro de cal.'],
    comprobacion=['¿Dónde te pones cuando una máquina da reversa?',
                  '¿Qué sacas de la capa antes de compactar?',
                  '¿Qué haces si ves que el suelo se hunde o sale agua?',
                  '¿Qué haces con una estaca de topografía que se cayó?'],
    siguiente='Operador de maquinaria: seis meses sin faltas, el curso de seguridad y calidad del tramo de prueba y la certificación de la máquina.',
)

P['Regador · control de humedad'] = dict(
    linea='Producción', reporta='Cabo de frente', esquema='frente',
    mision='Llevar el agua exacta a cada capa de suelo con la pipa de 10,000 L, para que se compacte en su humedad óptima, pareja de orilla a orilla y a la hora en que se necesita.',
    importa='Con el suelo seco, el rodillo pasa y no compacta; con agua de más, la capa se vuelve lodo y bombea. La humedad es la mitad de la compactación, y en el calor del norte se pierde en una hora.',
    responde=['El riego de cada capa con la cantidad que indica el cabo según la prueba de humedad del laboratorio.',
              'Un riego parejo: sin charcos, sin franjas secas, llegando a las orillas.',
              'Tener la pipa llena y lista antes de que la capa la necesite, calculando los viajes a la toma de agua.',
              'El riego de los caminos de acarreo y accesos para controlar el polvo hacia la gente y las comunidades.',
              'La revisión diaria de su pipa: bomba, barra de riego, válvulas, frenos, llantas y luces.'],
    autoridad=['Pedir al cabo que el laboratorio mida la humedad si ve la capa demasiado seca o mojada.',
               'Negarse a manejar la pipa con frenos, dirección o luces fallando.',
               'No le toca: decidir cuánta agua lleva una capa sin la indicación del cabo o del laboratorio.'],
    experiencia=['2 años o más manejando pipa de agua, camión de volteo o camión de carga en obra o en carretera, idealmente regando capas de terracería.',
                 'Saber regular la bomba y la barra de riego para dar un riego parejo a velocidad constante.',
                 'Licencia de manejo de carga vigente, sin infracciones graves.'],
    escolaridad=['Primaria terminada, secundaria deseable; saber leer, escribir y hacer cuentas sencillas de litros y viajes.',
                 'Licencia de chofer de carga estatal vigente; licencia federal tipo C si la pipa circula por carretera federal abierta.'],
    persona=['Maneja despacio y parejo; no tiene prisa.',
             'Mira la capa después de regar y regresa a la franja que quedó seca.',
             'Calcula sus viajes para no dejar al compactador esperando.',
             'Cuida su pipa como si fuera suya.'],
    alertas=['Dice que "entre más agua mejor, así compacta más rápido".',
             'Tiene licencia vencida o varias infracciones por exceso de velocidad.',
             'No sabe regular la bomba ni la barra de riego.'],
    preguntas=[('El laboratorio dice que la capa está 3 % abajo de la humedad óptima. ¿Qué haces?', 'Riega en pasadas parejas lo que indique el cabo, espera a que el agua se reparta y pide medir de nuevo; no echa todo de una vez.'),
               ('Ves que tu riego dejó charcos. ¿Qué pasa si se compacta así?', 'Se forma lodo y bolsa blanda; hay que dejar orear o escarificar antes de compactar.'),
               ('Son las 2 de la tarde, 40 °C, y la capa se seca muy rápido. ¿Cómo lo manejas?', 'Riego más seguido y en menos cantidad, coordinado para que el compactador entre justo detrás.')],
    prueba='Una jornada con la pipa del proyecto: revisión completa antes de salir, llenado en la toma, y riego de una capa de 200 m a la humedad que indique el laboratorio. Aprueba si el riego queda parejo (sin charcos ni franjas secas), la humedad medida después queda dentro de ±2 % de la óptima y maneja con seguridad dentro del frente.',
    indicadores=['Capas con humedad dentro de ±2 % de la óptima al compactar.', 'Minutos que el compactador esperó agua: cero.',
                 'Revisión diaria de la pipa en bitácora.', 'Cero incidentes de manejo.'],
    dia=[('06:30', 'Plática de seguridad, revisión de la pipa y llenado para estar listo a las 07:00.'),
         ('07:00–13:00', 'Riegas las capas que el cabo marca, delante del compactador; entre viajes, riegas caminos de acarreo.'),
         ('13:00', 'Comida; la pipa queda llena para la tarde.'),
         ('13:30–16:30', 'Riego de mantenimiento de lo tendido y de los accesos; el calor de la tarde seca más rápido.'),
         ('16:30–17:00', 'Lavas y revisas la pipa, reportas fallas y anotas viajes y litros.')],
    saber=['La humedad óptima sale del laboratorio (prueba Proctor). El suelo se compacta bien sólo dentro de ±2 % de esa humedad.',
           'Tu pipa carga 10,000 L. Riega a velocidad constante, con la barra abierta parejo; si aceleras, dejas franjas secas, y si frenas, charcos.',
           'Riega en varias pasadas cortas, no en una sola de golpe: el agua tiene que repartirse en la capa antes de compactar.',
           'Si ves charcos o el suelo se pega a la llanta, ya te pasaste: avisa al cabo para que se deje orear.',
           'En el calor se pierde humedad en menos de una hora: el riego va justo delante del compactador, no una hora antes.',
           'El agua de riego tiene que ser limpia, sin aceite ni basura; la toma la indica el cabo.',
           'Dentro del frente máximo 20 km/h; nunca des reversa sin ayudante a la vista.'],
    numeros=[('10,000 L', 'capacidad de tu pipa'), ('±2 %', 'humedad aceptable respecto a la óptima'),
             ('30 cm', 'profundidad que se compacta: el agua tiene que llegar pareja'), ('20 km/h', 'velocidad máxima dentro del frente')],
    errores=['Regar mucho de una vez y hacer lodo.', 'Regar una hora antes y que el sol se lleve el agua.', 'Dejar las orillas secas.', 'Manejar la pipa sin revisar frenos.'],
    capacitacion=[('Días 2 a 5', 'Acompaña al otro regador y al laboratorista: cómo se mide la humedad y qué significa "óptima".'),
                  ('Semana 2', 'Calibra su pipa: cuántos litros por metro cuadrado da a cada velocidad y apertura de barra.'),
                  ('Tramo de prueba', 'Riega en los 500 m del tramo de prueba y toma el curso de seguridad y calidad.'),
                  ('Mes 2 a 3', 'Revisión con el cabo de las capas rechazadas por humedad; manejo defensivo.')],
    certificaciones=['Licencia de chofer de carga vigente (federal tipo C si circula por carretera federal).',
                     'Manejo defensivo de vehículos pesados.',
                     'NOM-031-STPS (seguridad en construcción) con constancia DC-3.'],
    comprobacion=['¿Cuánto se puede alejar la humedad de la óptima?',
                  '¿Qué pasa si riegas de más?',
                  '¿Por qué riegas justo delante del compactador y no antes?',
                  '¿A qué velocidad máxima manejas dentro del frente?'],
    siguiente='Operador de maquinaria (compactador o cargador) con la certificación de la máquina, o chofer del camión de combustible.',
)

# ─────────────────────────── Frente 2 · Drenaje ───────────────────────────

P['Cabo de drenaje'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='frente',
    mision='Construir cada día 1 km de dren de borde que funcione y se pueda revisar: tubo perforado de 10 cm con su pendiente, geotextil bien traslapado, salidas cada 60–100 m con cabezal visible y registro de limpieza.',
    importa='El agua atrapada es la enfermedad número 1 y la causa de la mayoría de los pavimentos destruidos del país. Este frente parece el menos glamoroso y es el que decide si la carretera llega a 50 años: un dren tapado se ve igual que uno que funciona.',
    responde=['El avance diario del dren de borde y los días de colchón sobre la base, medidos cada tarde.',
              'La pendiente del tubo, que el agua corra siempre hacia la salida, sin columpios.',
              'Que cada salida tenga su cabezal visible, su registro y su ubicación en el plano as-built.',
              'Que el geotextil envuelva la subbase drenante y la zanja sin rasgaduras ni contaminación de tierra.',
              'Que ninguna zanja quede abierta de más: el drenaje abierto semanas se azolva.',
              'La seguridad de su cuadrilla en zanjas y junto a la retroexcavadora.'],
    autoridad=['Detener el relleno de un tramo si el tubo quedó sin pendiente, aplastado o con el geotextil roto.',
               'Pedir a topografía la verificación de pendiente de cualquier tramo antes de tapar.',
               'Parar la excavación si aparece un ducto, cable o línea no marcada, hasta que Liberaciones lo resuelva.',
               'No le toca: tapar un dren sin la verificación de pendiente, ni cambiar la separación de salidas.'],
    experiencia=['5 años o más en obras de drenaje (subdrenes, alcantarillas, tubería o drenaje pluvial) en carreteras o urbanización, al menos 2 como cabo.',
                 'Haber instalado tubería con pendiente controlada por topografía y geotextil en zanja.',
                 'Haber trabajado junto a ductos, líneas o servicios enterrados, con protocolo de localización antes de excavar.'],
    escolaridad=['Secundaria terminada como mínimo; bachillerato técnico deseable.',
                 'Leer planos de perfil y de salidas, calcular pendientes en porcentaje y llenar la bitácora en tableta.'],
    persona=['Revisa la pendiente con topografía antes de dejar tapar, cada tramo.',
             'Se mete a la zanja a ver el tubo y el geotextil con sus propios ojos.',
             'Piensa en el año 20: quiere que alguien pueda encontrar y limpiar cada salida.',
             'Mantiene su frente ordenado: zanja abierta hoy, tapada hoy.'],
    alertas=['Dice que el dren "es lo de menos, lo importante es la losa".',
             'Ha tapado tubo sin verificar pendiente "porque se veía bien".',
             'No sabe qué es un traslape de geotextil ni por qué importa.',
             'Excava sin preguntar por ductos o líneas.'],
    preguntas=[('Topografía te dice que en 40 m el tubo quedó con 1 cm de columpio. Ya está relleno la mitad. ¿Qué haces?', 'Destapa y corrige: un columpio junta agua y sedimento y tapa el dren en pocos años.'),
               ('Vas 6 días arriba de la base y te piden adelantarte más. ¿Qué dices?', 'Que el colchón ya está sano; abrir drenaje semanas antes lo azolva y lo contamina.'),
               ('¿Para qué sirve el cabezal y el registro en cada salida?', 'Para que el dren se pueda ver, inspeccionar y limpiar en el año 20; un dren que no se puede revisar es un dren que no existe.'),
               ('La retro topa con un tubo que no está en el plano. ¿Qué haces?', 'Para, aísla la zona, avisa al superintendente y a Liberaciones; no se sigue hasta saber qué es.')],
    prueba='Medio día en un tramo de 100 m con zanja abierta: debe revisar pendiente con el topógrafo, detectar tres defectos sembrados (un columpio, un traslape de geotextil corto y una salida sin pendiente), ordenar la corrección a la cuadrilla y explicar qué autoriza tapar. Aprueba si encuentra los tres defectos, no deja tapar nada sin verificación y la cuadrilla trabaja segura en la zanja.',
    indicadores=['Metros de dren terminados contra 1,000 m diarios.', 'Días de colchón sobre la base, siempre ≥ 3 y sin zanja abierta de más.',
                 'Tramos con pendiente verificada antes de tapar: 100 %.', 'Salidas con cabezal, registro y ubicación en as-built: 100 %.', 'Cero accidentes en zanja.'],
    dia=[('06:00', 'Junta de cierre: das los días de colchón de tu frente y lo que te puede frenar (ductos, liberaciones, lluvia).'),
         ('06:30', 'Plática de seguridad con énfasis en zanjas y maquinaria; revisas la ruta de la zanjadora con topografía.'),
         ('07:00–13:00', 'Zanja, tubo, geotextil y grava; te metes a la zanja a revisar cada tramo antes de tapar.'),
         ('13:30–16:30', 'Salidas, cabezales y registros; relleno compactado de lo verificado.'),
         ('17:00', 'Cierras: nada abierto sin protección, metros en bitácora, salidas ubicadas para el as-built.')],
    saber=['El dren de borde es un tubo perforado de 10 cm a lo largo del borde, con salidas cada 60–100 m, cabezal visible y registro de limpieza. Tiene que poder inspeccionarse y limpiarse en el año 20.',
           'La subbase drenante de 15–20 cm va envuelta en geotextil; la subbase y el geotextil sobresalen unos 35 cm por lado de lo que se cuela encima.',
           'El tubo sigue la pendiente del camino y nunca menos de 0.5 %; un columpio de un centímetro junta agua y sedimento y lo tapa. Las salidas bajan con pendiente fuerte (3 % o más) hasta la cuneta.',
           'Geotextil: traslapes de al menos 30 cm, sin rasgaduras, sin tierra encima, y no más de unos días al sol porque se degrada.',
           'La rasante de la losa debe quedar al menos 80 cm arriba del nivel más alto del agua subterránea, y el bombeo transversal es del 2 %: si ves agua freática alta o zonas planas, avisa.',
           'Relleno de zanja en capas de 15 cm con el compactador de zanja; los primeros centímetros sobre el tubo con cuidado para no aplastarlo.',
           'Antes de excavar, confirma con Liberaciones que no hay ductos ni líneas; una zanja de más de 1.5 m de profundidad necesita talud o ademe.',
           'Tu colchón: al menos 3 días sobre la base, pero sin abrir de más, porque la zanja abierta se azolva y la subbase expuesta se contamina.'],
    numeros=[('10 cm', 'diámetro del tubo perforado del dren de borde'), ('60–100 m', 'separación entre salidas, cada una con cabezal y registro'),
             ('≥ 0.5 %', 'pendiente mínima del tubo, sin columpios'), ('30 cm', 'traslape mínimo del geotextil'),
             ('80 cm', 'altura mínima de la rasante sobre el agua subterránea'), ('3 días', 'colchón mínimo sobre la base')],
    errores=['Tapar un tubo sin verificar la pendiente.', 'Dejar el geotextil con tierra, rasgado o sin traslape.',
             'Salidas sin cabezal ni registro: nadie las encontrará en el año 20.', 'Abrir zanja semanas antes y dejar que se azolve.',
             'Excavar sin confirmar ductos y líneas.'],
    capacitacion=[('Días 2 a 5', 'Recorre con el topógrafo los primeros 20 km: niveles, salidas, cunetas y zonas con agua freática alta; revisa con Liberaciones los cruces con ductos y líneas.'),
                  ('Semana 2', 'Con el jefe de laboratorio: cómo se revisa la graduación de la grava drenante y la calidad del geotextil y del tubo que llegan.'),
                  ('Tramo de prueba', 'Construye el drenaje de los 500 m del tramo de prueba con su cuadrilla, incluidas salidas y registros, y lo prueba con agua.'),
                  ('Mes 2 a 3', 'Revisión semanal con el superintendente de colchón, pendientes y as-built; curso de supervisión de cuadrillas y seguridad en excavaciones.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción), con énfasis en excavaciones y zanjas, constancia DC-3.',
                     'NOM-004-STPS (seguridad en maquinaria) y NOM-006-STPS (manejo de materiales).',
                     'Primeros auxilios y rescate básico en zanja.'],
    comprobacion=['¿Cada cuántos metros va una salida y qué lleva cada una?',
                  '¿Qué pasa si el tubo queda con un columpio de un centímetro?',
                  '¿Por qué no conviene adelantarte semanas sobre la base?',
                  '¿Qué haces si la retroexcavadora topa con un ducto que no está en el plano?'],
    siguiente='Cabo de base o, con dos años de colchón sano y as-built completo, apoyo al superintendente en varios frentes.',
    pedimos=['Meterte a la zanja a ver el tubo antes de autorizar que se tape.'],
)

P['Operador'] = dict(
    linea='Producción', reporta='Cabo de drenaje', esquema='frente',
    mision='Operar la retroexcavadora, la zanjadora continua o el compactador de zanja del frente de drenaje para abrir y cerrar la zanja del dren de borde con la profundidad, la pendiente y la compactación exactas.',
    importa='La zanja la hace la máquina: si el fondo queda con columpios, el tubo los copia; si el relleno queda flojo, se asienta y rompe el borde. Y esta máquina trabaja con gente adentro de la zanja, junto a ductos que no siempre están en el plano.',
    responde=['Abrir la zanja del dren de borde y de las salidas con la profundidad y pendiente del modelo o de las marcas de topografía.',
              'Colocar el material excavado donde no caiga de regreso a la zanja ni tape el paso.',
              'Rellenar y compactar por capas sin aplastar ni mover el tubo.',
              'La revisión diaria de su máquina y la bitácora de horas y fallas.',
              'La seguridad de la cuadrilla que trabaja en la zanja a un lado de su máquina.'],
    autoridad=['Detener la excavación si ve un ducto, cable, cinta de advertencia o cambio de suelo raro.',
               'Detener su máquina si alguien entra a su radio de giro o a la zanja sin avisar.',
               'Negarse a operar una máquina con fallas de frenos, hidráulico o alarma.',
               'No le toca: cambiar la profundidad o pendiente de la zanja por su cuenta, ni excavar fuera de lo liberado.'],
    experiencia=['3 años o más operando retroexcavadora en zanjas para tubería, drenaje o servicios, con pendiente controlada por topografía; o zanjadora continua o compactador de zanja en obra lineal.',
                 'Haber excavado junto a ductos, líneas eléctricas o servicios enterrados sin dañarlos.',
                 'Deseable: operar las tres máquinas del frente (retro, zanjadora y compactador de zanja).'],
    escolaridad=['Primaria terminada como mínimo, secundaria deseable; saber leer y escribir.',
                 'Constancia DC-3 de habilidades en retroexcavadora o en la máquina que opera, o disposición a certificarse en el primer mes.'],
    persona=['Excava despacio y parejo; revisa el fondo con el nivel o con el ayudante antes de avanzar.',
             'Siempre sabe dónde está cada persona de la cuadrilla.',
             'Se detiene al primer indicio de un ducto, sin esperar a romperlo.',
             'Cuida su máquina y reporta fallas antes de que se vuelvan paros.'],
    alertas=['Presume que "a ojo" saca la pendiente.',
             'Ha roto ductos o líneas y lo cuenta como algo normal.',
             'Opera con gente dentro de la zanja justo bajo el bote.'],
    preguntas=[('Vas excavando y aparece una cinta amarilla o roja en la tierra. ¿Qué haces?', 'Se detiene de inmediato: es aviso de un ducto o cable; avisa al cabo y no se sigue hasta que Liberaciones confirme.'),
               ('¿Cómo compactas el relleno de una zanja con tubo?', 'En capas de 15 cm, con cuidado los primeros centímetros sobre el tubo, sin golpearlo ni moverlo.'),
               ('¿Cómo sabes que el fondo de la zanja tiene la pendiente correcta?', 'Con las marcas o el control de topografía y revisando con el ayudante antes de colocar tubo; si hay duda, se verifica antes de avanzar.')],
    prueba='Dos horas en la máquina que solicita, en un tramo de prueba de 50 m: retroexcavadora o zanjadora, abrir la zanja a la profundidad y pendiente marcadas (aprueba si topografía no encuentra columpios mayores a 1 cm y el material queda bien acomodado); compactador de zanja, rellenar por capas sin mover el tubo (aprueba si el tubo sigue en su lugar y el relleno no se hunde al pisarlo). Se evalúa la revisión previa de la máquina y la atención a la gente dentro de la zanja.',
    indicadores=['Metros de zanja sin retrabajo por pendiente.', 'Ductos, líneas o tubos dañados: cero.',
                 'Horas de paro de su máquina por falla evitable.', 'Cero incidentes con personas en la zanja.'],
    dia=[('06:30', 'Plática de seguridad; revisas tu máquina y confirmas con el cabo el tramo liberado y las marcas de topografía.'),
         ('07:00–13:00', 'Excavas o rellenas según el plan; te detienes cada vez que alguien baja a la zanja.'),
         ('13:00', 'Comida; tu máquina queda apagada y fuera del paso, con el bote en el suelo.'),
         ('13:30–16:30', 'Salidas hacia la cuneta y relleno compactado de lo que el cabo ya verificó.'),
         ('16:30–17:00', 'Limpieza, revisión y bitácora; ninguna zanja queda abierta sin protección.')],
    saber=['El dren de borde es un tubo perforado de 10 cm; tu zanja le da la pendiente. El fondo sigue la pendiente del camino, nunca menos de 0.5 %, y sin columpios: un centímetro de columpio junta agua y tapa el dren.',
           'Las salidas bajan cada 60–100 m hacia la cuneta con pendiente fuerte (3 % o más); termínalas donde marque topografía para que el cabezal quede visible.',
           'Zanjadora continua: avance constante, sin frenazos, siguiendo la guía de altura; retroexcavadora: bote de ancho parejo y fondo limpio.',
           'El material excavado se deja al menos a 60 cm del borde de la zanja, para que no se caiga ni cargue la pared.',
           'Compactador de zanja: capas de 15 cm; los primeros centímetros sobre el tubo con cuidado, sin vibración fuerte encima.',
           'Una zanja de más de 1.5 m de profundidad necesita talud o ademe antes de que alguien baje.',
           'Cinta de advertencia, arena de colores, concreto enterrado o tubo que no está en el plano: te detienes y avisas.'],
    numeros=[('10 cm', 'diámetro del tubo que va en tu zanja'), ('≥ 0.5 %', 'pendiente mínima del fondo'), ('60–100 m', 'separación entre salidas'),
             ('15 cm', 'espesor de cada capa de relleno'), ('60 cm', 'distancia mínima del material excavado al borde de la zanja'), ('1.5 m', 'profundidad a partir de la cual la zanja necesita talud o ademe')],
    errores=['Excavar a ojo sin revisar la pendiente.', 'Seguir excavando después de ver una cinta de advertencia.',
             'Aplastar el tubo con el compactador.', 'Operar con alguien dentro de la zanja bajo el bote.'],
    capacitacion=[('Días 2 a 5', 'Opera acompañado del cabo y del topógrafo; aprende a leer las marcas de pendiente y las salidas del plano.'),
                  ('Semana 2', 'Protocolo de localización de ductos y líneas con Liberaciones; práctica en las tres máquinas del frente.'),
                  ('Tramo de prueba', 'Excava y rellena el drenaje de los 500 m del tramo de prueba, y ve la prueba con agua de lo que construyó.'),
                  ('Mes 2 a 3', 'Evaluación de su bitácora y retrabajos; certificación DC-3 de su máquina si no la tenía.')],
    certificaciones=['Constancia DC-3 de habilidades en retroexcavadora, zanjadora o compactador de zanja.',
                     'NOM-004-STPS (seguridad en maquinaria) y NOM-031-STPS (construcción, excavaciones y zanjas).',
                     'Excavación segura junto a servicios enterrados.'],
    comprobacion=['¿Cuál es la pendiente mínima del fondo y qué pasa con un columpio?',
                  '¿Qué haces si ves una cinta de advertencia en la tierra?',
                  '¿A qué distancia dejas el material excavado del borde?',
                  '¿En capas de cuánto se rellena la zanja?'],
    siguiente='Cabo de drenaje con dos años de bitácora limpia, o operador de un equipo mayor del frente de terracería o de base.',
)

P['Cuadrilla de tubo, geotextil y cabezales'] = dict(
    linea='Producción', reporta='Cabo de drenaje', esquema='frente',
    mision='Colocar a mano el geotextil, la grava drenante, el tubo perforado y los cabezales de salida del dren de borde, para que el agua salga de abajo de la carretera durante 50 años.',
    importa='Todo lo que esta cuadrilla hace queda enterrado el mismo día y nadie lo vuelve a ver: un geotextil roto, un tubo mal unido o una salida sin cabezal se ven igual que uno bien hecho, hasta que el agua se queda atrapada y la losa se rompe.',
    responde=['Tender el geotextil en la zanja y bajo la subbase, con sus traslapes y sin rasgaduras.',
              'Colocar el tubo perforado de 10 cm con sus uniones firmes y las perforaciones en la posición indicada.',
              'Colocar la grava drenante limpia alrededor del tubo y cerrar el geotextil encima.',
              'Construir cada salida con su tubo liso, su cabezal visible y su registro de limpieza.',
              'Cuidar el material: que el tubo y el geotextil no se ensucien, no se pisen y no se queden al sol.'],
    autoridad=['Avisar al cabo y detener la colocación si el tubo llega roto, el geotextil rasgado o la grava sucia.',
               'Salir de la zanja cuando la máquina se acerque o la pared se vea floja.',
               'No le toca: tapar un tramo sin que el cabo lo haya revisado.'],
    experiencia=['1 año o más como ayudante u oficial en obras de tubería, drenaje, alcantarillado o subdrenes.',
                 'Haber tendido geotextil o colocado tubo en zanja; deseable haber construido cabezales o registros de concreto o mampostería.',
                 'No es indispensable experiencia si tiene buena condición física y ganas de aprender.'],
    escolaridad=['Saber leer y escribir; primaria terminada deseable.',
                 'Saber usar cinta métrica y nivel de mano.'],
    persona=['Cuida el material: no arrastra el geotextil ni avienta el tubo.',
             'Revisa cada unión antes de cubrirla.',
             'Trabaja en equipo, con una sola voz de mando dentro de la zanja.',
             'Sale de la zanja sin discutir cuando se lo piden.'],
    alertas=['Le parece exagerado cuidar el geotextil "si de todos modos se entierra".',
             'Se mete a zanjas sin revisar la pared.',
             'No usa guantes ni lentes.'],
    preguntas=[('El geotextil trae un corte de 10 cm. ¿Lo pones así?', 'No: se cambia o se parcha con un traslape amplio, y se avisa al cabo.'),
               ('Llega grava con tierra y lodo. ¿Qué haces?', 'Avisar al cabo: la grava sucia tapa el geotextil y el dren deja de funcionar.'),
               ('La retroexcavadora se acerca mientras estás en la zanja. ¿Qué haces?', 'Salir o hacerse visible y esperar la señal del operador.')],
    prueba='Una jornada de prueba en un tramo de 30 m con la cuadrilla: tender geotextil con traslapes de 30 cm, colocar y unir el tubo, rodearlo de grava, cerrar el geotextil y armar una salida con su cabezal. Aprueba si los traslapes cumplen, las uniones no se sueltan al jalar, el tubo queda sin columpios según el nivel y trabaja seguro dentro de la zanja.',
    indicadores=['Tramos rechazados por el cabo por geotextil, uniones o grava: cero.', 'Salidas completas con cabezal y registro.',
                 'Material dañado o desperdiciado.', 'Asistencia y cero incidentes en zanja.'],
    dia=[('06:30', 'Plática de seguridad; revisas guantes, lentes, casco, chaleco y botas; recibes el material del día.'),
         ('07:00–13:00', 'Geotextil, tubo y grava detrás de la zanjadora; el cabo revisa antes de tapar.'),
         ('13:00', 'Comida y descanso a la sombra.'),
         ('13:30–16:30', 'Salidas, cabezales y registros; limpieza de lo que quedó.'),
         ('16:30–17:00', 'Guardas el material a la sombra, cubres lo abierto y reportas al cabo.')],
    saber=['El dren de borde saca el agua de abajo de la carretera. El agua atrapada es lo que más carreteras destruye en México: tu trabajo es la primera defensa.',
           'El tubo es perforado, de 10 cm. Las uniones deben quedar firmes; si se sueltan, entra tierra y el tubo se tapa.',
           'Geotextil: traslape de al menos 30 cm, sin cortes, sin tierra encima. Guárdalo a la sombra: el sol lo debilita en pocos días.',
           'La grava drenante tiene que llegar limpia. Grava con tierra o lodo tapa el geotextil y el dren deja de funcionar.',
           'Cada 60–100 m va una salida: tubo liso que baja a la cuneta y termina en un cabezal visible con registro de limpieza, para que alguien lo revise y lo limpie en el año 20.',
           'Nunca bajes a una zanja con la pared floja o de más de 1.5 m sin talud o ademe; nunca estés en la zanja bajo el bote de la retroexcavadora.'],
    numeros=[('10 cm', 'diámetro del tubo perforado'), ('30 cm', 'traslape mínimo del geotextil'), ('60–100 m', 'distancia entre salidas'),
             ('1 km', 'dren de borde que se hace cada día'), ('1.5 m', 'zanja más honda que esto: sólo con talud o ademe')],
    errores=['Dejar el geotextil con traslape corto o rasgado.', 'Unir el tubo "a medias".', 'Echar grava sucia.',
             'Hacer una salida sin cabezal ni registro.', 'Meterse a la zanja bajo la máquina.'],
    capacitacion=[('Días 2 a 5', 'Trabaja junto a un integrante con experiencia; aprende a tender geotextil, unir tubo y revisar pendiente con nivel.'),
                  ('Semana 2', 'Construcción de cabezales y registros; seguridad en zanjas con Seguridad e higiene.'),
                  ('Tramo de prueba', 'Construye el dren de los 500 m del tramo de prueba y ve la prueba con agua; toma el curso de seguridad y calidad.'),
                  ('Mes 3 a 6', 'Si quiere crecer, práctica controlada en el compactador de zanja con el operador.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción, excavaciones y zanjas) con constancia DC-3.',
                     'Uso de equipo de protección personal (NOM-017-STPS) y manejo manual de materiales (NOM-006-STPS).'],
    comprobacion=['¿Cuánto traslapas el geotextil?',
                  '¿Qué haces si llega grava sucia?',
                  '¿Qué lleva cada salida y cada cuántos metros va?',
                  '¿Cuándo no bajas a una zanja?'],
    siguiente='Operador del frente de drenaje (compactador de zanja o retroexcavadora): seis meses sin faltas, el curso del tramo de prueba y la certificación de la máquina.',
)

# ─────────────────────────── Frente 3 · Base ───────────────────────────

P['Cabo de base'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='frente',
    mision='Entregar cada día 1 km de base de concreto pobre de 20 cm, compactada, pareja y curada, con su interfaz bituminosa de 4–6 cm encima, lista para que el acero y el tren trabajen sobre ella.',
    importa='La base es lo que el agua no lava y la interfaz es lo que deja a la losa encogerse sin agrietarse: el detalle que casi nadie pone en México. Si la base queda desigual, el tren no puede corregirlo; si la interfaz falta o se ensucia, la losa se agrieta en sus primeros días.',
    responde=['El avance diario de la base y la interfaz, y los días de colchón sobre el colado, medidos cada tarde.',
              'El espesor, la compactación y la regularidad de la base: que no haya zonas flojas ni escalones.',
              'Que el concreto pobre se tienda y compacte a tiempo, antes de que empiece a fraguar.',
              'El curado húmedo de la base hasta que recibe la interfaz.',
              'Una interfaz completa, a su espesor y limpia: sin polvo, lodo ni tráfico de obra encima.',
              'La coordinación con planta y con los volteos que le traen la mezcla.'],
    autoridad=['Rechazar volteos con mezcla seca, segregada o que ya pasó su tiempo, avisando al laboratorio.',
               'Detener la extendedora si la alimentación es irregular o la mezcla no compacta.',
               'Cerrar su tramo al tráfico de obra hasta que la base y la interfaz estén listas.',
               'No le toca: aceptar una base fuera de espesor o de compactación sin la firma del laboratorio.'],
    experiencia=['5 años o más en pavimentación con extendedora (asfalto, bases estabilizadas o concreto compactado con rodillo), al menos 2 como cabo o sobrestante de un tendido.',
                 'Haber trabajado con control de densidad y espesor por laboratorio y con riegos de liga o emulsiones.',
                 'Deseable: experiencia con concreto compactado con rodillo o bases tratadas con cemento.'],
    escolaridad=['Secundaria terminada como mínimo; bachillerato técnico deseable.',
                 'Leer secciones y perfiles, calcular volúmenes y rendimientos, y llenar la bitácora en tableta.'],
    persona=['Controla el reloj: sabe a qué hora se mezcló cada volteo.',
             'Mide el espesor detrás de la extendedora sin esperar a que se lo pidan.',
             'No deja pasar a nadie por su base fresca ni por la interfaz.',
             'Coordina con la planta con anticipación, no a gritos.'],
    alertas=['Trata la base "como un relleno más".',
             'No conoce los riesgos de compactar un concreto que ya empezó a fraguar.',
             'Dice que la interfaz "no hace falta" o que "es sólo chapopote".',
             'Deja circular volteos sobre base recién tendida.'],
    preguntas=[('Llega un volteo con la mezcla que salió de planta hace 70 minutos y hace 35 °C. ¿Qué haces?', 'No la tiende: se rechaza y se avisa al laboratorio; un concreto pobre que ya fraguó no compacta y queda flojo.'),
               ('La extendedora se detuvo 90 minutos por falta de volteos. ¿Qué haces con la orilla?', 'Hace junta fría: corta vertical lo que ya no compacta, limpia y humedece antes de continuar.'),
               ('¿Por qué importa la interfaz de 4–6 cm?', 'Porque deja que la losa se encoja al secarse sin agrietarse; sin ella la losa queda amarrada a la base.'),
               ('Los fierreros quieren meter una camioneta sobre la interfaz. ¿Qué dices?', 'Que no: se ensucia o se rompe la interfaz; entran por el acceso marcado.')],
    prueba='Medio día en un tramo de prueba: debe revisar la alimentación de la extendedora, medir el espesor suelto y compactado, detectar dos defectos sembrados (un volteo con mezcla vieja y una zona con espesor corto) y organizar el curado y el riego del tramo. Aprueba si rechaza la mezcla vieja, corrige el espesor antes de compactar, ordena bien el curado y la cuadrilla trabaja segura con la emulsión.',
    indicadores=['Metros de base con interfaz terminados contra 1,000 m diarios.', 'Días de colchón sobre el colado, siempre ≥ 3 y sin base expuesta de más.',
                 'Espesor y densidad dentro de especificación en los ensayos del laboratorio.', 'Tramos con interfaz sucia o dañada al llegar el tren: cero.', 'Cero accidentes con tiempo perdido.'],
    dia=[('06:00', 'Junta de cierre: das los días de colchón de tu frente y confirmas con el jefe de planta los m³ y horarios del día.'),
         ('06:30', 'Plática de seguridad, revisión de extendedora, rodillos y petrolizadora; limpieza del tramo que recibe.'),
         ('07:00–13:00', 'Tendido y compactación de base; mides espesor y tiempos de cada volteo.'),
         ('13:30–16:30', 'Curado de la base del día y riego o tendido de interfaz sobre la base de días anteriores.'),
         ('17:00', 'Cierras el tramo al tráfico, metros en bitácora y entregas al cabo de colado lo que está listo.')],
    saber=["La base es concreto pobre de 15–20 cm (en nuestro diseño, 20 cm) con f'c de 100–150 kg/cm² y apenas 120–150 kg de cemento por m³. Se tiende con extendedora de alta densidad y se compacta con rodillos, como concreto compactado con rodillo.",
           'La base sobresale unos 15 cm por lado de lo que se cuela encima, para que el borde de la losa también quede apoyado.',
           'El reloj manda: la mezcla se tiende y se compacta en menos de 60 minutos desde que salió de la planta, menos con calor. Lo que ya empezó a fraguar no compacta: queda flojo aunque se vea bien.',
           'Compactación de al menos 98 % de la densidad que fija el laboratorio y superficie sin escalones mayores a 1 cm con regla de 3 m.',
           'Si la extendedora se detiene más de lo que aguanta la mezcla, se hace junta fría: corte vertical, limpieza y humedad antes de seguir.',
           'La base se mantiene húmeda desde que el rodillo termina hasta que recibe la interfaz; una base que se seca al sol se agrieta.',
           'Interfaz bituminosa de 4–6 cm o doble riego de emulsión con geotextil. Existe para que la losa se encoja al secarse sin agrietarse. Tiene que llegar completa y limpia al tren.',
           'Tu colchón: al menos 3 días sobre el colado, pero sin dejar base expuesta días de más, porque se contamina y hay que limpiarla.'],
    numeros=[('20 cm', 'espesor de la base de concreto pobre'), ("100–150", "f'c de la base en kg/cm²"), ('< 60 min', 'de la planta a la compactación'),
             ('98 %', 'compactación mínima de la base'), ('4–6 cm', 'espesor de la interfaz bituminosa'), ('3 días', 'colchón mínimo sobre el colado')],
    errores=['Tender mezcla vieja "para no tirarla".', 'Dejar secar la base al sol sin curado.',
             'Dejar pasar tráfico de obra sobre la interfaz.', 'Omitir la interfaz en un tramo "porque se acabó la emulsión".',
             'Continuar sin junta fría después de un paro largo.'],
    capacitacion=[('Días 2 a 5', 'Recorre con el jefe de planta el ciclo de la mezcla de base y con el laboratorio los ensayos de espesor, densidad y resistencia.'),
                  ('Semana 2', 'Con el topógrafo: control 3D o de niveles de la extendedora; con Seguridad: manejo de emulsiones calientes.'),
                  ('Tramo de prueba', 'Construye la base y la interfaz de los 500 m del tramo de prueba, incluida la variante con capa inferior de concreto compactado con rodillo.'),
                  ('Mes 2 a 3', 'Revisión semanal con el superintendente y el cabo de colado: colchón, estado de la base al llegar el tren y rechazos.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción) y NOM-004-STPS (maquinaria), con constancia DC-3.',
                     'Manejo seguro de asfaltos y emulsiones (NOM-010-STPS y hojas de datos de seguridad).',
                     'Técnico en concreto compactado con rodillo o bases tratadas con cemento (curso con el laboratorio del proyecto).'],
    comprobacion=['¿En cuánto tiempo máximo se tiende y compacta la mezcla de base?',
                  '¿Para qué sirve la interfaz y qué pasa si falta?',
                  '¿Qué haces después de un paro largo de la extendedora?',
                  '¿Por qué no dejas base expuesta días de más?'],
    siguiente='Cabo de colado (el tren) o, con dos años de colchón sano y cero tramos rechazados, apoyo al superintendente en varios frentes.',
    pedimos=['Cerrar tu tramo al tráfico de obra, aunque te lo pida alguien con más jerarquía.'],
)

P['Operador de extendedora y rodillos'] = dict(
    linea='Producción', reporta='Cabo de base', esquema='frente',
    mision='Operar la extendedora de alta densidad, el rodillo vibratorio liso o el rodillo neumático para dejar la base de concreto pobre con su espesor, su densidad y su regularidad en cada metro.',
    importa='La base se compacta en una ventana corta: lo que el rodillo no aprieta antes de que el concreto empiece a fraguar se queda flojo para siempre. Y una base con escalones obliga al tren a compensar con concreto de más o con losa de menos.',
    responde=['Extendedora: tender la base a espesor y nivel parejos, a velocidad constante, sin segregar la mezcla.',
              'Rodillos: el patrón de pasadas que fija el laboratorio, completo en todo el ancho y en las orillas.',
              'Compactar a tiempo, detrás de la extendedora, sin dejar pasar la ventana de la mezcla.',
              'La revisión diaria de su máquina y la bitácora de horas y fallas.',
              'Avisar de inmediato de mezcla seca, segregada o que no cierra bajo el rodillo.'],
    autoridad=['Detener su máquina si la mezcla no compacta o si hay alguien en su zona ciega.',
               'Pedir al cabo que el laboratorio revise un volteo o una zona.',
               'Negarse a operar con fallas de frenos, vibración, sensores o alarma.',
               'No le toca: cambiar el espesor, el patrón de pasadas o la vibración sin indicación del cabo o del laboratorio.'],
    experiencia=['3 años o más operando extendedora (pavimentadora de asfalto) o rodillos vibratorios o neumáticos en pavimentación de carreteras.',
                 'Haber trabajado con control de espesor y densidad por laboratorio.',
                 'Deseable: experiencia con concreto compactado con rodillo, bases tratadas con cemento o control de niveles automático en la extendedora.'],
    escolaridad=['Primaria terminada como mínimo, secundaria deseable; saber leer y escribir.',
                 'Constancia DC-3 de la máquina que opera o disposición a certificarse en el primer mes.'],
    persona=['Mantiene la misma velocidad toda la jornada.',
             'Mira hacia atrás: revisa lo que dejó su máquina.',
             'Se coordina con los otros operadores sin gritos: cada uno sabe su lugar en el tren de la base.',
             'Avisa temprano cuando algo no compacta.'],
    alertas=['Dice que "vibra más fuerte" para arreglar cualquier cosa.',
             'Ha operado sólo en asfalto y no entiende que el concreto fragua.',
             'Detiene la extendedora cada vez que falta un volteo en lugar de ajustar la velocidad.'],
    preguntas=[('El rodillo ya pasó y la base se ve con grietas finas y material suelto. ¿Qué pasó y qué haces?', 'Que se compactó tarde o seco; se detiene y avisa al cabo, no sigue vibrando encima.'),
               ('Los volteos llegan irregulares. ¿Cómo manejas la extendedora?', 'Baja la velocidad para no detenerse; una extendedora que para y arranca deja escalones.'),
               ('¿Cómo compactas una orilla sin confinar?', 'Con el traslape indicado y sin salirse del borde; la orilla se revisa con el laboratorio porque es donde más falta densidad.')],
    prueba='Dos horas en la máquina que solicita, en un tramo de prueba de 100 m: extendedora, tender a espesor con velocidad constante (aprueba si topografía y el laboratorio encuentran el espesor dentro de ±1 cm y sin segregación); rodillo, compactar con el patrón indicado detrás de la extendedora (aprueba si la densidad sale sobre 98 % y la superficie no tiene escalones mayores a 1 cm en regla de 3 m). Se evalúa la revisión previa y la coordinación con los demás operadores.',
    indicadores=['Tramos rechazados por espesor, densidad o regularidad atribuibles a su máquina: cero.', 'Paros de la extendedora por mala coordinación.',
                 'Horas de paro de su máquina por falla evitable.', 'Cero incidentes con personas o máquinas.'],
    dia=[('06:30', 'Plática de seguridad y revisión de tu máquina: vibración, sensores, frenos, agua de riego del rodillo y alarma.'),
         ('07:00–13:00', 'Tendido y compactación de la base, en el orden y los tiempos que marca el cabo.'),
         ('13:00', 'Comida en relevo, sin dejar base sin compactar.'),
         ('13:30–16:30', 'Tendido y compactación; si toca, tendido de la interfaz sobre la base de días anteriores.'),
         ('16:30–17:00', 'Limpieza de la máquina (el concreto pegado se quita hoy, no mañana), revisión y bitácora.')],
    saber=["La base es concreto pobre de 20 cm, f'c 100–150 kg/cm². Es concreto, no tierra: empieza a fraguar, y lo que no se compacta a tiempo se queda flojo.",
           'Desde que la mezcla sale de planta hasta que termina el rodillo: menos de 60 minutos, menos con calor. El rodillo va pegado a la extendedora.',
           'Extendedora: velocidad constante y alimentación pareja; el espesor suelto es mayor que el final porque el rodillo lo baja. Si faltan volteos, baja la velocidad en lugar de parar.',
           'Rodillo liso de 10–12 t: el número de pasadas y la vibración que fija el laboratorio, con traslape parejo; nunca vibres encima de concreto que ya fraguó.',
           'Rodillo neumático al final: cierra y sella la superficie.',
           'Meta: 98 % de la densidad del laboratorio y superficie sin escalones mayores a 1 cm en regla de 3 m.',
           'Limpia la máquina el mismo día: el concreto pegado en la tolva, el tornillo o el rodillo se endurece y la descompone.'],
    numeros=[('20 cm', 'espesor final de la base'), ('< 60 min', 'de la planta al último pase de rodillo'), ('10–12 t', 'peso del rodillo vibratorio liso'),
             ('98 %', 'densidad mínima de la base'), ('1 cm', 'escalón máximo en regla de 3 m')],
    errores=['Compactar tarde, cuando el concreto ya fraguó.', 'Detener y arrancar la extendedora cada vez que falta un volteo.',
             'Vibrar de más en un solo lugar.', 'Dejar la máquina sucia de concreto para el día siguiente.'],
    capacitacion=[('Días 2 a 5', 'Opera acompañado de un operador con experiencia del proyecto; aprende el patrón de pasadas y los tiempos de la mezcla.'),
                  ('Semana 2', 'Con el laboratorio: cómo se mide la densidad y el espesor de la base; con topografía: control de niveles de la extendedora.'),
                  ('Tramo de prueba', 'Opera en los 500 m del tramo de prueba, donde se fija el número de pasadas, incluida la variante con capa inferior de concreto compactado con rodillo.'),
                  ('Mes 2 a 3', 'Evaluación de su bitácora y de los ensayos de su tramo; certificación DC-3 de su máquina si no la tenía.')],
    certificaciones=['Constancia DC-3 de habilidades en extendedora o rodillo compactador.',
                     'NOM-004-STPS (seguridad en maquinaria) y NOM-031-STPS (construcción).',
                     'Curso de concreto compactado con rodillo con el laboratorio del proyecto.'],
    comprobacion=['¿En cuánto tiempo máximo se compacta la base desde que sale de la planta?',
                  '¿Qué haces con la extendedora si los volteos llegan irregulares?',
                  '¿Qué densidad y qué regularidad debe tener la base?',
                  '¿Por qué no se vibra encima de concreto que ya fraguó?'],
    siguiente='Operador de la colocadora-esparcidora o de la máquina de textura y curado del tren, o cabo de base con dos años de bitácora limpia.',
)

P['Cuadrilla de apoyo y riego'] = dict(
    linea='Producción', reporta='Cabo de base', esquema='frente',
    mision='Dejar la base lista para el tren: limpiar la superficie, rematar orillas, mantener la base húmeda mientras cura y aplicar el riego de liga o de emulsión parejo y a su dosis.',
    importa='Una interfaz sobre polvo no pega y una base que se seca al sol se agrieta. Son trabajos de mano que nadie ve cuando llega el tren, y de los que depende que la losa pueda encogerse sin agrietarse en sus primeros días.',
    responde=['Rematar a mano orillas y bordes de la base detrás de la extendedora.',
              'Mantener la base húmeda desde que termina el rodillo hasta que recibe la interfaz.',
              'Barrer y soplar la superficie antes de cualquier riego: sin polvo, lodo ni piedras sueltas.',
              'Aplicar el riego de liga o de emulsión con la barra o la lanza, a la dosis que indica el laboratorio.',
              'Colocar conos y cerrar el tramo al tráfico de obra.'],
    autoridad=['Detener el riego si la superficie está sucia, mojada de más o si llueve.',
               'Avisar al cabo de cualquier zona floja, agrietada o sucia en la base.',
               'No le toca: cambiar la dosis de emulsión ni abrir el tramo al tráfico.'],
    experiencia=['1 año o más como ayudante en pavimentación (asfalto, bases o concreto), idealmente en riegos de liga o de impregnación.',
                 'Deseable: uno de la cuadrilla con experiencia operando la petrolizadora o distribuidor de emulsión.',
                 'No es indispensable experiencia si tiene buena condición física y ganas de aprender.'],
    escolaridad=['Saber leer y escribir; primaria terminada deseable.',
                 'Para quien maneje la petrolizadora: licencia de chofer de carga vigente.'],
    persona=['Barre bien aunque "ya se vea limpio".',
             'Cuida la base como si ya fuera la carretera: no la pisa con lodo.',
             'Usa su equipo completo con la emulsión caliente, aunque haga calor.',
             'Trabaja parejo toda la jornada, sin dejar tramos a medias.'],
    alertas=['Dice que el polvo "no importa porque el riego lo pega".',
             'No usa guantes ni lentes con productos calientes.',
             'Le da igual regar de más o de menos.'],
    preguntas=[('La base tiene polvo y el camión de emulsión ya llegó. ¿Qué haces?', 'Barrer y soplar primero; la emulsión sobre polvo no pega.'),
               ('Son las 2 de la tarde y la base de la mañana ya se ve blanca y seca. ¿Qué haces?', 'Regarla con agua de inmediato y avisar al cabo; la base se cura húmeda.'),
               ('¿Cómo sabes si el riego quedó a la dosis correcta?', 'Con la prueba de charola que indica el laboratorio y viendo que no haya charcos ni zonas sin cubrir.')],
    prueba='Una jornada de prueba en un tramo de 100 m: rematar orillas detrás de la extendedora, mantener húmeda la base, barrer y aplicar un riego de emulsión con la lanza o la barra. Aprueba si la superficie queda limpia antes del riego, la prueba de charola da la dosis indicada, no quedan charcos ni franjas secas y trabaja con su equipo completo.',
    indicadores=['Tramos rechazados por superficie sucia o riego disparejo: cero.', 'Base sin curado: cero tramos secos al sol.',
                 'Asistencia y puntualidad.', 'Cero quemaduras o incidentes con emulsión.'],
    dia=[('06:30', 'Plática de seguridad; equipo completo: guantes, lentes, manga larga, casco, chaleco y botas.'),
         ('07:00–13:00', 'Rematas orillas detrás de la extendedora y mantienes húmeda la base recién compactada.'),
         ('13:00', 'Comida por relevos, sin dejar la base secarse.'),
         ('13:30–16:30', 'Barres, soplas y aplicas el riego sobre la base de días anteriores; cierras el tramo con conos.'),
         ('16:30–17:00', 'Limpieza de barra, lanza y herramienta; reporte al cabo.')],
    saber=['La base es concreto: se cura húmeda. Desde que el rodillo termina hasta que recibe la interfaz no debe secarse; si se ve blanca y seca, riega.',
           'Encima de la base va la interfaz de 4–6 cm o un doble riego de emulsión con geotextil. Sirve para que la losa se encoja sin agrietarse.',
           'Antes de cualquier riego: barrer y soplar. La emulsión sobre polvo no pega.',
           'La dosis la fija el laboratorio (un riego de liga suele andar entre 0.3 y 0.6 L por m²). Se verifica con la prueba de charola; sin charcos y sin franjas secas.',
           'Nadie pisa ni circula sobre el riego fresco o la interfaz: se ensucia y se rompe.',
           'La emulsión puede ir caliente: guantes, lentes, manga larga; si te salpica, agua fría y avisas.',
           'La base sobresale unos 15 cm por lado de lo que se cuela: remata la orilla para que quede firme y pareja.'],
    numeros=[('20 cm', 'espesor de la base que cuidas'), ('4–6 cm', 'espesor de la interfaz'), ('0.3–0.6 L/m²', 'dosis típica de un riego de liga, la exacta la da el laboratorio'),
             ('15 cm', 'lo que la base sobresale por lado'), ('1 km', 'lo que tu frente deja listo cada día')],
    errores=['Regar emulsión sobre polvo.', 'Dejar secar la base al sol.', 'Regar de más y hacer charcos.', 'Dejar pasar camionetas sobre el riego fresco.'],
    capacitacion=[('Días 2 a 5', 'Trabaja junto a un integrante con experiencia; aprende a rematar orillas y el curado húmedo de la base.'),
                  ('Semana 2', 'Con el laboratorio: prueba de charola y dosis; con Seguridad: manejo seguro de emulsiones calientes.'),
                  ('Tramo de prueba', 'Trabaja en los 500 m del tramo de prueba y toma el curso de seguridad y calidad.'),
                  ('Mes 3 a 6', 'Si quiere crecer, práctica controlada en la petrolizadora o en un rodillo con un operador certificado.')],
    certificaciones=['NOM-031-STPS (seguridad en construcción) con constancia DC-3.',
                     'Manejo seguro de asfaltos y emulsiones (NOM-010-STPS y hojas de datos de seguridad).',
                     'Uso de equipo de protección personal (NOM-017-STPS).'],
    comprobacion=['¿Qué haces antes de cualquier riego?',
                  '¿Cómo cuidas la base mientras llega la interfaz?',
                  '¿Cómo compruebas la dosis del riego?',
                  '¿Qué haces si la emulsión te salpica?'],
    siguiente='Operador de extendedora y rodillos: seis meses sin faltas, el curso del tramo de prueba y la certificación de la máquina.',
)
