# -*- coding: utf-8 -*-
# RLR · Perfiles de Frente 4 · Colado — Ricardo López Reyero
P = {}

P['Cabo de colado'] = dict(
    linea='Producción', reporta='Residente de colado', esquema='frente',
    mision='Mandar el tren de colado minuto a minuto, de 19:00 a 05:00, para que la pavimentadora nunca se detenga y cada metro quede como dice la especificación.',
    importa='Es la voz que la cuadrilla oye a las 3 de la mañana. El residente decide el tren; el cabo hace que 34 personas se muevan como una sola, sin gritos y sin atajos.',
    responde=['Que cada puesto del tren esté cubierto, en su lugar y con su equipo a las 18:30, antes de que llegue el primer camión.',
              'La distancia entre las cuatro máquinas: colocadora, pavimentadora, textura y curado, siempre en su orden y a su separación.',
              'Que el acero de esta noche esté revisado y liberado antes de colar, y que el de pasado mañana vaya avanzando de día.',
              'El registro de cada paro del tren con su hora de inicio, de fin y su causa, entregado al residente a las 05:00.',
              'Que nadie pise la losa fresca, nadie añada agua y nadie se meta entre dos máquinas.',
              'La cabecera de fin de colado (junta de construcción) bien armada al cierre de cada noche.'],
    autoridad=['Detener el tren por seguridad o por un defecto que ve con sus ojos, y avisar al residente en ese momento.',
               'Mover gente entre puestos del tren durante la noche para cubrir una falta o un cuello de botella.',
               'Sacar del frente a quien llegue en malas condiciones o no respete una regla de seguridad.',
               'No le toca: aceptar o rechazar camiones (eso es del laboratorista) ni reanudar un colado detenido por Calidad.'],
    experiencia=['5 años o más en colados de pavimento de concreto con cimbra deslizante, al menos 2 mandando cuadrilla de noche.',
                 'Haber trabajado en un tren completo: colocadora, pavimentadora y máquina de textura y curado, no sólo colado a mano con regla vibratoria.',
                 'Deseable: haber vivido un colado de concreto reforzado continuo (acero corrido sobre sillas) o de losa con pasajuntas en autopista.',
                 'Haber visto una noche que salió mal y poder contar qué la tumbó.'],
    escolaridad=['Secundaria terminada como mínimo; bachillerato o técnico en construcción deseable.', 'Leer planos de sección y de acero, y llevar una bitácora escrita o en tableta.'],
    persona=['Llega antes que su cuadrilla y se va después.', 'Da la instrucción una vez, clara y con calma, y verifica que se cumplió.',
             'Corrige en privado y reconoce en público.', 'Dice "paramos" sin dudar cuando alguien está en riesgo, aunque vayan bien de metros.',
             'Conoce a cada persona de su tren por su nombre y sabe quién se cansa a qué hora.'],
    alertas=['Presume de "sacar los metros como sea" o de "arreglar el concreto con tantita agua".', 'Habla de su cuadrilla como "la gente" y no sabe nombres.',
             'Culpa siempre a la planta o a los camiones de sus paros.', 'Nunca ha parado un colado por seguridad.'],
    preguntas=[('Son las 2 a. m. y el acabador te dice que la mezcla viene dura y que con una cubeta de agua se arregla. ¿Qué haces?', 'Que lo prohíbe en ese momento, avisa al laboratorista para que revise el camión y registra el caso. Nunca agua.'),
               ('La colocadora se está separando de la pavimentadora porque los camiones se atrasan. ¿Qué haces?', 'Que baja la velocidad del tren parejo, avisa al despachador y al residente; no deja que el concreto espere de más delante del molde.'),
               ('¿Cómo sabes que el acero de esta noche está listo?', 'Que lo recorre antes de las 18:30: sillas firmes, separación de 15 cm, traslapes escalonados, altura a un tercio del espesor y amarres completos.'),
               ('Falta un acabador y un señalero. ¿A quién mueves y a quién no?', 'Que nunca deja sin cubrir el tránsito; pide apoyo a Seguridad e higiene y cubre el acabado con el apoyo general o el ayudante.')],
    prueba='Noche de prueba en el tramo de 500 m (o en un colado real como segundo del cabo titular), de 18:00 a 05:00. Debe pasar lista, revisar el acero, acomodar las máquinas y llevar el registro de paros con causa. Aprueba si su registro coincide con el control 3D de la pavimentadora (diferencia menor a 5 minutos en total) y si el residente y el laboratorista no reportan ninguna regla rota.',
    indicadores=['Metros colados contra la meta de la noche (1,000 m a ritmo pleno).', 'Minutos de paro del tren atribuibles a la cuadrilla: menos de 10 por noche.',
                 'Paros registrados con causa: 100 %.', 'Cero accidentes con tiempo perdido y cero casos de agua añadida.', 'Cabecera de fin de colado aceptada por Calidad todas las noches.'],
    dia=[('17:30', 'Junta de 10 minutos con el residente: metros, camiones, temperatura y clima esperados.'),
         ('18:00–18:30', 'Pasas lista, revisas el equipo de protección, repartes puestos y recorres el acero de esta noche.'),
         ('18:30–19:00', 'Colocas máquinas, verificas sensores 3D, luces, rompevientos y pasarela. Plática de seguridad de 5 minutos.'),
         ('19:00–05:00', 'Mandas el tren. Cada paro lo anotas con hora y causa. Rotas descansos sin dejar un puesto vacío.'),
         ('05:00–05:30', 'Armas la cabecera de fin de colado, limpias máquinas y entregas el registro al residente.'),
         ('06:00', 'Junta de cierre: explicas tus paros sin culpar a nadie.')],
    saber=['La sección que colamos: dos carriles de 4.20 m (8.40 m) por 27 cm; la raya se pinta a 3.60 m para que el tráiler no pise el borde; 2.27 m³ por cada metro lineal.',
           'El ritmo: 227 m³ por hora son 28 camiones de 8 m³, uno cada 2 minutos. El tren avanza de 1 a 2 metros por minuto. Si un camión falta, se baja la velocidad parejo; nunca se para y arranca a tirones.',
           'El acero en CRCP: varilla #6 cada 15 cm a lo largo, #4 cada 90 cm a lo ancho, a un tercio del espesor desde arriba (unos 9 cm) sobre sillas, con 7 cm de recubrimiento mínimo. Hombro amarrado con #4 cada 75 cm.',
           'El orden del tren no se cambia: colocadora-esparcidora, pavimentadora, máquina de textura y curado. Si la textura se atrasa, la superficie se seca al aire y se pierde el curado.',
           'Cada vez que la pavimentadora se detiene queda una junta fría y una marca que no se repara. Una hora de paro cuesta el 10 % de la producción del día.',
           'Cuándo no se cuela: evaporación arriba de 0.5 kg/m² por hora sin poder bajarla con rompevientos, lluvia sobre concreto fresco o concreto arriba de 30 °C. Esa decisión la toman el residente y Calidad; tú la haces cumplir.',
           'La cabecera de fin de colado: se corta a escuadra, se deja el acero corrido y el acero adicional que marca el plano, y el concreto de ese borde se vibra a mano.'],
    numeros=[('19:00–05:00', 'la ventana de colado: diez horas, mil metros'), ('2 min', 'un camión en la colocadora, toda la noche'), ('1–2 m/min', 'velocidad del tren'),
             ('< 30 min', 'meta de paro total del tren por noche, con causa'), ('34', 'personas en el frente de colado'), ('2 días', 'lo que va adelantado el acero')],
    errores=['Permitir una cubeta de agua "para que se deje trabajar".', 'Apurar la pavimentadora para recuperar metros después de un paro.',
             'Dejar un puesto del tren sin cubrir durante un descanso.', 'Esconder un paro o cambiarle la causa en el registro.', 'Cerrar la noche con una cabecera mal armada por prisa.'],
    capacitacion=[('Días 2 a 5', 'Cuatro noches como segundo del cabo titular o del residente en el tramo de prueba: pasar lista, revisar acero, llevar el registro de paros.'),
                  ('Semana 2', 'Una noche junto a cada máquina (colocadora, pavimentadora, textura y curado) y una noche en planta con el Jefe de planta para entender de dónde viene cada camión.'),
                  ('Semanas 3 y 4', 'Mandas el tren con el residente a un lado; revisión de tu registro contra el control 3D cada mañana.'),
                  ('Primeros 3 meses', 'Curso de mando de cuadrilla y de seguridad en frentes abiertos al tránsito; revisión mensual con el residente.')],
    certificaciones=['NOM-031-STPS (seguridad en obras de construcción) y NOM-017-STPS (equipo de protección personal).', 'Primeros auxilios y brigada de emergencia.',
                     'ACI Concrete Field Testing Technician Grade I (para entender lo que mide el laboratorista), pagada por la empresa.', 'Curso de lectura de planos de acero en pavimento continuo.'],
    comprobacion=['¿Cuántos camiones por hora necesita el tren y cada cuánto llega uno?', '¿A qué altura va el acero y cuánto recubrimiento lleva?',
                  '¿Qué haces si la colocadora se separa de la pavimentadora?', '¿Qué tiene que tener cada renglón de tu registro de paros?'],
    siguiente='Residente de colado, con estudios de ingeniería, o Superintendente de frente por la escalera de mando de campo.',
    pedimos=['Pasar lista a las 18:00 en punto, todas las noches, aunque falte el residente.'],
)

P['Operador de pavimentadora'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Operar la pavimentadora de cimbra deslizante a velocidad constante y con control 3D, para dejar una losa de 27 cm con bordes rectos, superficie cerrada y sin juntas frías.',
    importa='Es la máquina que todos miran y la que decide la suavidad que el perfilómetro medirá por 50 años. Un operador nervioso que acelera y frena deja en la losa cada uno de sus cambios de humor.',
    responde=['La velocidad pareja del tren: de 1 a 2 metros por minuto, sin tirones.',
              'El espesor y la rasante según el modelo 3D, verificados con los sensores y con las mediciones del topógrafo.',
              'La frecuencia de los vibradores: que consoliden sin dejar rastros de vibración ni segregar.',
              'Bordes a plomo y sin caída de orilla; barras de amarre del hombro insertadas a su distancia.',
              'Revisión diaria de la máquina con el mecánico y bitácora de horas.'],
    autoridad=['Bajar la velocidad o detener la máquina si ve un riesgo para alguien o un defecto que no se puede corregir en marcha.',
               'Pedir al cabo que se corrija la cabeza de concreto delante del molde (mucha o poca).',
               'No arrancar si el sistema 3D no está verificado contra los puntos de control del topógrafo.',
               'No le toca: aceptar concreto fuera de especificación ni cambiar el modelo 3D por su cuenta.'],
    experiencia=['5 años o más operando pavimentadora de cimbra deslizante en carreteras o aeropuertos, con control automático (hilo o 3D).',
                 'Haber colado anchos de 7 m o más en una sola pasada.',
                 'Deseable: experiencia con acero corrido sobre sillas (CRCP) o con insertadora de pasajuntas.'],
    escolaridad=['Secundaria terminada; saber leer, escribir y hacer cuentas.', 'Licencia o constancia de operador de maquinaria pesada vigente.', 'Manejo básico de pantallas y menús del control de la máquina.'],
    persona=['Calmado: mantiene la velocidad aunque haya prisa alrededor.', 'Mira hacia adelante (cabeza de concreto) y hacia atrás (superficie) todo el tiempo.',
             'Avisa antes de que algo falle, no después.', 'Cuida la máquina como suya: la limpia, la revisa, la conoce por su ruido.'],
    alertas=['Presume velocidades altas y no habla de suavidad.', 'Dice que "el 3D se arregla solo" o que no necesita topógrafo.',
             'No sabe explicar para qué sirven los vibradores ni qué pasa si se quedan prendidos con la máquina parada.', 'Nunca ha llenado una bitácora.'],
    preguntas=[('La máquina se tiene que detener porque no llega camión. ¿Qué haces con los vibradores?', 'Que los baja o apaga mientras está parada; si los deja prendidos sobre el mismo concreto, lo segrega y deja una marca.'),
               ('¿Qué ves en la losa cuando la vibración está demasiado alta?', 'Rastros o surcos de vibración en la superficie, pasta de más arriba y agregado hundido.'),
               ('El borde de la losa se está cayendo. ¿Qué revisas?', 'Revenimiento del concreto (avisa al laboratorista), cabeza de concreto, vibradores de orilla y la cimbra lateral; nunca que el acabador lo "arregle" con agua.'),
               ('¿Qué pasa con la suavidad si subes y bajas la velocidad?', 'Que cada cambio deja una ondulación que el perfilómetro mide como IRI.')],
    prueba='En el tramo de prueba, 2 horas continuas operando la pavimentadora en una sección de 8.40 m. Aprueba si mantiene la velocidad dentro de ±0.2 m/min de la indicada, los núcleos o sondeos de espesor salen completos (27 cm), la caída de orilla no pasa de 6 mm y el perfilómetro da IRI de 1.0 m/km o menos en su tramo.',
    indicadores=['Minutos de paro atribuibles a la operación de la máquina: cero.', 'IRI del tramo que coló: 1.0 m/km o menos.', 'Espesor completo en núcleos.',
                 'Caída de orilla dentro de tolerancia en todo el tramo.', 'Bitácora de la máquina completa cada noche.'],
    dia=[('17:30–18:30', 'Revisas la máquina con el mecánico: hidráulica, vibradores, sensores, niveles. Verificas el 3D con el topógrafo en un punto de control.'),
         ('18:30–19:00', 'Colocas la máquina en la cabecera de la noche anterior, calibras altura y ancho.'),
         ('19:00–05:00', 'Operas a velocidad constante. Vigilas la cabeza de concreto, los vibradores, los bordes y la pantalla 3D.'),
         ('05:00–05:30', 'Sacas la máquina, la lavas a fondo y anotas horas, alarmas y fallas en la bitácora.'),
         ('06:00', 'Junta de cierre si hubo paros de tu máquina.')],
    saber=['La losa: 27 cm de espesor, 8.40 m de ancho (dos carriles de 4.20 m) en una sola pasada. Un espesor corto de 1 cm cuesta años de fatiga y una penalización en núcleos.',
           'El control 3D sin hilos: la máquina se guía por el modelo digital y las estaciones GNSS o totales del topógrafo. Antes de arrancar, siempre se verifica contra un punto físico.',
           'Vibradores: se ajustan a la velocidad. Si la máquina se detiene, bajan o se apagan. Los surcos en la superficie son señal de vibración de más.',
           'La cabeza de concreto delante del molde debe ser pareja a todo lo ancho: si baja, la losa queda con huecos; si sube mucho, empuja y deforma.',
           'En CRCP la máquina pasa sobre acero corrido sobre sillas: nada de insertadora de pasajuntas en la losa; sí las barras de amarre del hombro (#4 cada 75 cm) cuando aplica.',
           'El revenimiento que la máquina quiere es de 3 a 5 cm. Si viene más duro o más aguado, lo dice el laboratorista y se corrige en planta, nunca con agua en el frente.',
           'La velocidad normal del tren es de 1 a 2 metros por minuto. Más rápido no da más metros: da peor superficie.'],
    numeros=[('27 cm', 'espesor de la losa'), ('8.40 m', 'ancho de la pasada'), ('1–2 m/min', 'velocidad del tren'), ('3–5 cm', 'revenimiento del concreto'),
             ('≤ 1.0 m/km', 'IRI de aceptación'), ('35 %', 'capacidad de sobra de la máquina: no es el cuello de botella')],
    errores=['Parar y arrancar a tirones: cada parada es una junta fría para siempre.', 'Dejar los vibradores prendidos con la máquina detenida.',
             'Arrancar sin verificar el 3D contra un punto de control.', 'Acelerar para "recuperar" después de un paro.'],
    capacitacion=[('Días 2 a 5', 'Con el mecánico y el topógrafo: la máquina completa, el sistema 3D y la verificación en puntos de control. Operación en vacío en el patio.'),
                  ('Semana 2', 'Tramo de prueba: operas con el cabo y el residente a un lado; se miden espesor, orilla e IRI de cada noche.'),
                  ('Semanas 3 y 4', 'Operación normal con revisión diaria de IRI y bitácora con el residente.'),
                  ('Primeros 3 meses', 'Certificación de la máquina con el fabricante y 500 horas limpias en bitácora.')],
    certificaciones=['NOM-004-STPS (seguridad en el uso de maquinaria) y NOM-031-STPS (construcción).', 'Certificación de operación de la pavimentadora y de su control 3D con el fabricante.',
                     'Curso básico de tecnología del concreto para pavimentos (revenimiento, aire, temperatura).'],
    comprobacion=['¿Qué haces con los vibradores si la máquina se detiene?', '¿Cómo verificas el 3D antes de arrancar?', '¿Qué revenimiento quiere la máquina y quién lo corrige si viene mal?', '¿Por qué no se acelera después de un paro?'],
    siguiente='Cabo de colado, después de dos años como operador y cero rechazos por agua o por superficie.',
)

P['Ayudante de pavimentadora'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Ser los ojos del operador alrededor de la pavimentadora: vigilar sensores, bordes, cabeza de concreto y barras de amarre, y avisar a tiempo cualquier cosa que no esté bien.',
    importa='El operador no ve los dos lados de una máquina de más de 8 metros al mismo tiempo. El ayudante es quien detecta el sensor golpeado o el borde que se cae antes de que se vuelvan 100 metros malos.',
    responde=['Revisar en cada vuelta los sensores y receptores del control 3D, que estén limpios, firmes y sin golpes.',
              'Avisar al operador por radio si la cabeza de concreto baja o sube de un lado.',
              'Vigilar la orilla de la losa: que no se caiga ni quede con huecos.',
              'Surtir y revisar las barras de amarre del hombro en la insertadora lateral.',
              'Ayudar al mecánico en la revisión de la tarde y en la limpieza al final.'],
    autoridad=['Pedir que se detenga la máquina si alguien está en su zona de peligro.', 'Avisar al laboratorista si ve que el concreto viene distinto.',
               'No le toca: operar la pavimentadora sin autorización del cabo ni tocar la configuración del 3D.'],
    experiencia=['1 año o más como ayudante en obra de concreto o en maquinaria pesada; mejor si fue en pavimentos.',
                 'Haber trabajado de noche en obra.', 'Deseable: haber visto una pavimentadora o una extendedora trabajando de cerca.'],
    escolaridad=['Primaria terminada como mínimo; secundaria deseable.', 'Saber leer y escribir; usar un radio.'],
    persona=['Atento: no se distrae con el teléfono ni la plática.', 'Avisa sin miedo aunque no esté seguro.', 'Se mueve con cuidado alrededor de la máquina, siempre a la vista del operador.', 'Quiere aprender a operar.'],
    alertas=['Se mete entre máquinas sin avisar.', 'Dice que "eso le toca al operador".', 'No quiere trabajar de noche o duda de hacerlo.'],
    preguntas=[('Ves que un sensor del 3D tiene lodo de concreto. ¿Qué haces?', 'Avisar al operador por radio y limpiarlo sólo cuando él lo autorice y sea seguro.'),
               ('El borde del lado derecho se ve más bajo. ¿A quién le dices?', 'Al operador de inmediato y al cabo; nunca intentar arreglarlo con agua.'),
               ('¿Dónde te pones para que el operador te vea?', 'Siempre en su campo de vista, fuera de la zona de giro y del camino de los camiones.')],
    prueba='Dos noches de prueba junto a un ayudante titular. Aprueba si detecta y avisa por radio las fallas que el cabo siembra o señala (un sensor tapado, una barra que falta, una orilla baja) y si en ningún momento se coloca en zona de peligro.',
    indicadores=['Avisos a tiempo de sensores, orilla y cabeza de concreto, confirmados por el operador.', 'Barras de amarre completas en todo el tramo.', 'Cero incidentes de seguridad.', 'Asistencia completa y puntual.'],
    dia=[('17:30–18:30', 'Revisión de la máquina con el mecánico y el operador; limpias sensores y surtes barras.'),
         ('18:30–19:00', 'Plática de seguridad con el cabo. Te colocas en tu lado de la máquina.'),
         ('19:00–05:00', 'Caminas junto a la máquina vigilando sensores, orilla y barras. Avisas todo por radio.'),
         ('05:00–05:30', 'Lavado completo de la máquina con el operador.')],
    saber=['La losa mide 27 cm de espesor y 8.40 m de ancho. La orilla debe quedar a plomo; si se cae, se pierde apoyo lateral.',
           'Los sensores del control 3D guían la máquina. Un golpe o una capa de lodo y la máquina cuela alta o baja sin que nadie se dé cuenta.',
           'La cabeza de concreto delante del molde debe ser pareja. Si de un lado falta, avisas para que la colocadora mande más de ese lado.',
           'Las barras de amarre del hombro son varilla #4 cada 75 cm. Si una falta, esa parte del hombro queda suelta.',
           'Nunca se añade agua al concreto. Si la mezcla viene dura, se avisa al laboratorista.'],
    numeros=[('27 cm', 'espesor de la losa'), ('8.40 m', 'ancho de la pasada'), ('75 cm', 'separación de las barras de amarre del hombro'), ('1–2 m/min', 'velocidad de la máquina')],
    errores=['Callarse porque "a lo mejor no es nada".', 'Limpiar un sensor sin avisar al operador.', 'Caminar detrás de la máquina o entre la máquina y un camión.'],
    capacitacion=[('Días 2 a 5', 'Con el operador y el mecánico: partes de la máquina, sensores, radio y zonas de peligro. Recorrido del tren de noche.'),
                  ('Semana 2', 'Tramo de prueba al lado de un ayudante titular.'),
                  ('Primeros 3 meses', 'Curso de seguridad y calidad del tramo de prueba. Horas de operación supervisada en el patio para empezar tu camino a operador.')],
    certificaciones=['NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Curso básico de seguridad en maquinaria (NOM-004-STPS).', 'Uso de radio y señales con operadores.'],
    comprobacion=['¿Qué haces si ves un sensor sucio?', '¿Cada cuánto van las barras de amarre del hombro?', '¿Dónde te colocas para que el operador te vea?'],
    siguiente='Operador de pavimentadora o de colocadora, después de seis meses sin faltas, el curso del tramo de prueba y horas supervisadas.',
)

P['Operador de colocadora-esparcidora'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Recibir el concreto de cada camión por la banda lateral y repartirlo parejo delante de la pavimentadora, sin pisar el acero y sin dejar que el concreto espere de más.',
    importa='En un pavimento con acero corrido los camiones no pueden entrar sobre la varilla: todo el concreto pasa por esta máquina. Si reparte mal, la pavimentadora cuela con huecos o empuja montañas.',
    responde=['Recibir cada camión en la tolva lateral sin derrames y sin perder el ritmo de 2 minutos.',
              'Una cabeza de concreto pareja a todo lo ancho delante de la pavimentadora.',
              'La separación correcta con la pavimentadora: ni tan lejos que el concreto pierda trabajabilidad, ni tan cerca que se estorben.',
              'Que el acero, las sillas y las barras no se muevan con el paso de la máquina.',
              'Revisión y limpieza diaria de la banda, el sinfín y la tolva.'],
    autoridad=['Pedir al controlador de descarga que detenga un camión si la tolva va llena o la maniobra es peligrosa.', 'Parar la banda si ve concreto con piedras sueltas, pasta segregada o cuerpos extraños, y avisar al laboratorista.',
               'No le toca: aceptar un camión que el laboratorista no liberó.'],
    experiencia=['3 años o más operando colocadora-esparcidora, extendedora o equipo de banda en pavimentos de concreto.',
                 'Experiencia en colados de noche con ritmo continuo de camiones.', 'Deseable: haber trabajado sobre acero corrido o canastillas de pasajuntas.'],
    escolaridad=['Secundaria terminada; saber leer, escribir y hacer cuentas.', 'Constancia de operador de maquinaria pesada vigente.'],
    persona=['Coordina bien con otros: mira al camión, al controlador y a la pavimentadora al mismo tiempo.', 'Paciente con los choferes, firme con las reglas.', 'Mantiene la máquina limpia: una banda con concreto pegado es una banda que se rompe.', 'Avisa temprano cuando el ritmo de camiones cambia.'],
    alertas=['Dice que "se puede echar el concreto directo sobre el acero".', 'No sabe cuánto trae un camión ni cuánto tarda en descargar.', 'Minimiza la limpieza de la máquina.'],
    preguntas=[('Llegan dos camiones juntos y luego ninguno en 6 minutos. ¿Qué haces con la cabeza de concreto?', 'Que reparte parejo, no amontona; avisa al cabo para bajar velocidad y al despachador del hueco.'),
               ('Ves que un camión trae la mezcla con piedra suelta y poca pasta. ¿Qué haces?', 'Que para la banda y avisa al laboratorista; no lo mete a la losa.'),
               ('¿Por qué la colocadora no puede irse muy adelante de la pavimentadora?', 'Porque el concreto se queda esperando, pierde trabajabilidad y se seca antes de entrar al molde.')],
    prueba='Una noche en el tramo de prueba recibiendo al menos 20 camiones. Aprueba si descarga cada camión en 6 minutos o menos, sin derrames sobre el acero, con la cabeza de concreto pareja (el operador de pavimentadora lo confirma) y sin mover sillas ni varillas.',
    indicadores=['Tiempo promedio de descarga por camión: 6 minutos o menos.', 'Cero derrames sobre acero o base.', 'Cero paros de la pavimentadora por falta de reparto.', 'Máquina limpia y revisada al cierre.'],
    dia=[('17:30–18:30', 'Revisas banda, sinfín, tolva e hidráulica con el mecánico.'),
         ('18:30–19:00', 'Colocas la máquina delante de la pavimentadora; acuerdas señales con el controlador de descarga.'),
         ('19:00–05:00', 'Recibes un camión cada 2 minutos y repartes parejo.'),
         ('05:00–05:30', 'Lavado de banda, sinfín y tolva; bitácora de horas y fallas.')],
    saber=['El ritmo: 28 camiones por hora, uno cada 2 minutos, de 8 m³ cada uno. Descarga de 6 minutos por camión como máximo.',
           'La losa lleva 2.27 m³ por metro lineal: un camión de 8 m³ alcanza para unos 3.5 m de avance.',
           'Los camiones descargan desde el carril de al lado hacia la banda lateral. Nunca entran sobre el acero.',
           'El concreto tiene de 60 a 90 minutos desde que se mezcló para quedar colocado. Si espera delante de la pavimentadora, se come ese tiempo.',
           'Concreto segregado (piedras separadas de la pasta) no se mete a la losa: se avisa al laboratorista.',
           'Nadie añade agua al camión para que "corra mejor" por la banda.'],
    numeros=[('2 min', 'un camión en tu tolva'), ('8 m³', 'por camión'), ('≈ 3.5 m', 'de losa por camión'), ('6 min', 'descarga máxima'), ('60–90 min', 'límite del mezclado a la colocación')],
    errores=['Echar concreto sobre el acero y mover las sillas.', 'Amontonar concreto delante de la pavimentadora.', 'Dejar que un chofer añada agua para que baje por la banda.', 'No lavar la banda al final.'],
    capacitacion=[('Días 2 a 5', 'La máquina completa con el mecánico; señales con el controlador de descarga; recorrido del tren.'),
                  ('Semana 2', 'Tramo de prueba: operas con el cabo a un lado; se revisan descargas, derrames y cabeza de concreto.'),
                  ('Primeros 3 meses', 'Certificación de la máquina y 500 horas limpias en bitácora.')],
    certificaciones=['NOM-004-STPS (maquinaria) y NOM-031-STPS (construcción).', 'Certificación de operación de la colocadora con el fabricante.', 'Curso básico de tecnología del concreto: revenimiento, segregación y tiempos.'],
    comprobacion=['¿Cuántos metros de losa salen de un camión de 8 m³?', '¿Por qué los camiones no entran sobre el acero?', '¿Qué haces si llega concreto segregado?'],
    siguiente='Operador de pavimentadora y, después, Cabo de colado.',
)

P['Operador de textura y curado'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Dar la textura y aplicar la membrana de curado a doble dosis inmediatamente detrás de la pavimentadora, sin dejar un solo metro de concreto secándose al aire.',
    importa='Un curado descuidado pierde hasta 40 % de la resistencia y el concreto se ve igual de bien. Este operador protege, en minutos, el trabajo de todo el tren y la vida de la losa.',
    responde=['Seguir a la pavimentadora a la distancia indicada, sin quedarse atrás.',
              'Textura uniforme, a la profundidad y separación indicadas, en toda la superficie.',
              'Membrana de curado a doble dosis, pareja y sin huecos, incluidos los bordes y costados de la losa.',
              'Medir y anotar el consumo de membrana contra los metros cuadrados colados.',
              'Tener lista la protección contra lluvia (plásticos) y avisar si el viento sube.'],
    autoridad=['Pedir al cabo que baje la velocidad del tren si no alcanza a curar a tiempo.', 'Avisar al laboratorista y al residente si la evaporación sube o se acaba la membrana.',
               'No le toca: reducir la dosis de membrana para que alcance ni curar "al final del turno".'],
    experiencia=['2 años o más operando máquina de textura y curado, o equipo de aspersión en pavimentos de concreto.',
                 'Experiencia en colados de noche.', 'Deseable: haber trabajado con curado de doble dosis o en clima seco y ventoso.'],
    escolaridad=['Secundaria terminada; saber leer, escribir y hacer cuentas sencillas (litros por metro cuadrado).', 'Constancia de operador de maquinaria vigente.'],
    persona=['Constante: su trabajo es aburrido y se hace igual en el metro 1 y en el metro 1,000.', 'Revisa con la lámpara lo que ya pasó, no sólo lo que viene.', 'Ordenado con su material: siempre sabe cuánta membrana le queda.', 'Pide ayuda antes de quedarse atrás.'],
    alertas=['Piensa que el curado "es lo de menos".', 'Dice que una sola pasada basta.', 'No sabe cuánto rinde un tambo de membrana.'],
    preguntas=[('Se te tapa una boquilla a las 3 a. m. ¿Qué haces?', 'Avisar para bajar el ritmo, destapar o cambiar la boquilla y volver a curar el tramo que quedó sin membrana.'),
               ('Sube el viento y el laboratorista dice que la evaporación pasa de 0.5 kg/m² por hora. ¿Qué haces?', 'Colocar rompevientos, acercarse más a la pavimentadora y avisar al residente; si no baja, se detiene el colado.'),
               ('¿Cómo sabes que pusiste la dosis correcta?', 'Midiendo litros usados contra metros cuadrados colados y viendo que la membrana blanca cubre parejo.')],
    prueba='Una noche en el tramo de prueba. Aprueba si nunca queda más atrás de lo que marca el residente, si el consumo de membrana medido cumple la doble dosis (del orden de 0.4 L/m², en dos pasadas cruzadas) y si la revisión de la mañana no encuentra huecos ni textura desigual.',
    indicadores=['Metros sin curar a tiempo: cero.', 'Consumo de membrana dentro de la doble dosis en todas las noches.', 'Textura uniforme en la revisión de la mañana.', 'Máquina y boquillas listas al inicio de cada noche.'],
    dia=[('17:30–18:30', 'Revisas boquillas, bombas, peine de textura y tanques; cargas membrana y plásticos.'),
         ('18:30–19:00', 'Pruebas de aspersión en un plástico para ver que todas las boquillas tiran parejo.'),
         ('19:00–05:00', 'Texturas y curas detrás de la pavimentadora; anotas litros usados cada hora.'),
         ('05:00–05:30', 'Curas la cabecera y los costados finales; lavas boquillas y peine.')],
    saber=['Las tres reglas: se cuela de noche, cero agua añadida y el curado empieza de inmediato. La tercera es tuya.',
           'Doble dosis: la membrana se aplica en dos pasadas cruzadas, del orden de 0.4 litros por metro cuadrado en total. Una noche de 1,000 m por 8.40 m son 8,400 m²: unos 3,400 litros.',
           'La membrana pigmentada blanca sirve para ver dónde faltó y para reflejar el sol del día siguiente.',
           'La textura se da con el concreto todavía fresco: surcos parejos, a la separación y profundidad del plano (típico 19 mm de separación y 3 mm de profundidad). Da agarre a las llantas por 50 años.',
           'Evaporación por arriba de 0.5 kg/m² por hora seca la superficie antes de curar; se combate con rompevientos y acercándote a la pavimentadora.',
           'Si llueve, se cubre con plástico lo recién colado. Una losa fresca lavada por la lluvia pierde la superficie.'],
    numeros=[('≈ 0.4 L/m²', 'doble dosis de membrana, en dos pasadas'), ('< 0.5 kg/m²·h', 'evaporación máxima'), ('8,400 m²', 'superficie de una noche de 1,000 m'),
             ('40 %', 'resistencia que se puede perder con un mal curado'), ('19 mm / 3 mm', 'separación y profundidad típicas de la textura')],
    errores=['Quedarse atrás y "curar después".', 'Bajar la dosis para que alcance la membrana.', 'Olvidar los costados y la cabecera.', 'No revisar si todas las boquillas tiran.'],
    capacitacion=[('Días 2 a 5', 'La máquina, las boquillas y la calibración de dosis con el mecánico y el laboratorista. Cálculo de litros por noche.'),
                  ('Semana 2', 'Tramo de prueba: la revisión de cada mañana con el laboratorista te dice si curaste bien.'),
                  ('Primeros 3 meses', 'Curso de curado y evaporación con el Jefe de laboratorio; 500 horas limpias en bitácora.')],
    certificaciones=['NOM-004-STPS (maquinaria) y NOM-031-STPS (construcción).', 'Manejo seguro de sustancias químicas y su hoja de seguridad (NOM-018-STPS).', 'Curso de curado de concreto y cálculo de evaporación.'],
    comprobacion=['¿Cuánta membrana lleva un metro cuadrado a doble dosis?', '¿Qué haces si se tapa una boquilla?', '¿Qué evaporación ya es peligrosa y cómo se combate?'],
    siguiente='Operador de pavimentadora o Cabo de acabado, después de dos años con curado sin faltas.',
)

P['Cuadrilla de acero (fierreros)'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Colocar el acero de la losa dos días antes del colado, a la altura, separación y traslape exactos, sobre sillas firmes, para que el pavimento mantenga sus grietas cerradas durante 50 años.',
    importa='Es la única parte del tren que no se acelera comprando una máquina. Si el acero no está listo, el tren se para esa misma noche; si está mal puesto, la losa se abre en diez años.',
    responde=['Varilla longitudinal #6 cada 15 cm y transversal #4 cada 90 cm, según plano.',
              'Altura: a un tercio del espesor desde arriba, sobre sillas, con 7 cm de recubrimiento mínimo.',
              'Traslapes a la longitud indicada y escalonados, bien amarrados.',
              'Anclajes terminales y acero adicional de cabeceras donde el plano lo marca.',
              'Mantener dos días de acero colocado adelante del tren.'],
    autoridad=['Rechazar varilla doblada, oxidada en exceso o con el recubrimiento protector dañado.', 'Pedir al cabo que no se cuele un tramo si el acero no está revisado.',
               'No le toca: cambiar separaciones o traslapes sin el plano.'],
    experiencia=['2 años o más como fierrero en obra; mejor si fue en losas, puentes o pavimentos.', 'Saber habilitar, amarrar y colocar acero con sillas.',
                 'Deseable: haber colocado acero corrido en pavimento de concreto.'],
    escolaridad=['Primaria terminada; saber leer y medir con flexómetro.', 'Leer un plano sencillo de armado (el cabo lo explica).'],
    persona=['Cuidadoso: mide dos veces antes de amarrar.', 'Aguanta trabajo físico de día bajo el sol, con hidratación.', 'Trabaja en equipo y avisa si alguien se lastima.', 'Respeta el orden del patio de acero.'],
    alertas=['Dice que "a ojo" se pone la separación.', 'Pisa el acero ya colocado como si fuera camino.', 'No conoce el calibre de una varilla por su número.'],
    preguntas=[('¿Cómo sabes que el acero quedó a la altura correcta?', 'Midiendo con flexómetro desde la base en varios puntos y viendo que las sillas estén firmes y completas.'),
               ('¿Qué pasa si todos los traslapes quedan en la misma línea?', 'Que se hace un punto débil; los traslapes se escalonan.'),
               ('Llega varilla con la capa protectora raspada. ¿Qué haces?', 'Separarla y avisar al cabo; no se coloca sin reparar el recubrimiento.')],
    prueba='Medio día armando 10 metros de acero de losa con la cuadrilla. Aprueba si la separación longitudinal queda en 15 cm ±1 cm, la altura dentro de ±1.3 cm, los traslapes completos y escalonados y ninguna silla suelta al pisar con cuidado la zona permitida.',
    indicadores=['Días de acero colocado adelante del tren: 2 o más.', 'Tramos liberados por Calidad a la primera revisión.', 'Cero paros del tren por acero.', 'Cero accidentes con tiempo perdido (cortes, golpes, cargas).'],
    dia=[('06:30', 'Plática de seguridad y reparto de tramos con tu encargado; hidratación lista.'),
         ('07:00–13:00', 'Habilitado y colocación de acero dos días adelante del colado. Sillas primero, luego varilla longitudinal, luego transversal.'),
         ('13:00–14:00', 'Comida a la sombra.'),
         ('14:00–17:00', 'Amarres, traslapes, anclajes y revisión con cinta. Entregas el tramo al cabo.'),
         ('Antes de salir', 'Material ordenado y cubierto; herramienta guardada.')],
    saber=['El acero de la losa ocupa 0.70 % del área: varilla #6 (19 mm) cada 15 cm a lo largo, y #4 (12.7 mm) cada 90 cm a lo ancho.',
           'Altura: la losa mide 27 cm; el acero va a un tercio desde arriba (unos 9 cm), con 7 cm de recubrimiento mínimo. Si queda bajo, las grietas se abren; si queda alto, se oxida.',
           'Traslapes: mínimo 25 diámetros (unos 50 cm para varilla #6), amarrados, y escalonados para que nunca más de un tercio de las varillas se empalme en la misma sección.',
           'Anclajes terminales en los extremos y accesos: sin ellos el pavimento camina. No son opcionales.',
           'El acero protegido (galvanizado o revestido) se maneja con cuidado: un raspón es por donde empieza la corrosión.',
           'Hombro amarrado con varilla #4 cada 75 cm. El acero se coloca dos días antes del colado, nunca la misma noche.'],
    numeros=[('#6 cada 15 cm', 'acero a lo largo'), ('#4 cada 90 cm', 'acero a lo ancho'), ('≈ 9 cm', 'profundidad del acero desde arriba (un tercio de 27)'),
             ('7 cm', 'recubrimiento mínimo'), ('25 diámetros', 'traslape mínimo'), ('2 días', 'adelante del tren, siempre')],
    errores=['Dejar sillas sueltas o chuecas: el acero se baja con el paso de la máquina.', 'Traslapes en la misma línea.', 'Raspar el acero protegido.', 'Ir al día con el acero.'],
    capacitacion=[('Días 2 a 5', 'Plano de armado, separaciones, alturas y traslapes con el cabo; práctica en el patio.'),
                  ('Semana 2', 'Tramo de prueba: armas junto a fierreros con experiencia y Calidad revisa cada tramo.'),
                  ('Primeros 3 meses', 'Curso de seguridad en manejo de cargas y de lectura de planos de armado.')],
    certificaciones=['NOM-031-STPS (construcción), NOM-017-STPS (equipo de protección) y NOM-006-STPS (manejo de materiales y cargas).', 'Estándar de competencia CONOCER de habilitado y armado de acero de refuerzo, cuando aplique.', 'Señales con el manipulador telescópico.'],
    comprobacion=['¿Cada cuánto va la varilla #6 y a qué altura?', '¿Cuánto mide un traslape de #6 y por qué se escalona?', '¿Por qué el acero va dos días adelante?'],
    siguiente='Encargado de la cuadrilla de acero y, después, Cabo de colado.',
    pedimos=['Usar siempre guantes, lentes y protección en las puntas de varilla expuestas.'],
)

P['Acabador'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Corregir a mano, desde la pasarela, los bordes, orillas y detalles que la pavimentadora no deja perfectos, sin añadir agua y sin trabajar de más la superficie.',
    importa='La máquina hace 95 % del trabajo; el acabador cuida el 5 % que se nota y el que se rompe primero: orillas, cabeceras y puntos donde el concreto no cerró.',
    responde=['Revisar la superficie detrás de la pavimentadora y corregir sólo donde hace falta.',
              'Bordes y orillas a plomo, sin caída ni huecos.',
              'La cabecera de fin de colado y las esquinas, vibradas y acabadas.',
              'Trabajar siempre desde la pasarela, sin pisar la losa fresca.',
              'Avisar al cabo y al laboratorista si la mezcla no deja acabar.'],
    autoridad=['Avisar que la máquina está dejando un defecto repetido para que se corrija desde la máquina.', 'Negarse a acabar con agua aunque se lo pidan.',
               'No le toca: cambiar la textura o el curado.'],
    experiencia=['2 años o más como acabador de concreto; mejor en pavimentos, pisos industriales o losas grandes.', 'Manejo de llana de mango largo, llana de borde y regla.',
                 'Deseable: experiencia en colados con pavimentadora de cimbra deslizante.'],
    escolaridad=['Primaria terminada; saber leer y escribir.'],
    persona=['Mano firme y paciencia.', 'Sabe cuándo dejar de tocar la superficie.', 'Orgulloso de su trabajo, sin necesitar que lo vean.', 'Aguanta la noche sin bajar el cuidado.'],
    alertas=['Dice que el agua "ayuda a cerrar" la superficie.', 'Presume de que "a mano queda mejor que con máquina".', 'No conoce la pasarela o dice que se puede pisar la losa.'],
    preguntas=[('La superficie no cierra y un compañero rocía agua. ¿Qué haces?', 'Detenerlo, avisar al cabo y al laboratorista; el agua en la superficie deja una capa débil que se descascara.'),
               ('¿Por qué no se trabaja de más la superficie?', 'Porque sube la pasta y el agua a la superficie y la debilita; además rompe las burbujas de aire que la protegen de la helada.'),
               ('¿Cómo corriges una orilla caída?', 'Con concreto de la misma mezcla, vibrado y llana de borde; y avisando para que se corrija en la máquina.')],
    prueba='Una noche en el tramo de prueba como acabador de apoyo. Aprueba si no añade agua en ningún momento, si no pisa la losa, si las orillas y la cabecera que acabó salen a plomo y sin huecos en la revisión de la mañana, y si trabaja la superficie sólo donde hace falta.',
    indicadores=['Cero casos de agua añadida.', 'Orillas y cabeceras aceptadas por Calidad.', 'Cero pisadas en losa fresca.', 'Asistencia completa.'],
    dia=[('18:00', 'Lista con el cabo, equipo y herramienta limpia.'),
         ('18:30–19:00', 'Pasarela colocada; plática de seguridad.'),
         ('19:00–05:00', 'Detrás de la pavimentadora, desde la pasarela: orillas, bordes, detalles. Descansos rotados.'),
         ('05:00–05:30', 'Cabecera de fin de colado con el cabo; lavado de herramienta.')],
    saber=['Nunca se añade agua: ni al camión, ni a la superficie. Una cubeta sube la permeabilidad de ese tramo cincuenta años.',
           'El concreto lleva aire incluido de 5 a 7 % para aguantar la helada de Torreón. Trabajar de más la superficie rompe esas burbujas justo donde más se necesitan.',
           'La losa mide 27 cm y 8.40 m de ancho; la orilla debe quedar a plomo porque es el borde que carga el hombro.',
           'La textura y la membrana vienen justo detrás de ti: si te atrasas, la superficie se seca al aire.',
           'La pasarela existe para no pisar la losa. Una huella en concreto fresco es un defecto para siempre.'],
    numeros=[('0', 'cubetas de agua, nunca'), ('5–7 %', 'aire incluido que no hay que romper'), ('27 cm', 'espesor de la orilla'), ('< 0.5 kg/m²·h', 'evaporación: si sube, la superficie se seca antes de curar')],
    errores=['Echar agua para cerrar la superficie.', 'Trabajar de más la superficie.', 'Pisar la losa en vez de usar la pasarela.', 'Tapar un defecto repetido en vez de avisar que viene de la máquina.'],
    capacitacion=[('Días 2 a 5', 'Con el cabo: pasarela, herramienta, orillas y cabeceras; por qué no se usa agua.'),
                  ('Semana 2', 'Tramo de prueba junto a un acabador con experiencia; revisión de la mañana con el laboratorista.'),
                  ('Primeros 3 meses', 'Curso de seguridad y calidad del tramo de prueba.')],
    certificaciones=['NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Estándar de competencia CONOCER en acabado de concreto, cuando aplique.', 'Curso básico de concreto para pavimento: aire, agua y curado.'],
    comprobacion=['¿Por qué no se echa agua a la superficie?', '¿Qué le pasa al aire incluido si trabajas de más la superficie?', '¿Desde dónde se trabaja la losa fresca?'],
    siguiente='Operador de textura y curado o encargado de acabadores, y después Cabo de acabado.',
)

P['Controlador de descarga'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Recibir y acomodar un camión cada 2 minutos en la colocadora, sin derrames, sin agua añadida y con el ticket revisado, para que el tren no espere ni un minuto.',
    importa='Es donde se juntan la logística y el tren. Un camión mal acomodado cuesta minutos; uno con agua añadida que pasa sin que nadie lo vea cuesta 50 años.',
    responde=['Guiar cada camión en reversa hasta la tolva de la colocadora con señales claras.',
              'Revisar el ticket: hora de mezclado, número de camión y metros cúbicos.',
              'Que ningún chofer añada agua ni se desvíe; avisar al laboratorista antes de descargar cada camión.',
              'Registrar la hora de llegada y de salida de cada camión.',
              'Mantener limpia la zona de descarga y ordenado el lavado de canales lejos de la losa.'],
    autoridad=['Detener la maniobra de un camión si hay alguien en la zona de reversa.', 'Retener un camión con ticket vencido o con agua añadida y llamar al laboratorista.',
               'Avisar al despachador de cualquier chofer que no respete las reglas.', 'No le toca: aceptar o rechazar un camión (eso lo decide el laboratorista).'],
    experiencia=['1 año o más como señalero de maniobras, checador de camiones o ayudante en obra de concreto.', 'Haber trabajado de noche con tráfico de camiones.'],
    escolaridad=['Secundaria terminada; saber leer, escribir y anotar horas.', 'Usar radio y tableta o bitácora.'],
    persona=['Firme y respetuoso con los choferes.', 'No se distrae: su trabajo son dos minutos que se repiten 300 veces.', 'Se coloca siempre donde el chofer lo ve por el espejo.', 'Anota todo, aunque parezca que nadie lo revisa.'],
    alertas=['Le parece normal que los choferes "ajusten" la mezcla con agua.', 'Da señales desde atrás del camión.', 'No sabe leer un ticket de concreto.'],
    preguntas=[('Llega un camión cuyo ticket dice que se mezcló hace 85 minutos. ¿Qué haces?', 'Retenerlo y avisar al laboratorista antes de que descargue; el límite es de 60 a 90 minutos y menos con calor.'),
               ('Ves que el chofer abre la llave de agua del camión. ¿Qué haces?', 'Detenerlo, avisar al laboratorista y al despachador; ese camión no descarga hasta que Calidad decida.'),
               ('¿Dónde te colocas para guiar una reversa?', 'A un lado, a la vista del espejo del chofer, nunca detrás del camión.')],
    prueba='Una noche en el tramo de prueba con el controlador titular. Aprueba si guía al menos 20 camiones sin un solo derrame, registra la hora de todos, detecta los tickets fuera de tiempo que se le presenten y nunca se coloca detrás de un camión en reversa.',
    indicadores=['Camiones registrados con hora y ticket: 100 %.', 'Tiempo de acomodo por camión: 1 minuto o menos.', 'Cero camiones descargados sin aviso al laboratorista.', 'Cero incidentes en maniobras.'],
    dia=[('18:00', 'Lista, equipo reflejante, lámpara de señales y radio.'),
         ('18:30–19:00', 'Marcas la zona de descarga y la ruta de reversa con conos; acuerdas señales con la colocadora.'),
         ('19:00–05:00', 'Un camión cada 2 minutos: ticket, aviso al laboratorista, reversa, descarga, salida y registro.'),
         ('05:00–05:30', 'Entregas el registro al cabo y el conteo al despachador; limpias la zona.')],
    saber=['28 camiones por hora, uno cada 2 minutos. Carga 6 min, descarga 6 min, maniobra 5 min: tú cuidas la maniobra y la descarga.',
           'El concreto se coloca dentro de 60 a 90 minutos desde su mezclado; en el tablero, el peor camión de la noche no debe pasar de 75 minutos.',
           'El chofer responde al despachador de la obra, no a su patrón. Si un chofer no obedece, se reporta.',
           'El laboratorista prueba cada camión: temperatura (30 °C máximo), revenimiento y aire. Ningún camión descarga sin que él lo vea.',
           'El agua de lavado del canal nunca cae sobre el acero, la base o la losa.'],
    numeros=[('2 min', 'entre camión y camión'), ('8 m³', 'por camión'), ('≤ 75 min', 'mezclado a colocación, el peor de la noche'), ('60–90 min', 'límite absoluto del concreto'), ('≤ 30 °C', 'temperatura del concreto en la descarga')],
    errores=['Dejar descargar un camión sin avisar al laboratorista.', 'Hacerse de la vista gorda con el agua.', 'Pararse detrás de un camión en reversa.', 'No anotar las horas.'],
    capacitacion=[('Días 2 a 5', 'Con el despachador y el laboratorista: el ticket, los tiempos, las señales y la cláusula de mando.'),
                  ('Semana 2', 'Tramo de prueba junto a un controlador con experiencia.'),
                  ('Primeros 3 meses', 'Curso de maniobras seguras y de señales con camiones pesados.')],
    certificaciones=['NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Señales de maniobra con vehículos pesados.', 'Curso básico de concreto fresco: tiempos y temperatura.'],
    comprobacion=['¿Cuánto tiempo máximo puede tener un camión desde que se mezcló?', '¿Qué haces si ves que un chofer añade agua?', '¿Dónde te colocas en una reversa?'],
    siguiente='Despachador de camiones, u operador de colocadora con la certificación de la máquina.',
)

P['Señalero · control de tránsito'] = dict(
    linea='Seguridad', reporta='Seguridad e higiene', esquema='seguridad',
    mision='Proteger a la cuadrilla y a los automovilistas en un frente nocturno abierto al tránsito, con señalamiento completo, desvíos claros y control de cada vehículo que se acerca.',
    importa='Un frente de colado de noche junto a un carril abierto es uno de los lugares más peligrosos de toda la obra. El señalero es lo único que hay entre un tráiler con sueño y 34 personas trabajando.',
    responde=['Colocar, revisar y retirar el señalamiento del plan de tránsito autorizado, en su orden.',
              'Controlar el paso de vehículos con paleta o bastón luminoso cuando se necesita.',
              'Vigilar la entrada y salida de camiones de concreto al carril de trabajo.',
              'Reportar de inmediato cualquier señal caída, dañada o apagada, y cualquier incidente o casi-accidente.',
              'Que ninguna persona de la cuadrilla cruce el carril abierto.'],
    autoridad=['Detener el tránsito o el trabajo si hay peligro, sin pedir permiso.', 'Pedir a cualquier persona de la obra que salga de la zona de riesgo.',
               'No le toca: dejar su puesto sin relevo, ni cambiar el plan de desvíos por su cuenta.'],
    experiencia=['1 año o más como banderero o señalero en carreteras abiertas al tránsito.', 'Haber trabajado turnos de noche.',
                 'Deseable: experiencia en obras de autopista con desvíos de carril.'],
    escolaridad=['Secundaria terminada; saber leer y escribir.', 'Usar radio con claridad.'],
    persona=['Alerta todo el turno: no se sienta ni se distrae con el teléfono.', 'Se hace ver: siempre con su equipo reflejante y su luz.', 'Tranquilo ante conductores enojados.', 'Reporta todo, aunque parezca poco.'],
    alertas=['Dice que el señalamiento "se puede poner a la mitad" si hay poco tráfico.', 'Se para de espaldas al tránsito.', 'Ha dejado su puesto sin relevo antes.'],
    preguntas=[('Un auto viene muy rápido y no baja la velocidad al acercarse a tu zona. ¿Qué haces?', 'Ponerse a salvo por su ruta de escape y avisar por radio a toda la cuadrilla; nunca atravesarse.'),
               ('A las 3 a. m. ves que un cono con luz se cayó y un tambo está apagado. ¿Qué haces?', 'Reportarlo por radio, reponerlo con un compañero y con protección; el señalamiento se revisa toda la noche.'),
               ('¿Dónde te colocas?', 'De frente al tránsito, visible desde lejos, con una ruta de escape libre, nunca dentro del carril abierto.')],
    prueba='Una noche con el señalero titular: coloca y retira el señalamiento completo de un desvío según el plan y controla el paso de vehículos durante 2 horas. Aprueba si el señalamiento queda en su orden y distancias, nunca da la espalda al tránsito y todos sus reportes por radio son claros.',
    indicadores=['Cero accidentes e incidentes con terceros en su zona.', 'Señalamiento completo en cada revisión de Seguridad e higiene.', 'Reportes de casi-accidentes el mismo día.', 'Asistencia puntual: el señalamiento se pone antes de las 19:00.'],
    dia=[('17:30', 'Recibes el plan de tránsito de la noche de Seguridad e higiene; revisas conos, trafitambos, flechas y lámparas.'),
         ('18:00–19:00', 'Colocas el señalamiento en su orden, desde lejos hacia la obra, con protección de vehículo.'),
         ('19:00–05:00', 'Controlas tránsito y entrada de camiones; revisas el señalamiento cada hora.'),
         ('05:00–06:00', 'Retiras el señalamiento en orden inverso cuando el frente ya está protegido; entregas reporte.')],
    saber=['El señalamiento en obra sigue la NOM-086-SCT2 (señalamiento y dispositivos para protección en zonas de obras viales): aviso previo, transición, zona de trabajo y fin de obra.',
           'De noche todo es reflejante y luminoso: chaleco clase 3, bastón o paleta luminosa, lámpara, conos y trafitambos con reflejante y flechas luminosas.',
           'Un camión de concreto llega cada 2 minutos: veintiocho entradas por hora al carril de trabajo. Cada entrada es un momento de riesgo.',
           'Siempre de frente al tránsito, visible, con una ruta de escape. Nunca dentro del carril abierto.',
           'Cualquiera detiene el trabajo por seguridad, sin consecuencias. Tú eres el primero que debe hacerlo.'],
    numeros=[('4', 'señaleros por noche en el frente de colado'), ('28', 'entradas de camiones por hora'), ('Clase 3', 'chaleco de alta visibilidad de noche'), ('19:00', 'el señalamiento ya está completo')],
    errores=['Dar la espalda al tránsito.', 'Dejar el puesto sin relevo.', 'Poner el señalamiento incompleto "porque hay poco tráfico".', 'No reportar un casi-accidente.'],
    capacitacion=[('Días 2 a 5', 'Con Seguridad e higiene: plan de tránsito, NOM-086-SCT2, señales con paleta y bastón, rutas de escape. Recorrido del desvío de noche.'),
                  ('Semana 2', 'Tramo de prueba junto a un señalero titular.'),
                  ('Primeros 3 meses', 'Curso de banderero certificado y primeros auxilios.')],
    certificaciones=['Curso de señalamiento en obra vial según NOM-086-SCT2.', 'NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).',
                     'Primeros auxilios y brigada de emergencia.', 'Estándar de competencia CONOCER en seguridad (p. ej. EC0391), cuando aplique.'],
    comprobacion=['¿En qué orden se coloca el señalamiento de un desvío?', '¿Dónde te colocas y por dónde escapas?', '¿Qué haces si una señal se cae a media noche?'],
    siguiente='Auxiliar de Seguridad e higiene y, con certificación, responsable de seguridad de un frente.',
)

P['Operador de planta'] = dict(
    linea='Logística', reporta='Jefe de planta', esquema='frente',
    mision='Producir concreto a 227 m³ por hora, dentro de especificación y a 30 °C o menos, alimentando y operando la planta y el cargador sin una sola interrupción.',
    importa='Un camión rechazado en el frente casi siempre nació mal en la planta. Aquí se decide la temperatura, el agua y la humedad de cada bachada, antes de que nadie la vea.',
    responde=['Alimentar las tolvas con el cargador sin contaminar el agregado y sin vaciar los acopios.',
              'Operar la dosificación según la fórmula del laboratorio, con la humedad de los agregados corregida.',
              'Agua con hielo o enfriada, agregado sombreado y prehumedecido: concreto a 30 °C o menos.',
              'El ticket de cada camión con hora de mezclado, volumen y temperatura.',
              'Revisar bandas, básculas y silos antes y durante el turno; reportar niveles de cemento y ceniza.'],
    autoridad=['Detener la producción si una báscula falla o un silo se vacía, y avisar al Jefe de planta.', 'No cargar un camión si la temperatura del concreto sale arriba de 30 °C.',
               'No le toca: cambiar la fórmula ni añadir agua para corregir revenimiento.'],
    experiencia=['3 años o más operando planta central de concreto (premezclado o de obra) de más de 100 m³/h.', 'Manejo de cargador frontal para alimentación de tolvas.',
                 'Deseable: experiencia con concreto enfriado con hielo y con plantas móviles.'],
    escolaridad=['Secundaria terminada; bachillerato técnico deseable.', 'Manejo de la computadora de dosificación y de cuentas de peso y humedad.', 'Licencia o constancia de operador de cargador.'],
    persona=['Disciplinado con la fórmula: no improvisa.', 'Mide antes de ajustar.', 'Cuida la limpieza del patio: el agregado contaminado es concreto malo.', 'Comunica al despachador cada retraso de inmediato.'],
    alertas=['Dice que el revenimiento "se ajusta con agua en la planta".', 'No sabe corregir la dosificación por humedad del agregado.', 'Ve normal trabajar la planta al 100 % toda la noche.'],
    preguntas=[('La arena llega más mojada que ayer. ¿Qué haces con la dosificación?', 'Medir su humedad y restar esa agua del agua de mezclado; si no, sube el agua/cementante.'),
               ('El concreto sale a 31 °C. ¿Qué haces?', 'No cargar, avisar al Jefe de planta, más hielo o agua más fría, sombrear y prehumedecer agregado; nunca corregir en el frente.'),
               ('¿Qué le pasa a la mezcla si la pómez para curado interno entra seca?', 'Que en vez de dar agua, la roba; se pierde el curado interno.')],
    prueba='Un turno de 4 horas con el Jefe de planta en la prueba continua de la planta (o en el tramo de prueba). Aprueba si todas las bachadas salen dentro de la fórmula, con la corrección por humedad bien hecha, a 30 °C o menos, y si el volumen producido queda dentro de ±3 % de lo teórico.',
    indicadores=['m³ producidos contra teóricos: ±3 %.', 'Camiones rechazados por causa de planta: cero.', 'Temperatura del concreto a la salida: 30 °C o menos.', 'Minutos de paro de la planta por operación: cero.'],
    dia=[('16:00', 'Arranque de la planta con el Jefe de planta: niveles de silos, humedad de agregados, temperatura del agua, hielo.'),
         ('17:00–19:00', 'Revolturas de prueba; el laboratorio las revisa antes de mandar el primer camión.'),
         ('19:00–05:00', 'Producción continua: 227 m³ por hora. Corriges humedad cada vez que cambia el acopio.'),
         ('05:00–06:00', 'Lavado de la mezcladora, cierre de tickets y niveles de silos para el turno de día.')],
    saber=['La mezcla: 320–350 kg/m³ de cementante con 20–25 % de ceniza volante clase F, agua/cementante 0.42 o menos, aire 5–7 %, revenimiento 3–5 cm con superfluidificante.',
           'Curado interno: pómez o tezontle presaturado, 20–25 % de la arena. Se mide su humedad en cada bachada; si entra seco, roba agua.',
           'La planta tiene 250–280 m³/h instalados y trabaja a 227: nunca al 100 %, porque al 100 % falla la primera noche caliente.',
           'Silos con autonomía de 2 días de colado. Si un silo baja del mínimo, se avisa de día, no a media noche.',
           'La planta salta cada 15–20 km para quedar a menos de 10 km del colado; después de cada salto se prueba 4 horas continuas antes de producir para la losa.',
           'El cargador toma el agregado sin arrastrar tierra del piso y sin mezclar acopios.'],
    numeros=[('227 m³/h', 'producción sostenida'), ('250–280 m³/h', 'capacidad instalada'), ('≤ 30 °C', 'temperatura del concreto'), ('≤ 0.42', 'agua/cementante'),
             ('2 días', 'autonomía de silos'), ('± 3 %', 'm³ producidos contra teóricos')],
    errores=['No corregir la humedad del agregado.', 'Mandar un camión caliente "porque el frente está esperando".', 'Dejar que el silo se vacíe a media noche.', 'Contaminar el agregado con el cargador.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de planta: fórmula, computadora de dosificación, corrección por humedad, hielo y calibración de básculas.'),
                  ('Semana 2', 'Tramo de prueba: produces con el Jefe de planta al lado y el laboratorio revisando cada bachada.'),
                  ('Primeros 3 meses', 'Curso de tecnología del concreto con el Jefe de laboratorio; certificación del cargador.')],
    certificaciones=['NOM-004-STPS (maquinaria) y NOM-031-STPS (construcción).', 'NOM-009-STPS (trabajos en altura) para revisar silos y tolvas.', 'Curso de operación de planta dosificadora y de tecnología del concreto.'],
    comprobacion=['¿Cómo corriges el agua si la arena viene mojada?', '¿Por qué la planta no trabaja al 100 %?', '¿Qué haces si el concreto sale arriba de 30 °C?', '¿Cuántos días de autonomía deben tener los silos?'],
    siguiente='Jefe de planta, después de dos años con cero rechazos por causa de planta.',
)

P['Laboratorista de turno'] = dict(
    linea='Calidad', reporta='Jefe de laboratorio', esquema='calidad',
    mision='Probar cada camión que llega al frente, medir la evaporación de la noche y rechazar sin pedir permiso todo concreto que no cumpla la especificación.',
    importa='Es el puesto donde la calidad se decide a las 3 de la mañana. Por eso reporta al Jefe de laboratorio y no al superintendente: su rechazo se sostiene solo.',
    responde=['Temperatura de cada camión y revisión de su ticket (hora de mezclado).',
              'Revenimiento y aire en los camiones que marca el plan de control, y siempre que un camión se vea distinto.',
              'Vigas para resistencia a flexión y su curado inicial, con su registro completo.',
              'La tasa de evaporación en vivo desde la estación del frente, y el aviso cuando se acerca a 0.5 kg/m² por hora.',
              'El registro en tableta de todos los ensayos y rechazos, con su causa, listo a las 05:00.'],
    autoridad=['Rechazar un camión fuera de especificación, sin pedir permiso a nadie.', 'Pedir que se detenga el colado por evaporación, temperatura o concreto fuera de rango, y avisar al Jefe de laboratorio.',
               'Pedir a la planta que corrija antes del siguiente camión.', 'No le toca: dejar pasar un camión por presión del frente ni corregir el concreto en el frente con agua.'],
    experiencia=['2 años o más como laboratorista de concreto en obra o en planta premezcladora.', 'Haber hecho pruebas de revenimiento, aire, temperatura y vigas con procedimiento escrito.',
                 'Deseable: haber rechazado camiones en un colado de pavimento o de obra grande.'],
    escolaridad=['Bachillerato o técnico en laboratorio, construcción o química.', 'Certificación de técnico de campo en concreto (ACI Grado I) o disposición a obtenerla en los primeros 3 meses.'],
    persona=['Firme y tranquilo: rechaza sin pelear.', 'Registra todo con hora, aunque nadie lo pida.', 'No se deja apurar: una prueba mal hecha vale menos que ninguna.', 'Explica la razón del rechazo con el número en la mano.'],
    alertas=['Dice que "si el frente está esperando, se deja pasar uno".', 'No recuerda nunca haber rechazado un camión.', 'Hace las pruebas "de memoria", sin procedimiento.', 'Busca quedar bien con el cabo o el residente.'],
    preguntas=[('Son las 3 a. m., el camión llega a 32 °C y el residente te pide dejarlo pasar. ¿Qué haces?', 'Rechazarlo, registrar la causa, avisar a la planta y al Jefe de laboratorio. No se discute.'),
               ('El aire sale en 4 %. ¿Qué haces?', 'Repetir la prueba; si confirma, rechazar el camión y avisar a planta para que corrija el aditivo.'),
               ('¿Cómo calculas la evaporación en el frente?', 'Con temperatura del aire y del concreto, humedad relativa y viento de la estación meteorológica, con el nomograma o la fórmula del procedimiento.'),
               ('¿A quién le reportas?', 'Al Jefe de laboratorio. Ni al cabo ni al residente.')],
    prueba='Prueba en el laboratorio de campo de 3 horas: hacer revenimiento, aire por método de presión, temperatura y colado de dos vigas siguiendo la norma, con el Jefe de laboratorio observando. Después, rechazar o aceptar cinco camiones simulados con datos (temperatura, ticket, aire). Aprueba si los procedimientos siguen la norma paso a paso y las cinco decisiones son correctas.',
    indicadores=['Camiones con temperatura y ticket revisados: 100 %.', 'Cero camiones aceptados fuera de especificación.', 'Registro de la noche completo en tableta a las 05:00.', 'Vigas bien curadas: cero vigas descartadas por mal manejo.'],
    dia=[('16:00–17:00', 'Recibes el turno del Jefe de laboratorio; calibras equipo; revisas el pronóstico de la noche.'),
         ('17:00–19:00', 'Pruebas de las revolturas de prueba en planta; libera o no el primer camión.'),
         ('19:00–05:00', 'Cada camión: ticket y temperatura. Revenimiento y aire según el plan. Vigas. Evaporación cada hora o cuando cambie el viento.'),
         ('05:00–06:00', 'Cierras el registro, llevas vigas al curado y entregas al Jefe de laboratorio.')],
    saber=['Los límites de la noche: concreto a 30 °C o menos; revenimiento 3–5 cm; aire 5–7 %; agua/cementante 0.42 o menos; del mezclado a la colocación 60–90 minutos, y el peor camión del turno no debe pasar de 75.',
           'Evaporación: por arriba de 0.5 kg/m² por hora se combate con rompevientos y curado inmediato; si no baja, se recomienda no colar. La estación meteorológica del frente da los datos.',
           'Resistencia: MR 48 kg/cm² a 28 días en vigas; también se miden a 90 días. Una viga mal curada miente.',
           'Un camión rechazado cuesta 8 m³; un camión aceptado mal cuesta 50 años.',
           'El pómez del curado interno debe entrar saturado; si la mezcla viene seca y dura sin explicación, pregunta a planta por la humedad del pómez.',
           'Procedimientos: muestreo (NMX-C-161), revenimiento (NMX-C-156), aire por presión (NMX-C-157), especímenes (NMX-C-159), flexión en vigas (NMX-C-191) y temperatura (ASTM C1064).'],
    numeros=[('≤ 30 °C', 'temperatura en la descarga'), ('3–5 cm', 'revenimiento'), ('5–7 %', 'aire incluido'), ('≤ 75 min', 'peor tiempo mezclado a colocación'),
             ('< 0.5 kg/m²·h', 'evaporación'), ('MR 48', 'kg/cm² a 28 días')],
    errores=['Dejar pasar un camión "sólo esta vez".', 'Hacer una prueba sin procedimiento o con equipo sin calibrar.', 'Dejar las vigas al sol o moverlas en las primeras horas.', 'Reportar de palabra y no en el registro.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de laboratorio: plan de control, procedimientos, equipo, tableta y criterios de rechazo.'),
                  ('Semana 2', 'Tramo de prueba: pruebas cada camión junto a un laboratorista con experiencia.'),
                  ('Semanas 3 y 4', 'Turnos solos con revisión diaria de tu registro por el Jefe de laboratorio.'),
                  ('Primeros 3 meses', 'Certificación ACI Grado I pagada por la empresa; curso de evaporación y madurez.')],
    certificaciones=['ACI Concrete Field Testing Technician Grade I.', 'Normas NMX-C del ONNCCE para concreto fresco y especímenes.', 'NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Método de madurez y sensores embebidos.'],
    comprobacion=['¿Qué cuatro cosas revisas en cada camión antes de aceptarlo?', '¿Qué haces si la evaporación pasa de 0.5 kg/m² por hora?', '¿Cuánto tiempo máximo puede tener un camión y cuál es la meta del tablero?', '¿A quién reportas, y a quién no?'],
    siguiente='Laboratorista de día o de núcleos y, con estudios, Jefe de laboratorio.',
)

P['Mecánico de turno'] = dict(
    linea='Logística', reporta='Jefe de mantenimiento', esquema='frente',
    mision='Vivir en el frente durante el colado y reparar en minutos cualquier falla del tren, para que una avería de 20 minutos no se convierta en una noche perdida.',
    importa='La diferencia entre una falla de 20 minutos y una noche perdida es que alguien con herramienta esté a 100 metros, no a 40 kilómetros. Una hora de paro cuesta el 10 % de la producción del día.',
    responde=['Revisión de arranque de las máquinas del tren con cada operador antes de las 19:00.',
              'Atención inmediata de fallas de hidráulica, vibradores, bandas, boquillas y sensores durante el colado.',
              'El taller móvil completo y las refacciones críticas en el frente.',
              'La bitácora de horas y fallas de cada máquina, entregada al Jefe de mantenimiento a las 05:00.',
              'Aplicar el plan escrito de falla a las 2 a. m. de cada máquina crítica.'],
    autoridad=['Detener una máquina si su falla pone en riesgo a alguien o a la losa.', 'Aplicar bloqueo y etiquetado antes de cualquier reparación.',
               'Pedir refacciones o apoyo al Jefe de mantenimiento a cualquier hora.', 'No le toca: decidir si se reanuda el colado; informa y el residente decide.'],
    experiencia=['5 años o más como mecánico de maquinaria pesada, con hidráulica y electrónica de control.', 'Deseable: experiencia con pavimentadoras, extendedoras o plantas de concreto.',
                 'Haber trabajado reparaciones de campo con presión de tiempo.'],
    escolaridad=['Técnico en mecánica diésel, hidráulica o mecatrónica, o secundaria con oficio comprobado.', 'Leer diagramas hidráulicos y eléctricos y códigos de falla.'],
    persona=['Rápido pero ordenado: diagnostica antes de desarmar.', 'Tiene su taller y su camioneta siempre listos.', 'Anota todo en la bitácora.', 'Trabaja bien de noche y bajo presión.'],
    alertas=['Sólo ha trabajado en taller, nunca en campo.', 'No lleva bitácora ni sabe qué es mantenimiento por horas.', 'Se salta el bloqueo "porque es rápido".'],
    preguntas=[('A las 2 a. m. la pavimentadora pierde presión hidráulica. ¿Qué haces primero?', 'Asegurar la máquina, bloqueo y etiquetado, diagnóstico con el operador, estimar tiempo y avisar al cabo y al residente; luego reparar con las refacciones del sitio.'),
               ('¿Cuáles son las cuatro máquinas que no tienen sustituto a media noche?', 'La planta, la pavimentadora, la enfriadora de agua y la máquina de textura y curado.'),
               ('¿Por qué se cambia una manguera antes de que falle?', 'Porque el mantenimiento se hace por horas, de día, y no por falla, de noche.')],
    prueba='Prueba de 3 horas en el patio: diagnosticar y resolver tres fallas preparadas (hidráulica, sensor de control y boquilla o banda) en una máquina del tren, aplicando bloqueo y etiquetado. Aprueba si resuelve al menos dos en el tiempo marcado, no omite el bloqueo en ninguna y registra todo en la bitácora.',
    indicadores=['Minutos de paro del tren por falla mecánica: el menor posible, con causa registrada.', 'Tiempo promedio de reparación en el frente.', 'Bitácora completa cada noche.', 'Cero accidentes en reparaciones.'],
    dia=[('17:30–19:00', 'Revisión de arranque con cada operador: hidráulica, vibradores, bandas, boquillas, sensores. Inventario de refacciones en el taller móvil.'),
         ('19:00–05:00', 'A menos de 100 m del tren, con radio. Atiendes fallas y haces revisiones rápidas en los momentos tranquilos.'),
         ('05:00', 'Entregas bitácora y pendientes al Jefe de mantenimiento; el equipo de madrugada hace las reparaciones mayores.'),
         ('06:00', 'Junta de cierre si hubo paro mecánico.')],
    saber=['Las fallas mecánicas más comunes del tren son hidráulica, sensores del control 3D y vibradores. Son la quinta causa de paro.',
           'Mantenimiento preventivo por horas: la bitácora dice qué cambia antes del límite. De día se repara; de noche sólo se atienden emergencias.',
           'Las cuatro máquinas críticas tienen un plan escrito de qué hacer si fallan a las 2 a. m.; conócelo de memoria.',
           'Refacciones críticas en sitio: bandas, mangueras, sensores, bombas, boquillas, según el manual de cada máquina.',
           'El camión de combustible surte en el frente: ninguna máquina sale a cargar.',
           'Si la pavimentadora se detiene, el cabo baja el ritmo; tu estimado de tiempo le dice al residente qué decidir.'],
    numeros=[('100 m', 'distancia máxima del tren durante el colado'), ('20 min', 'meta de una reparación en el frente'), ('4', 'máquinas críticas sin sustituto'), ('10 %', 'producción del día que se pierde con una hora de paro')],
    errores=['Reparar sin bloqueo y etiquetado.', 'Desarmar antes de diagnosticar.', 'No anotar la falla en la bitácora.', 'Alejarse del frente durante el colado.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de mantenimiento: manuales, planes de falla de las cuatro máquinas críticas, taller móvil y refacciones.'),
                  ('Semana 2', 'Tramo de prueba: noches junto a cada máquina con su operador.'),
                  ('Primeros 3 meses', 'Cursos del fabricante de pavimentadora, planta y máquina de textura y curado.')],
    certificaciones=['NOM-004-STPS (maquinaria) y bloqueo y etiquetado de energías peligrosas.', 'NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Cursos del fabricante de las máquinas del tren.'],
    comprobacion=['¿Cuáles son las cuatro máquinas críticas?', '¿Qué haces antes de meter las manos en una máquina?', '¿A qué distancia del tren estás durante el colado?'],
    siguiente='Jefe de mantenimiento.',
)

P['Electricista · iluminación'] = dict(
    linea='Logística', reporta='Jefe de mantenimiento', esquema='frente',
    mision='Mantener el frente de colado iluminado y con energía toda la noche: torres LED, generadores y respaldo listos para que una falla eléctrica nunca apague el tren.',
    importa='El colado es nocturno: sin luz no hay calidad ni seguridad. Y una planta sin energía a media noche es el peor escenario de la obra.',
    responde=['Las 8 torres de iluminación LED colocadas, encendidas y bien dirigidas antes de las 19:00.',
              'Los 2 generadores de respaldo revisados, con combustible y probados.',
              'Tierras físicas, tableros y cables en buen estado y fuera del paso de máquinas.',
              'Mover las torres conforme avanza el tren, sin dejar zonas oscuras.',
              'La bitácora de horas, combustible y fallas del equipo eléctrico.'],
    autoridad=['Desenergizar un equipo o una línea si hay riesgo eléctrico.', 'Pedir al cabo un paro breve para mover o reparar iluminación en zona de peligro.',
               'No le toca: puentear protecciones ni trabajar en equipo energizado sin procedimiento.'],
    experiencia=['3 años o más como electricista industrial o de obra, con generadores y tableros.', 'Haber instalado iluminación temporal de obra o eventos.',
                 'Deseable: experiencia con plantas de concreto o torres de iluminación móviles.'],
    escolaridad=['Técnico en electricidad o secundaria con oficio comprobado.', 'Leer diagramas eléctricos y usar multímetro y megóhmetro.'],
    persona=['Previsor: prueba antes de que haga falta.', 'Ordenado con los cables: nada tirado donde pasa un camión.', 'Respeta los procedimientos de seguridad eléctrica sin excepción.', 'Resuelve rápido y avisa lo que hizo.'],
    alertas=['Dice que ha trabajado "en caliente" sin problema.', 'No sabe qué es una tierra física.', 'No revisa combustible de los generadores.'],
    preguntas=[('A la 1 a. m. se apaga una torre en la zona de la pavimentadora. ¿Qué haces?', 'Avisar al cabo, mover una torre de respaldo o redirigir otra de inmediato y luego revisar la falla con seguridad.'),
               ('¿Cómo diriges una torre para no cegar a los conductores del carril abierto?', 'Hacia la zona de trabajo, hacia abajo y en sentido contrario al tránsito.'),
               ('¿Qué revisas en un generador antes de la noche?', 'Combustible, aceite, refrigerante, batería, tierra física y una prueba con carga.')],
    prueba='Prueba de 2 horas en el patio: instalar y dirigir dos torres, conectar un generador con su tierra física, simular una falla de energía y pasar al respaldo. Aprueba si lo hace con procedimiento seguro, sin dejar zonas oscuras y en el tiempo marcado.',
    indicadores=['Minutos de paro del tren por iluminación o energía: cero.', 'Torres y generadores revisados y encendidos antes de las 19:00.', 'Cero incidentes eléctricos.', 'Bitácora completa.'],
    dia=[('16:00–18:00', 'Revisión de torres, generadores, combustible, tierras y cables. Encendido de prueba.'),
         ('18:00–19:00', 'Colocas y diriges las torres sobre la zona del tren, la descarga y el desvío.'),
         ('19:00–05:00', 'Mueves las torres conforme avanza el tren; atiendes fallas; revisas combustible a media noche.'),
         ('05:00–06:00', 'Apagas, recoges cables y dejas bitácora al Jefe de mantenimiento.')],
    saber=['El frente lleva 8 torres LED y 2 generadores de respaldo. El colado es de 19:00 a 05:00 y avanza unos 1,000 m: las torres se mueven toda la noche.',
           'La zona de pavimentadora, acabado y laboratorio necesita luz fuerte y pareja (del orden de 200 lux) para ver defectos en la superficie.',
           'La luz se dirige hacia abajo y hacia el trabajo, nunca a los ojos de los conductores del carril abierto.',
           'Una planta parada a media noche es el peor escenario: el respaldo de energía se prueba antes, no durante.',
           'Seguridad eléctrica: tierra física en todo generador y torre; bloqueo y etiquetado antes de reparar; cables protegidos del paso de camiones.'],
    numeros=[('8', 'torres de iluminación LED'), ('2', 'generadores de respaldo'), ('≈ 200 lux', 'en la zona de colado y acabado'), ('19:00', 'todo encendido y probado')],
    errores=['Dejar una zona oscura detrás de la pavimentadora.', 'Cegar a los conductores del carril abierto.', 'Quedarse sin combustible a media noche.', 'Trabajar en equipo energizado sin procedimiento.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de mantenimiento: torres, generadores, tableros, tierras y planes de falla de energía.'),
                  ('Semana 2', 'Tramo de prueba: iluminas el frente y el desvío con Seguridad e higiene.'),
                  ('Primeros 3 meses', 'Curso de seguridad eléctrica NOM-029-STPS y del fabricante de los generadores.')],
    certificaciones=['NOM-029-STPS (mantenimiento de instalaciones eléctricas).', 'Bloqueo y etiquetado de energías peligrosas (NOM-004-STPS).', 'NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).'],
    comprobacion=['¿Cuántas torres y generadores lleva el frente?', '¿Hacia dónde se dirige una torre junto al carril abierto?', '¿Qué revisas en un generador antes de la noche?'],
    siguiente='Electricista responsable de planta y campamento, o Jefe de mantenimiento con formación mecánica.',
)

P['Apoyo general'] = dict(
    linea='Producción', reporta='Cabo de colado', esquema='frente',
    mision='Cubrir lo que el tren necesite durante la noche: rompevientos, pasarela, limpieza, herramienta, plásticos y relevos, para que nadie deje su puesto.',
    importa='Es quien evita que un acabador suelte la llana para ir por plástico o que un operador baje a limpiar. Cada minuto que resuelve es un minuto que el tren no se para.',
    responde=['Tener listos rompevientos, plásticos para lluvia, herramienta de repuesto y agua para la cuadrilla.',
              'Mover la pasarela y apoyar la limpieza de derrames lejos del acero y de la losa.',
              'Cubrir descansos cortos en puestos sencillos cuando el cabo lo indica.',
              'Llevar lo que pidan el laboratorista, el mecánico o el cabo.',
              'Mantener la zona del tren ordenada y libre de obstáculos.'],
    autoridad=['Detener el trabajo si ve a alguien en peligro.', 'Avisar al cabo de cualquier falta de material.',
               'No le toca: operar máquinas ni tocar el concreto con agua.'],
    experiencia=['6 meses o más como ayudante en obra de construcción.', 'Haber trabajado de noche o en turnos largos.'],
    escolaridad=['Primaria terminada; saber leer y escribir.'],
    persona=['Dispuesto: se mueve antes de que le pidan.', 'Atento a la seguridad: mira dónde pisa y dónde están las máquinas.', 'Humilde para aprender de cada puesto.', 'Puntual y constante.'],
    alertas=['Dice que "eso no le toca".', 'Se distrae con el teléfono.', 'No quiere trabajar de noche.'],
    preguntas=[('Empieza a llover y la losa recién colada está descubierta. ¿Qué haces?', 'Llevar los plásticos y cubrir con la cuadrilla lo recién colado, siguiendo al cabo.'),
               ('Un compañero te pide que le pases una cubeta de agua para la mezcla. ¿Qué haces?', 'No hacerlo y avisar al cabo: nunca se añade agua al concreto.'),
               ('¿Dónde no te puedes parar nunca?', 'Detrás de una máquina en reversa, entre dos máquinas o dentro del carril abierto.')],
    prueba='Una noche en el tramo de prueba con el cabo. Aprueba si tiene listo el material a tiempo (rompevientos, plásticos, agua), respeta todas las zonas de peligro y el cabo confirma que ningún puesto tuvo que abandonarse por falta de apoyo.',
    indicadores=['Material listo al inicio de la noche.', 'Cero puestos abandonados por falta de apoyo.', 'Cero incidentes de seguridad.', 'Asistencia completa.'],
    dia=[('18:00', 'Lista con el cabo; cargas rompevientos, plásticos, herramienta y agua.'),
         ('18:30–19:00', 'Colocas rompevientos y pasarela; plática de seguridad.'),
         ('19:00–05:00', 'Apoyas donde pida el cabo; cubres descansos cortos; mantienes la zona limpia.'),
         ('05:00–05:30', 'Recoges material, apoyas la cabecera y la limpieza final.')],
    saber=['El tren nunca se detiene: tu trabajo es que nadie tenga que soltar su puesto.',
           'Rompevientos: se colocan cuando sube el viento; la evaporación no debe pasar de 0.5 kg/m² por hora.',
           'Nunca se añade agua al concreto, aunque te lo pidan.',
           'La pasarela existe para no pisar la losa fresca: nadie la pisa.',
           'Un camión llega cada 2 minutos: la zona de descarga es de riesgo; nunca cruces detrás de un camión.'],
    numeros=[('2 min', 'entre camión y camión'), ('34', 'compañeros en el frente de colado'), ('< 0.5 kg/m²·h', 'evaporación máxima: por eso los rompevientos'), ('0', 'cubetas de agua al concreto')],
    errores=['Pasar agua para la mezcla.', 'Dejar herramienta o material en el camino de las máquinas.', 'Pararse en zona de peligro.'],
    capacitacion=[('Días 2 a 5', 'Con el cabo: el tren, los puestos, los materiales y las zonas de peligro; recorrido de noche.'),
                  ('Semana 2', 'Tramo de prueba junto a cada puesto sencillo del tren para aprender a cubrir descansos.'),
                  ('Primeros 3 meses', 'Curso de seguridad y calidad del tramo de prueba.')],
    certificaciones=['NOM-031-STPS (construcción) y NOM-017-STPS (equipo de protección personal).', 'Primeros auxilios básicos.'],
    comprobacion=['¿Para qué sirven los rompevientos?', '¿Qué haces si te piden agua para la mezcla?', '¿Dónde no te puedes parar nunca?'],
    siguiente='Acabador, controlador de descarga o ayudante de pavimentadora, después de seis meses sin faltas y el curso del tramo de prueba.',
)
