# -*- coding: utf-8 -*-
# RLR · Perfiles de Frente 5 (acabado), Mantenimiento y Choferes propios — Ricardo López Reyero
P = {}

# ───────────────────────── Frente 5 · Acabado, control y entrega ─────────────────────────

P['Cabo de acabado'] = dict(
    linea='Producción', reporta='Superintendente de frente', esquema='frente',
    mision='Convertir cada kilómetro colado en un tramo terminado, medido y entregable: cortado, esmerilado donde haga falta, con sus núcleos, su IRI y su expediente completo.',
    importa='El Frente 5 es el último que toca la carretera antes del cliente. Lo que aquí se deja pasar ya no lo corrige nadie: un tope que no se esmerila, un núcleo que no se saca o un hueco mal tapado se quedan 50 años, y el bono o la penalización por suavidad se decide con su trabajo.',
    responde=['El avance del Frente 5 detrás del colado: que el tramo de anteanoche esté medido y el de hace una semana entregado.',
              'La programación diaria de corte, esmerilado, núcleos y perfilómetro, en el orden correcto y sin pisar losa que aún no aguanta.',
              'La protección de la losa recién colada: nadie circula, nadie la mancha y la membrana de curado se repara donde se dañó.',
              'El expediente de entrega de cada tramo: IRI, espesores, grietas, correcciones hechas y fotos, junto con Topografía y Laboratorio.',
              'La seguridad de su cuadrilla: polvo de sílice, ruido, lodo de esmerilado y tránsito abierto a un lado.'],
    autoridad=['Detener el corte o el esmerilado si la losa no tiene el dato de madurez que lo permite, o si el equipo no está en condiciones.',
               'Ordenar el re-esmerilado de un tramo que el perfilómetro volvió a marcar fuera de especificación.',
               'Pedir al Superintendente que el tren no avance sobre un tramo donde el Frente 5 perdió su colchón de medición.',
               'No le toca: cambiar un resultado de IRI o de núcleo, ni decidir la aceptación del tramo; eso es del Jefe de laboratorio.'],
    experiencia=['5 años o más como cabo o sobrestante en pavimentos de concreto hidráulico, con al menos una obra donde le tocó el acabado, el corte de juntas o la corrección de suavidad.',
                 'Haber trabajado junto a un laboratorio o una supervisión que midió IRI y sacó núcleos, y saber qué pasa con la estimación cuando algo sale mal.',
                 'Mando de cuadrillas pequeñas con equipo de corte y de diamante, en carretera abierta al tránsito.'],
    escolaridad=['Secundaria terminada como mínimo; bachillerato técnico en construcción deseable.', 'Saber leer planos de sección y cadenamientos, y llevar bitácora y formatos en tableta.'],
    persona=['Camina el tramo completo antes de firmar que está listo; no lo firma desde la camioneta.',
             'Revisa dos veces lo que el perfilómetro marca y lo busca con la regla en campo antes de mandar la esmeriladora.',
             'Pide el dato de madurez antes de meter equipo a la losa, aunque lo apuren.',
             'Cuida el orden: el lodo aspirado, las mangueras enrolladas, el tramo limpio al terminar.',
             'Reporta en la junta de las 06:00 el IRI tal como salió, aunque sea malo.'],
    alertas=['Dice que "el esmerilado arregla todo" o que se puede esmerilar lo que sea sin límite.',
             'No sabe qué es el IRI ni para qué sirve un núcleo.',
             'Presume que su cuadrilla "echa el lodo a la cuneta y listo".',
             'Culpa siempre al tren de colado de los topes, sin ofrecer cómo encontrarlos a tiempo.'],
    preguntas=[('El perfilómetro marca IRI de 1.3 m/km en 200 m del tramo de anteanoche. ¿Qué hace hoy?', 'Que lo ubica con cadenamiento, lo confirma en campo, avisa al Residente de colado para que corrija esa noche, y programa esmerilado y nueva medición; no espera a fin de mes.'),
               ('Le piden meter la cortadora a una losa de hace 6 horas porque "ya se ve dura". ¿Qué responde?', 'Que primero pide el dato de madurez al laboratorio; se corta con dato, no con la vista.'),
               ('¿Qué hace con el lodo de la esmeriladora?', 'Se aspira, se lleva a la fosa de secado autorizada y jamás se tira al dren de borde ni a la cuneta.'),
               ('Un camión de la obra quiere cruzar sobre la losa de ayer para acortar camino. ¿Qué hace?', 'Lo detiene: nada rueda sobre la losa hasta que el laboratorio confirme MR 30 kg/cm² por madurez.')],
    prueba='Recorrido en campo de 3 horas sobre un tramo de 1 km ya colado, con el reporte de perfilómetro en mano: debe ubicar con cadenamiento y regla de 3 m los dos puntos peores, proponer el plan de esmerilado del día con orden, equipo y protección de tránsito, y detectar al menos tres faltas sembradas (membrana dañada sin reparar, núcleo mal tapado, lodo en la cuneta). Aprueba si encuentra las faltas y su plan respeta madurez, seguridad y el límite de desbaste.',
    indicadores=['IRI del tramo colado anteanoche reportado a las 06:00, todos los días.', 'Porcentaje de tramos con IRI ≤ 1.0 m/km a la entrega.',
                 'Días de atraso del Frente 5 detrás del colado: cero.', 'Expedientes de entrega completos a la primera.', 'Cero accidentes y cero lodo de esmerilado fuera de la fosa.'],
    dia=[('06:00', 'Reportas en la junta el IRI del tramo de anteanoche y lo que se esmeriló ayer.'),
         ('07:00', 'Plática de 5 minutos con tu cuadrilla: tramo del día, tránsito, polvo y ruido.'),
         ('Mañana', 'Pides el dato de madurez al laboratorio y repartes: perfilómetro al tramo de anteanoche, núcleos donde marque el plan, corte y esmerilado donde toque.'),
         ('Tarde', 'Recorres a pie lo terminado, cierras el expediente y revisas la membrana de curado del tramo de anoche.'),
         ('16:30', 'Entregas el tramo limpio, el equipo lavado y le pasas al Superintendente lo que viste del colado para la junta de 17:30.')],
    saber=['El IRI (índice de rugosidad internacional) se mide en m/km por cada huella de rodada; la meta de aceptación es ≤ 1.0 m/km y trae bono o penalización. Un tope de 1 cm en el lugar equivocado sube el IRI de 100 m completos.',
           'El orden del Frente 5: primero se mide (perfilómetro), luego se corrige (esmerilado) y se vuelve a medir; los núcleos se sacan donde lo diga el plan de control, no donde sea cómodo.',
           'Nada entra a la losa sin dato: el laboratorio confirma por madurez cuándo aguanta el equipo y cuándo llega a MR 30 kg/cm² para abrir a tránsito.',
           'En CRCP no hay juntas transversales: la losa se agrieta sola cada 1 a 2 m y el acero mantiene la grieta en menos de 0.5 mm. Esas grietas no se cortan, no se sellan y no se "arreglan"; se registran.',
           'El esmerilado de diamante quita pocos milímetros: cada milímetro que quitas se lo quitas al espesor de 27 cm que miden los núcleos y al recubrimiento del acero, que va a un tercio del espesor con mínimo 7 cm.',
           'El lodo del esmerilado y del corte es cemento molido en agua: tirado al dren de borde lo tapa y activa la enfermedad número 1. Se aspira y se va a la fosa.',
           'La membrana de curado es la piel de la losa: donde una llanta, una manguera o una bota la raspe, se vuelve a aplicar ese mismo día.'],
    numeros=[('≤ 1.0 m/km', 'IRI de aceptación de cada tramo'), ('anteanoche', 'el tramo que el Frente 5 mide y reporta cada mañana'), ('MR 30 kg/cm²', 'resistencia a flexión, por madurez, antes de abrir a tránsito'),
             ('1–2 m', 'separación normal de las grietas del CRCP'), ('< 0.5 mm', 'abertura máxima de esas grietas'), ('2 km-carril', 'lo que hay que medir cada día: 1 km de dos carriles')],
    errores=['Meter equipo a la losa sin el dato de madurez: la marca queda 50 años.', 'Esmerilar de más para bajar el IRI y comerse el recubrimiento del acero.',
             'Echar el lodo al dren o a la cuneta.', 'Dejar el IRI de anteanoche para "cuando se pueda": el tren repite el mismo defecto cada noche.', 'Firmar un tramo entregado sin caminarlo.'],
    capacitacion=[('Días 2 a 5', 'Una noche en el tren de colado junto al Residente para ver de dónde salen los topes; un día con el Operador de perfilómetro y otro con Núcleos y mediciones.'),
                  ('Semana 2', 'Plan de control y criterios de aceptación con el Jefe de laboratorio: IRI, núcleos, grietas y cómo se arma el expediente de entrega.'),
                  ('Tramo de prueba', 'Mide, corrige y entrega los 500 m de prueba con sus tres variantes; es su ensayo general.'),
                  ('Primer trimestre', 'Revisión mensual con el Superintendente de IRI, atrasos y seguridad de la cuadrilla.')],
    certificaciones=['NOM-031-STPS-2011 (seguridad en obras de construcción) y NOM-017-STPS-2008 (equipo de protección personal).',
                     'Protección contra polvo de sílice y ruido (NOM-010-STPS-2014 y NOM-011-STPS-2001) en corte y esmerilado.',
                     'Curso de interpretación de perfiles e IRI con el Jefe de laboratorio.',
                     'Señalización de obras en carretera abierta al tránsito con Seguridad e higiene.'],
    comprobacion=['¿Qué tramo mides y reportas cada mañana, y cuál es la meta de IRI?', '¿Qué dato necesitas antes de meter cualquier equipo a la losa?',
                  '¿Por qué no se esmerila sin límite?', '¿A dónde va el lodo del esmerilado, y a dónde nunca?'],
    siguiente='Cabo de colado o sobrestante de varios frentes de acabado en el siguiente corredor.',
)

P['Operador de corte y esmerilado'] = dict(
    linea='Producción', reporta='Cabo de acabado', esquema='frente',
    mision='Cortar las juntas que lleva la losa y esmerilar los tramos que el perfilómetro marca, en el momento correcto y a la profundidad exacta, sin dañar el concreto ni el drenaje.',
    importa='Un corte a destiempo agrieta la losa donde no debe; un esmerilado mal hecho deja la carretera más áspera o más delgada de lo que se pagó. Este operador decide, con la máquina en la mano, los últimos milímetros de la carretera.',
    responde=['El corte de la junta longitudinal entre carriles y la del hombro, y de las transversales donde el proyecto las lleve (accesos, anclajes o losa con juntas), a la profundidad y en la ventana indicadas.',
              'El esmerilado de diamante de los tramos marcados, con la profundidad mínima que corrija y la nueva medición después.',
              'El manejo del agua y del lodo: todo aspirado y llevado a la fosa.', 'El estado de sus discos, cabezas de diamante, aspiradora y mangueras.',
              'Su bitácora: cadenamiento, hora, profundidad, discos usados y dato de madurez con el que se cortó.'],
    autoridad=['Negarse a cortar o esmerilar si no tiene el dato de madurez o si la máquina no está en condiciones.',
               'Parar el trabajo si el agua de enfriamiento falla y se levanta polvo.', 'Pedir al Cabo de acabado que se reubique el tránsito si trabaja a menos de lo que marca el plan de señalización.',
               'No le toca: decidir cuánto se esmerila para "bajar el número"; esmerila lo que marca el plan y se vuelve a medir.'],
    experiencia=['3 años o más operando cortadora de juntas autopropulsada o esmeriladora de diamante en pavimento de concreto hidráulico.',
                 'Haber cortado juntas en obra nueva dentro de una ventana de pocas horas, de noche o de madrugada.', 'Deseable: haber trabajado en corrección de suavidad por IRI.'],
    escolaridad=['Primaria o secundaria terminada; saber leer y escribir.', 'Saber leer una cinta métrica, un cadenamiento y el profundímetro de la máquina.'],
    persona=['Revisa el disco y mide la profundidad antes del primer corte, no después.', 'Trabaja con calma y a velocidad pareja; no fuerza la máquina.',
             'Mantiene el agua abierta todo el tiempo y la aspiradora conectada.', 'Avisa de inmediato si un corte le salió chueco o si nota una grieta rara.'],
    alertas=['Dice que "el corte se hace cuando uno ve que ya se puede".', 'Trabaja en seco "para ir más rápido".', 'No conoce la diferencia entre cortar y esmerilar.', 'No usa protección auditiva ni respirador.'],
    preguntas=[('¿Cuándo se corta una junta en losa recién colada?', 'Dentro de la ventana que marca el dato de madurez: ni tan pronto que desportille ni tan tarde que la losa se agriete sola donde no debe.'),
               ('¿Por qué se corta con agua?', 'Para enfriar el diamante y para que no se levante polvo de sílice, que enferma los pulmones.'),
               ('Terminaste de esmerilar un tramo. ¿Ya acabaste?', 'No: el tramo se vuelve a medir con el perfilómetro y se revisa que no haya quedado escalón ni desbaste de más.')],
    prueba='Prueba en campo de 2 horas en losa de desecho o del tramo de prueba: cortar 20 m de junta longitudinal a la profundidad indicada (se verifica cada 2 m con profundímetro, tolerancia ± 3 mm, recta y sin desportillar) y esmerilar un tramo de 10 m marcado, dejando el lodo aspirado y el disco revisado. Aprueba si cumple profundidad, alineación, limpieza y seguridad.',
    indicadores=['Cortes a la profundidad indicada, verificados con profundímetro.', 'Cero cortes fuera de la ventana de madurez.', 'Tramos esmerilados que pasan la nueva medición a la primera.',
                 'Cero lodo fuera de la fosa; cero accidentes.'],
    dia=[('07:00', 'Recibes con el Cabo de acabado los tramos del día y el dato de madurez.'), ('07:15', 'Revisas disco, agua, aspiradora y profundímetro; te pones tu equipo.'),
         ('Mañana y tarde', 'Cortas o esmerilas según el plan, anotando cadenamiento y profundidad.'), ('Al terminar cada tramo', 'Aspiras el lodo, lo llevas a la fosa y avisas para la nueva medición.'),
         ('Cierre', 'Lavas la máquina y dejas anotado el desgaste del disco para Almacén.')],
    saber=['La junta longitudinal entre los dos carriles va a un tercio del espesor: en losa de 27 cm son unos 9 cm. En losa con juntas, la transversal va a un cuarto del espesor y se corta entre 4 y 12 horas, según el dato del día.',
           'En CRCP no hay juntas transversales en el tramo corrido: las grietas salen solas cada 1 a 2 m. Nunca cortes ni "repases" una grieta del CRCP.',
           'Se corta con dato de madurez, no con la vista: si cortas temprano, el borde se desportilla; si cortas tarde, la losa se agrieta sola donde no debe.',
           'El esmerilado quita sólo lo necesario, pocos milímetros; cada milímetro de más se lo quitas al espesor de 27 cm y al recubrimiento del acero (mínimo 7 cm).',
           'El esmerilado deja franjas parejas y en la dirección del tránsito; no debe quedar escalón con la losa de al lado.',
           'El lodo es cemento molido: tirado al dren de borde lo tapa. Siempre aspirado y a la fosa.',
           'Polvo de sílice: se corta y esmerila siempre en húmedo, con respirador y protección auditiva.'],
    numeros=[('≈ 9 cm', 'profundidad de la junta longitudinal en losa de 27 cm (un tercio)'), ('1/4 del espesor', 'profundidad de la junta transversal en losa con juntas'),
             ('4–12 h', 'ventana típica de corte en losa con juntas, afinada con el dato de madurez'), ('7 cm', 'recubrimiento mínimo del acero que el esmerilado no puede comerse'), ('≤ 1.0 m/km', 'IRI que el esmerilado tiene que dejar')],
    errores=['Cortar sin dato de madurez.', 'Cortar o esmerilar en seco.', 'Esmerilar de más "para asegurar".', 'Tirar el lodo al dren o a la cuneta.', 'Cortar una grieta del CRCP pensando que es junta.'],
    capacitacion=[('Días 2 a 5', 'Con el Cabo de acabado: plan de corte del proyecto, lectura del dato de madurez y práctica en losa de desecho.'),
                  ('Semana 2', 'Con el Operador de perfilómetro: cómo se lee un perfil, dónde está el tope y cómo se verifica después de esmerilar.'),
                  ('Tramo de prueba', 'Corta y esmerila los 500 m de prueba bajo supervisión del Cabo y del laboratorio.'),
                  ('Cada mes', 'Revisión de discos y cabezas con Almacén y del registro de profundidades con el Cabo.')],
    certificaciones=['NOM-004-STPS-1999 (sistemas de protección en maquinaria y equipo).', 'NOM-010-STPS-2014 (polvo de sílice) y NOM-011-STPS-2001 (ruido).',
                     'NOM-031-STPS-2011 (seguridad en construcción) y NOM-017-STPS-2008 (equipo de protección personal).'],
    comprobacion=['¿A qué profundidad va la junta longitudinal en losa de 27 cm?', '¿Con qué dato sabes que ya puedes cortar?', '¿Por qué nunca se corta una grieta del CRCP?', '¿Qué haces con el lodo?'],
    siguiente='Cabo de acabado.',
)

P['Núcleos y mediciones'] = dict(
    linea='Calidad', reporta='Jefe de laboratorio', esquema='calidad',
    mision='Sacar los núcleos y hacer las mediciones que demuestran, con números, que la losa tiene el espesor, el acero y la calidad que se pagaron.',
    importa='El contrato se acepta por núcleos extraídos, no por acta firmada. Si este puesto mide mal, el pavimento se paga como si tuviera 27 cm cuando tiene 25, o se penaliza un tramo bueno; en los dos casos se pierde la confianza en el laboratorio.',
    responde=['La extracción de núcleos en los puntos que marca el plan de control, elegidos al azar y ubicados con cadenamiento y GPS.',
              'La medición del espesor de cada núcleo y la posición y recubrimiento del acero.', 'El levantamiento de grietas del CRCP: separación y abertura por tramo.',
              'La reparación del hueco de cada núcleo el mismo día.', 'La cadena de custodia: cada núcleo etiquetado, fotografiado y entregado al laboratorio.'],
    autoridad=['Reportar directamente al Jefe de laboratorio cualquier espesor o recubrimiento fuera de especificación, sin pasar por Producción.',
               'Negarse a cambiar un punto de extracción por uno "más cómodo" o "más grueso".', 'Detener su trabajo si el tránsito no está señalizado.',
               'No le toca: decidir si se acepta o se penaliza el tramo; eso lo decide el Jefe de laboratorio con sus datos.'],
    experiencia=['2 años o más como técnico de laboratorio de concreto o de terracerías, con extracción de núcleos con broca de diamante en obra.',
                 'Haber medido espesores y llenado registros para una supervisión o dependencia.', 'Deseable: manejo de detector de acero (pachómetro) y de GPS de mano.'],
    escolaridad=['Bachillerato o carrera técnica en construcción o laboratorio.', 'Saber hacer cuentas con decimales, usar calibrador y capturar en tableta.'],
    persona=['Mide dos veces y anota en el momento, no al final del día.', 'No se deja "ayudar" a escoger el punto de extracción.',
             'Cuidadoso con la muestra: la etiqueta, la protege y la entrega completa.', 'Deja el lugar como lo encontró: el hueco tapado y nivelado.'],
    alertas=['Dice que "el punto se escoge donde se vea bien la losa".', 'Anota las medidas "de memoria" al regresar al laboratorio.', 'Nunca ha visto un núcleo con el espesor incompleto o no sabe qué se hizo.'],
    preguntas=[('El Cabo de acabado te pide sacar el núcleo 30 m más adelante porque ahí "está más cómodo". ¿Qué haces?', 'Lo sacas donde marcó el sorteo del plan de control y le avisas al Jefe de laboratorio de la petición.'),
               ('Te sale un núcleo de 25.5 cm en un tramo de 27. ¿Qué haces?', 'Lo mides otra vez, lo fotografías con su etiqueta, lo reportas de inmediato al Jefe de laboratorio y no lo comentas como "error de la broca".'),
               ('¿Qué haces antes de meter la broca a la losa?', 'Paso el detector de acero para no cortar una varilla #6 y ubico el punto entre varillas.')],
    prueba='Prueba en campo de 3 horas sobre el tramo de prueba o una losa de ensayo: ubicar un punto sorteado con GPS y cadenamiento, localizar el acero con detector, extraer un núcleo sin cortar varilla, medir el espesor con calibrador en varios puntos del perímetro (diferencia con la medición del evaluador ≤ 2 mm), medir la profundidad del acero, tapar el hueco y entregar el registro completo con foto. Aprueba si no corta acero, mide dentro de la tolerancia y el registro no tiene huecos.',
    indicadores=['Núcleos extraídos contra el plan de control: 100 %.', 'Registros completos (cadenamiento, GPS, foto, espesor, acero) el mismo día.', 'Huecos reparados el mismo día: 100 %.',
                 'Cero núcleos con varilla cortada.'],
    dia=[('07:00', 'Recibes del Jefe de laboratorio los puntos sorteados del día.'), ('07:30', 'Revisas broca, agua, planta de luz, detector de acero y calibrador.'),
         ('Mañana', 'Ubicas, extraes, mides en campo y tapas cada hueco.'), ('Tarde', 'Levantamiento de grietas del tramo que toque y entrega de núcleos al laboratorio.'),
         ('Cierre', 'Capturas todo en la tableta antes de irte; el dato del día se cierra el mismo día.')],
    saber=['El espesor de proyecto es 27 cm y se acepta por núcleos con penalización por lo que falte. El núcleo se mide en varios puntos de su perímetro con calibrador y se promedia.',
           'El acero longitudinal es varilla #6 (19 mm) cada 15 cm, a un tercio del espesor desde arriba (unos 9 cm) sobre sillas, con 7 cm de recubrimiento mínimo; el transversal es #4 cada 90 cm. Antes de perforar, ubícalo con el detector.',
           'El punto se sortea: si alguien escoge dónde medir, la medición ya no vale.',
           'En CRCP las grietas salen solas cada 1 a 2 m y deben quedar cerradas, en menos de 0.5 mm. Grietas muy juntas, ramificadas o abiertas son un aviso que el Jefe de laboratorio tiene que ver ese mismo día.',
           'Cada núcleo lleva etiqueta con cadenamiento, carril, fecha de colado y fecha de extracción; también sirve para ensayos de permeabilidad (menos de 1,500 coulombs).',
           'El hueco se rellena el mismo día con mortero sin contracción y se enrasa; un hueco abierto es una entrada de agua directa a la base.'],
    numeros=[('27 cm', 'espesor de proyecto que el núcleo tiene que demostrar'), ('≈ 9 cm', 'profundidad del acero longitudinal (un tercio del espesor)'), ('7 cm', 'recubrimiento mínimo del acero'),
             ('< 0.5 mm', 'abertura máxima de una grieta del CRCP'), ('< 1,500 C', 'permeabilidad del concreto medida en núcleo'), ('el mismo día', 'se tapa el hueco y se captura el dato')],
    errores=['Escoger el punto en lugar de sortearlo.', 'Perforar sin ubicar el acero y cortar una varilla.', 'Dejar el hueco abierto para "taparlo mañana".', 'Anotar medidas al final del día de memoria.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de laboratorio: plan de control, sorteo de puntos, uso del detector de acero y del calibrador, y práctica en losa de ensayo.'),
                  ('Semana 2', 'Levantamiento de grietas del CRCP y captura en tableta con el Ingeniero de datos.'),
                  ('Tramo de prueba', 'Extrae y mide todos los núcleos de las tres variantes de los 500 m.'),
                  ('Primer semestre', 'Preparación para la certificación de técnico de campo en concreto.')],
    certificaciones=['ACI Concrete Field Testing Technician Grade I, o su equivalente en México.', 'Extracción y ensaye de corazones de concreto según la norma NMX-C del ONNCCE que aplique.',
                     'NOM-031-STPS-2011 (seguridad en construcción) y NOM-017-STPS-2008 (equipo de protección personal).'],
    comprobacion=['¿Por qué el punto de extracción se sortea?', '¿Qué haces antes de meter la broca y por qué?', '¿Cuándo se tapa el hueco de un núcleo?', '¿A quién le reportas un espesor faltante?'],
    siguiente='Laboratorista de turno o Laboratorista de día.',
)

P['Operador de perfilómetro'] = dict(
    linea='Calidad', reporta='Jefe de laboratorio', esquema='calidad',
    mision='Medir la suavidad de cada metro colado con el perfilómetro inercial y entregar a tiempo el IRI que decide correcciones, bono y penalización.',
    importa='La suavidad no se juzga a ojo: un pavimento más liso recibe menos golpe de cada eje y dura más. Si el perfilómetro mide mal o tarde, el tren repite el mismo defecto varias noches y la empresa paga penalizaciones o cobra bonos que no merece.',
    responde=['La medición diaria del tramo colado anteanoche, en las dos huellas de cada carril.', 'La calibración y verificación del equipo antes de medir.',
              'El reporte de IRI por tramo y de los puntos de rugosidad localizada, con cadenamiento, listo para la junta de las 06:00.',
              'La nueva medición de cada tramo esmerilado.', 'El cuidado del vehículo, los sensores y los archivos de medición.'],
    autoridad=['Negarse a medir si el equipo no pasó su verificación del día.', 'Invalidar una corrida con velocidad o trayectoria fuera de lo permitido y repetirla.',
               'Reportar directamente al Jefe de laboratorio, sin pasar por Producción.', 'No le toca: borrar, recortar o "filtrar" una corrida para que el número salga mejor.'],
    experiencia=['2 años o más operando perfilómetro inercial o equipo de auscultación de pavimentos (IRI, deflexiones o textura).',
                 'Haber medido para aceptación de obra nueva o para una evaluación de red carretera.', 'Deseable: manejo de software de análisis de perfiles.'],
    escolaridad=['Bachillerato o carrera técnica; técnico en topografía, laboratorio o electrónica deseable.', 'Licencia de manejo vigente y buen manejo de computadora.'],
    persona=['Hace la verificación del equipo aunque tenga prisa.', 'Maneja a velocidad pareja y sobre la huella, sin zigzaguear.',
             'Entrega el número tal como salió y explica de dónde viene.', 'Ordenado con sus archivos: cada corrida con fecha, tramo, carril y huella.'],
    alertas=['Dice que "si sale alto, se vuelve a pasar hasta que salga bien".', 'No sabe qué es el IRI ni en qué unidades se mide.', 'Nunca ha calibrado un equipo por sí mismo.'],
    preguntas=[('Tu corrida marca 1.4 m/km y el Residente te pide volver a pasar "más despacio". ¿Qué haces?', 'Repito sólo si la corrida no fue válida por equipo o trayectoria; si fue válida, reporto el número como salió.'),
               ('¿Qué revisas antes de la primera corrida del día?', 'La verificación del equipo: sensores, acelerómetros y la distancia contra el tramo de calibración.'),
               ('¿Cuándo puede entrar el perfilómetro a la losa?', 'Cuando el laboratorio confirma por madurez que la losa aguanta el vehículo.')],
    prueba='Prueba en campo de medio día: hacer la verificación completa del equipo, medir 1 km en las dos huellas de un carril con tres corridas repetidas y entregar el reporte de IRI por cada 100 m y los puntos de rugosidad localizada con cadenamiento. Aprueba si la verificación está completa, las tres corridas se parecen entre sí dentro de lo que marca el procedimiento del equipo y el reporte identifica los puntos que el evaluador sembró.',
    indicadores=['IRI de anteanoche entregado antes de las 06:00, todos los días.', 'Verificación del equipo registrada cada día de medición.', 'Corridas repetibles dentro de lo que marca el procedimiento.',
                 'Tramos esmerilados vueltos a medir en menos de 24 h.'],
    dia=[('05:00–06:00', 'Terminas y revisas el reporte del tramo de anteanoche para la junta.'), ('06:00', 'Presentas el IRI: el número, dónde está lo peor y la causa probable.'),
         ('Mañana', 'Verificas el equipo y mides el tramo que ya tiene dato de madurez.'), ('Tarde', 'Vuelves a medir lo esmerilado y procesas las corridas.'),
         ('Cierre', 'Respaldas los archivos y dejas el vehículo cargado y limpio.')],
    saber=['El IRI se mide en m/km, en cada huella de rodada; la meta de aceptación es ≤ 1.0 m/km y lleva bono y penalización.',
           'Se mide el tramo colado anteanoche: 1 km de dos carriles son 2 km-carril y cuatro huellas cada día.',
           'Antes de medir se verifica el equipo: altura de los sensores, acelerómetros y la distancia contra un tramo medido por topografía. Sin verificación, la corrida no vale.',
           'Una corrida sólo es válida con velocidad dentro del rango del equipo, sin frenar ni acelerar de golpe y sobre la huella.',
           'Además del IRI por tramo, busca la rugosidad localizada: un tope corto es lo que se esmerila, y lo que le dice al tren qué corregir esa misma noche.',
           'La losa nueva sólo se pisa cuando el laboratorio confirma por madurez que aguanta.'],
    numeros=[('≤ 1.0 m/km', 'IRI de aceptación'), ('anteanoche', 'el tramo que se mide cada día'), ('4 huellas', 'dos por carril, en cada kilómetro'),
             ('06:00', 'hora en que el IRI tiene que estar en el tablero'), ('< 24 h', 'para volver a medir un tramo esmerilado')],
    errores=['Medir sin verificar el equipo.', 'Repetir corridas "hasta que salga bien".', 'Entregar el IRI tarde: el tren repite el defecto.', 'Perder o sobrescribir archivos de medición.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de laboratorio: procedimiento de verificación, operación del equipo y software de análisis.'),
                  ('Semana 2', 'Mide junto al Cabo de acabado y el Operador de corte y esmerilado: cómo se traduce un perfil en un punto a corregir.'),
                  ('Tramo de prueba', 'Mide los 500 m de prueba y sus tres variantes; establece la línea base.'),
                  ('Cada año', 'Recalibración del equipo con el fabricante o un laboratorio acreditado.')],
    certificaciones=['Operación y verificación de perfilómetro inercial (curso del fabricante o de un laboratorio acreditado).', 'Manejo defensivo y licencia de manejo vigente.',
                     'NOM-031-STPS-2011 (seguridad en construcción) y NOM-017-STPS-2008 (equipo de protección personal).'],
    comprobacion=['¿Cuál es el IRI de aceptación y en qué unidades se mide?', '¿Qué verificas antes de la primera corrida?', '¿Cuándo es válida una corrida?', '¿Qué haces si el Residente te pide volver a pasar?'],
    siguiente='Laboratorista o técnico de auscultación del activo para la conservación por disponibilidad.',
)

# ───────────────────────── Mantenimiento ─────────────────────────

P['Jefe de mantenimiento'] = dict(
    linea='Logística', reporta='Gerente de logística', esquema='frente',
    mision='Garantizar que las cuatro máquinas críticas y toda la flotilla estén listas cada noche, con mantenimiento preventivo por horas y un plan escrito para cada falla de las 2 de la mañana.',
    importa='Una hora de paro del tren cuesta el 10 % de la producción del día. La diferencia entre una falla de 20 minutos y una noche perdida es el mantenimiento que se hizo de madrugada y la refacción que estaba en el almacén.',
    responde=['La disponibilidad de la planta, la pavimentadora, la enfriadora y la máquina de textura y curado.',
              'El programa de mantenimiento preventivo por horómetro de toda la flotilla, incluidas las 12 revolvedoras propias.',
              'La bitácora de horas por máquina y el cambio de piezas antes de su límite.', 'La lista de refacciones críticas en sitio, junto con Almacén y refacciones.',
              'El mecánico de turno en el frente y el electricista de iluminación, y su entrega de turno a las 05:00.',
              'Los protocolos escritos de falla de las cuatro máquinas críticas.'],
    autoridad=['Retirar de servicio una máquina o un camión que no esté seguro o que llegó a su límite de horas.',
               'Pedir a Almacén y a Logística la compra urgente de una refacción crítica.', 'Decidir con el Residente de colado si una falla nocturna se repara en el frente o se activa el plan de respaldo.',
               'No le toca: autorizar que una máquina trabaje "una noche más" pasada de su límite para no parar.'],
    experiencia=['8 años o más como mecánico y 3 o más como jefe de taller o de mantenimiento de maquinaria pesada, idealmente con pavimentadoras de cimbra deslizante y plantas de concreto.',
                 'Haber montado un programa de mantenimiento preventivo por horas en una flotilla de más de 30 unidades.', 'Haber resuelto fallas hidráulicas y de control de noche, con la obra esperando.'],
    escolaridad=['Carrera técnica en mecánica diésel, industrial o mecatrónica; ingeniería mecánica deseable pero no indispensable.',
                 'Saber leer manuales de fabricante y diagramas hidráulicos y eléctricos, y manejar bitácoras digitales.'],
    persona=['Llega a las 05:00 y lo primero que pregunta es qué falló en la noche y por qué.', 'Cambia una pieza antes de que falle aunque "todavía sirva".',
             'Tiene el plan de falla de cada máquina crítica en la cabeza y en papel.', 'Enseña a sus mecánicos y los hace responsables de su máquina.', 'Cuenta refacciones: sabe qué hay en el almacén sin ir a ver.'],
    alertas=['Trabaja sólo "cuando se rompe".', 'No lleva bitácora de horas.', 'Presume reparaciones heroicas pero no sabe cuánto duró la máquina parada.', 'Culpa a los operadores de todas las fallas.'],
    preguntas=[('A las 02:00 falla un sensor del control 3D de la pavimentadora. ¿Qué pasa?', 'El mecánico de turno aplica el plan escrito, el sensor de repuesto está en sitio y se cambia en minutos; al día siguiente se analiza la causa.'),
               ('La planta llega a su límite de horas de banda el viernes y hay colado el sábado. ¿Qué hace?', 'La cambia de madrugada antes del sábado; no se cuela una noche con una pieza pasada de su límite.'),
               ('¿Qué revisa antes de que la planta se reubique?', 'Todo el sistema y después la prueba de 4 horas continuas, antes de reanudar.'),
               ('¿Qué refacciones deben estar siempre en sitio?', 'Las de las cuatro máquinas críticas: bandas, mangueras, sensores, bombas y vibradores, según el manual de cada una.')],
    prueba='Caso práctico de 3 horas: con la bitácora de horas de una flotilla real y la lista del almacén, armar el plan de mantenimiento de la semana sin quitar ninguna máquina crítica en horario de colado, detectar dos faltantes sembrados en refacciones críticas y escribir el protocolo de falla de una de las cuatro máquinas. Después, diagnóstico en taller de una falla hidráulica real en 45 minutos. Aprueba si el plan cabe entre 05:00 y 16:00, encuentra los faltantes y el protocolo dice quién decide y qué se hace.',
    indicadores=['Disponibilidad de las cuatro máquinas críticas durante el colado.', 'Minutos de paro del tren por falla mecánica.', 'Mantenimientos preventivos hechos a tiempo contra programados.',
                 'Refacciones críticas en sitio: 100 %.', 'Revolvedoras propias fuera de ciclo por falla: cero.'],
    dia=[('05:00', 'Recibes al mecánico de turno y al electricista: fallas de la noche, causa y qué quedó pendiente.'), ('06:00', 'Junta de cierre: minutos de paro por falla mecánica, con causa.'),
         ('06:30–14:00', 'Mantenimiento preventivo por horómetro del tren y la flotilla; reparaciones pendientes.'), ('14:00–16:00', 'Pruebas en vacío de las cuatro máquinas y entrega al tren.'),
         ('16:00', 'Entregas por escrito al mecánico de turno el estado de cada máquina crítica y lo que hay que vigilar.')],
    saber=['Las cuatro máquinas críticas: planta de 250–280 m³/h, pavimentadora de cimbra deslizante con control 3D, enfriadora de agua y máquina de textura y curado. No tienen sustituto a media noche.',
           'Mantenimiento preventivo por horas, no por falla: bitácora de horas por máquina y cambio antes del límite del fabricante.',
           'De madrugada se repara: tu ventana es de 05:00 a 16:00; a las 16:00 el tren se empieza a armar y a las 19:00 cuela.',
           'Las causas típicas de paro: banda rota o báscula descalibrada en planta; hidráulica, sensores del control 3D y vibradores en el tren; ponchadura o falla de un camión en el acarreo.',
           'Refacciones críticas en sitio: bandas, mangueras, sensores, bombas y vibradores, con la lista sacada del manual de cada máquina.',
           'Cada vez que la planta salta, cada 15–20 km, se prueba 4 horas continuas antes de reanudar.',
           'Nadie deja el frente para cargar diésel: el camión de combustible y el patio de planta abastecen.'],
    numeros=[('4', 'máquinas críticas sin sustituto a media noche'), ('10 %', 'de la producción del día se pierde con una hora de paro'), ('05:00–16:00', 'tu ventana para reparar'),
             ('4 h', 'prueba continua de la planta antes de reanudar tras cada salto'), ('12', 'revolvedoras propias que dependen de tu taller'), ('100 m', 'distancia a la que debe estar el mecánico de turno del tren, no 40 km')],
    errores=['Dejar trabajar una máquina pasada de su límite de horas.', 'Esperar a que se rompa para reparar.', 'Descubrir a las 2 de la mañana que la refacción no está en el almacén.',
             'Entregar el tren a las 16:00 sin probarlo.'],
    capacitacion=[('Días 2 a 5', 'Recorre planta, tren, taller móvil y almacén; inventario de horas de cada máquina y de refacciones críticas.'),
                  ('Semanas 2 a 4', 'Monta con el Ingeniero de datos la bitácora de horas y con Almacén la lista de refacciones; escribe los cuatro protocolos de falla con el Gerente de logística.'),
                  ('Tramo de prueba', 'Mantiene el tren durante los 500 m de prueba; ajusta el programa con lo que falló.'),
                  ('Primer año', 'Capacitación del fabricante en la pavimentadora y la planta; revisión mensual de disponibilidad con el Gerente de logística.')],
    certificaciones=['NOM-004-STPS-1999 (maquinaria y equipo) y NOM-029-STPS-2011 (mantenimiento de instalaciones eléctricas).',
                     'NOM-027-STPS-2008 (soldadura y corte) y NOM-020-STPS-2011 (recipientes sujetos a presión).',
                     'Curso del fabricante de la pavimentadora de cimbra deslizante y de la planta.', 'Sistemas hidráulicos y de control 3D.'],
    comprobacion=['¿Cuáles son las cuatro máquinas críticas y qué tienen en común?', '¿Qué ventana tienes para reparar y a qué hora entregas el tren?',
                  '¿Qué pasa con la planta después de cada salto?', '¿Qué haces con una pieza que llegó a su límite de horas pero todavía funciona?'],
    siguiente='Gerente de maquinaria de varios frentes o del parque de equipo de la empresa.',
)

P['Mecánico'] = dict(
    linea='Logística', reporta='Jefe de mantenimiento', esquema='frente',
    mision='Hacer el mantenimiento preventivo y las reparaciones de madrugada para que cada máquina y cada camión salgan a trabajar sin fallar esa noche.',
    importa='Cada falla que se previene en el taller es una noche que el tren no se para. Este puesto trabaja cuando nadie mira, y su trabajo se nota sólo cuando falta.',
    responde=['Los servicios preventivos por horómetro de las máquinas y camiones que le asigne el Jefe de mantenimiento.', 'Las reparaciones pendientes que dejó la noche.',
              'Revisar mangueras, conexiones hidráulicas, bandas, vibradores y sensores de las máquinas del tren.', 'La bitácora de cada trabajo: máquina, horas, qué se hizo y qué piezas se usaron.',
              'El orden y la limpieza del taller móvil y de su herramienta.'],
    autoridad=['Marcar una máquina como "no apta" y avisar al Jefe de mantenimiento antes de que salga.', 'Detener su trabajo si la máquina no está bloqueada y sin energía.',
               'Pedir a Almacén la refacción que falta en cuanto la detecta.', 'No le toca: autorizar que una máquina salga pasada de su límite o con una falla conocida.'],
    experiencia=['3 años o más como mecánico diésel de maquinaria pesada o de camiones, con sistemas hidráulicos.',
                 'Deseable: haber trabajado en pavimentadoras, plantas de concreto, compactadores o revolvedoras.', 'Haber trabajado en taller de obra o de campo, no sólo en agencia.'],
    escolaridad=['Secundaria terminada; carrera técnica en mecánica diésel o industrial deseable.', 'Saber leer un manual de servicio y llenar la bitácora.'],
    persona=['Termina lo que empieza y deja la máquina probada.', 'Bloquea y etiqueta antes de meter la mano.', 'Avisa de lo que vio aunque no le tocara revisarlo.', 'Cuida su herramienta y la del taller.'],
    alertas=['No bloquea la máquina "porque va rápido".', 'Deja trabajos a medias sin avisar.', 'No sabe leer un manual o no quiere llenar la bitácora.'],
    preguntas=[('Encuentras una manguera hidráulica de la pavimentadora rozada pero sin fuga. ¿Qué haces?', 'La cambio ahora y lo anoto; de noche esa manguera revienta y para el tren.'),
               ('¿Qué haces antes de trabajar en una máquina?', 'Apagar, bloquear, etiquetar y liberar presión hidráulica.'),
               ('Te falta una refacción para terminar a las 16:00. ¿Qué haces?', 'Aviso de inmediato al Jefe de mantenimiento y a Almacén, no al final del turno.')],
    prueba='Prueba en taller de 3 horas: servicio preventivo completo de una máquina (cambio de filtros, revisión de niveles, engrase y revisión de mangueras) siguiendo el manual, con bloqueo y etiquetado, y diagnóstico de una falla hidráulica o eléctrica sembrada. Aprueba si sigue el manual, bloquea antes de trabajar, encuentra la falla y llena la bitácora completa.',
    indicadores=['Servicios preventivos terminados a tiempo.', 'Fallas repetidas en la misma máquina dentro de 30 días: cero.', 'Bitácora completa el mismo día.', 'Cero accidentes en el taller.'],
    dia=[('05:00', 'Recibes con el Jefe de mantenimiento lo que falló en la noche y tus máquinas del día.'), ('05:30', 'Bloqueas y etiquetas cada máquina antes de trabajar.'),
         ('Mañana', 'Servicios preventivos por horómetro y reparaciones.'), ('Hasta 15:30', 'Pruebas en vacío de lo que reparaste.'), ('Cierre', 'Bitácora, herramienta limpia y taller en orden.')],
    saber=['Se repara de madrugada: el tren cuela de 19:00 a 05:00 y a las 16:00 se empieza a armar; lo tuyo tiene que estar probado antes.',
           'Preventivo por horas: cada máquina tiene su horómetro y su programa; una pieza se cambia al llegar a su límite aunque todavía sirva.',
           'En el tren, lo que más falla es la hidráulica, los sensores del control 3D y los vibradores. Revísalos en cada servicio.',
           'Bloqueo y etiquetado: apagar, quitar la llave, poner candado y etiqueta, liberar presión y comprobar que no arranca antes de meter la mano.',
           'La limpieza cuenta: el concreto pegado en vibradores, cadenas y bandas se quita todos los días o endurece y rompe piezas.',
           'Todo trabajo va a la bitácora: máquina, horas, qué hiciste y qué refacción usaste.'],
    numeros=[('05:00', 'hora en que entras'), ('16:00', 'hora en que el tren se empieza a armar'), ('4', 'máquinas críticas sin sustituto'), ('12', 'revolvedoras propias')],
    errores=['Trabajar en una máquina sin bloquearla.', 'Dejar una manguera dudosa "para la próxima".', 'No probar la máquina después de repararla.', 'No anotar lo que hiciste.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de mantenimiento: recorrido del tren, la planta y las revolvedoras; programa de horas y bloqueo y etiquetado.'),
                  ('Semana 2', 'Trabaja junto al mecánico más experimentado en un servicio de cada máquina crítica.'),
                  ('Tramo de prueba', 'Mantenimiento del tren durante los 500 m de prueba.'),
                  ('Primer año', 'Curso del fabricante en al menos una máquina crítica; cubre turnos como Mecánico de turno.')],
    certificaciones=['NOM-004-STPS-1999 (maquinaria y equipo) con bloqueo y etiquetado.', 'NOM-027-STPS-2008 (soldadura y corte) si suelda.',
                     'NOM-017-STPS-2008 (equipo de protección personal).', 'Hidráulica de maquinaria pesada.'],
    comprobacion=['¿Qué haces antes de meter la mano en una máquina?', '¿Por qué se cambia una pieza que todavía sirve?', '¿Qué es lo que más falla en el tren?', '¿A qué hora tiene que estar lista la máquina?'],
    siguiente='Mecánico de turno del tren de colado.',
)

P['Llantero-lubricador'] = dict(
    linea='Logística', reporta='Jefe de mantenimiento', esquema='frente',
    mision='Mantener las llantas y la lubricación de toda la flotilla al día, para que ningún camión se ponche en el ciclo y ninguna máquina se desgaste por falta de grasa o aceite.',
    importa='Un camión que se poncha se sale del ciclo y rompe el ritmo de un camión cada dos minutos: es la causa número uno de paro. Un punto sin grasa en la pavimentadora es una pieza rota a media noche.',
    responde=['La revisión diaria de presión, desgaste y daños de las llantas de las 12 revolvedoras propias y de los vehículos de la obra.',
              'La reparación y el cambio de llantas en la jaula de inflado.', 'El engrase y los niveles de aceite de las máquinas según su carta de lubricación.',
              'El registro por llanta y por máquina: presión, profundidad, cambios y engrases.', 'El manejo limpio de aceites y grasas usadas.'],
    autoridad=['Sacar de servicio un camión con una llanta dañada o fuera de presión.', 'Pedir a Almacén llantas, grasas y aceites antes de que se acaben.',
               'Negarse a inflar una llanta fuera de la jaula.', 'No le toca: dejar salir un camión "sólo esta noche" con una llanta mala.'],
    experiencia=['2 años o más como llantero o lubricador de flotilla de camiones pesados o maquinaria.', 'Manejo de llantas de camión y rines, y de cartas de lubricación.'],
    escolaridad=['Primaria o secundaria terminada; saber leer y escribir.', 'Saber usar calibrador de presión y de profundidad, y llenar una bitácora sencilla.'],
    persona=['Revisa todas las llantas, no sólo las que "se ven mal".', 'Infla siempre en la jaula, aunque tarde más.', 'Engrasa todos los puntos de la carta, no sólo los fáciles.', 'Deja el aceite usado en su tambo, nunca en el suelo.'],
    alertas=['Infla llantas sin jaula "porque así lo ha hecho siempre".', 'No sabe cuánta presión lleva una llanta de camión.', 'Tira el aceite usado a la tierra.'],
    preguntas=[('Encuentras una revolvedora con una llanta con un corte en el costado. ¿Qué haces?', 'La saco de servicio, aviso al Jefe de mantenimiento y al despachador, y la cambio antes de que salga.'),
               ('¿Por qué se infla una llanta de camión en jaula?', 'Porque si el rin o la llanta revientan, la jaula detiene las piezas; sin jaula eso mata.'),
               ('¿Qué pasa si una máquina se queda un día sin engrasar?', 'Se desgastan pernos y bujes, y la pieza falla de noche con el tren trabajando.')],
    prueba='Prueba en patio de 2 horas: revisar presión y profundidad de las llantas de dos revolvedoras (se siembran dos llantas fuera de presión y una dañada), desmontar y montar una llanta inflándola en jaula, y engrasar una máquina siguiendo su carta de lubricación. Aprueba si encuentra las tres fallas, usa la jaula y no se salta ningún punto de engrase.',
    indicadores=['Camiones fuera de ciclo por ponchadura: cero.', 'Llantas revisadas contra flotilla: 100 % cada día.', 'Máquinas engrasadas según su carta: 100 %.', 'Cero derrames de aceite o grasa.'],
    dia=[('05:00', 'Revisas las revolvedoras que regresan del colado: presión, cortes y desgaste.'), ('Mañana', 'Engrase y niveles de las máquinas del tren y de la flotilla, según su carta.'),
         ('Mediodía', 'Reparas o cambias llantas en la jaula; anotas todo.'), ('Tarde', 'Última revisión de llantas antes de que los camiones salgan al ciclo de la noche.'),
         ('Cierre', 'Aceite usado en su tambo, herramienta limpia y pedidos a Almacén.')],
    saber=['Una revolvedora cargada lleva 8 m³ de concreto; una llanta baja se calienta y revienta en la ruta. Revisa la presión en frío, antes de que el camión salga.',
           'Un camión ponchado se sale del ciclo y rompe el ritmo de un camión cada 2 minutos. Por eso la revisión es diaria y de todas las llantas.',
           'Inflado siempre en jaula de seguridad y con manguera de extensión; nunca te pongas frente al rin mientras inflas.',
           'Cada máquina tiene su carta de lubricación: qué puntos, con qué grasa y cada cuántas horas. La pavimentadora y la máquina de textura y curado trabajan diez horas cada noche: se engrasan todos los días.',
           'El concreto pegado tapa las graseras: límpialas antes de engrasar.',
           'El aceite y la grasa usados van en su tambo etiquetado; en el suelo contaminan y tapan el drenaje.'],
    numeros=[('12', 'revolvedoras propias que revisas cada día'), ('8 m³', 'concreto que lleva cada revolvedora cargada'), ('2 min', 'el ritmo que rompe una ponchadura'),
             ('10 h', 'lo que trabajan cada noche las máquinas del tren')],
    errores=['Inflar una llanta sin jaula.', 'Dejar salir un camión con una llanta dañada.', 'Engrasar sólo los puntos fáciles.', 'Tirar el aceite usado.'],
    capacitacion=[('Días 2 a 5', 'Con el Jefe de mantenimiento: cartas de lubricación de cada máquina, presiones de cada llanta y uso de la jaula.'),
                  ('Semana 2', 'Registro digital de llantas y engrases con el Ingeniero de datos.'),
                  ('Tramo de prueba', 'Lleva la flotilla del tramo de prueba sin una sola ponchadura.'),
                  ('Primer año', 'Curso de mecánica básica diésel para subir a Mecánico.')],
    certificaciones=['NOM-004-STPS-1999 (maquinaria y equipo) y NOM-017-STPS-2008 (equipo de protección personal).', 'NOM-020-STPS-2011 (recipientes sujetos a presión) aplicado al compresor y al inflado.',
                     'NOM-005-STPS-1998 (manejo de sustancias inflamables y combustibles).'],
    comprobacion=['¿Por qué se revisan todas las llantas todos los días?', '¿Dónde se infla una llanta de camión y por qué?', '¿Cada cuándo se engrasa la pavimentadora?', '¿Qué haces con el aceite usado?'],
    siguiente='Mecánico.',
)

# ───────────────────────── Choferes propios ─────────────────────────

P['Chofer de revolvedora (12 camiones + 15 % de relevo)'] = dict(
    linea='Logística', reporta='Despachador de camiones', esquema='frente',
    mision='Llevar el concreto de la planta al frente a tiempo y en buen estado, en el lugar exacto del ciclo que marque el despachador, toda la noche y sin añadirle una gota de agua.',
    importa='El tren necesita un camión cada 2 minutos durante diez horas. Un solo chofer que se sale del ciclo a cargar diésel, que se atrasa o que le echa agua a la olla rompe el ritmo de la noche o daña 50 años de un tramo.',
    responde=['Cumplir su lugar en el ciclo: carga, ida, descarga, maniobra y regreso, a la hora que marque el despachador.',
              'Entregar el concreto dentro del tiempo máximo desde el mezclado, con su ticket de planta.', 'Mantener cerrada y sellada la llave del agua de la olla mientras lleve concreto.',
              'La revisión diaria de su camión: llantas, frenos, luces, alarma de reversa y olla.', 'Lavar la olla sólo en la zona autorizada.'],
    autoridad=['Negarse a añadir agua al concreto, aunque se lo pida cualquiera.', 'Detener su camión si ve un riesgo de seguridad en la ruta o en el frente.',
               'Avisar al despachador y no salir si su camión no pasó la revisión.', 'No le toca: salirse del ciclo por su cuenta (diésel, comida, un encargo) ni recibir órdenes de ruta de nadie más que del despachador.'],
    experiencia=['2 años o más manejando camión revolvedor de concreto o camión de carga de 3 ejes, con historial limpio de accidentes.',
                 'Haber trabajado en turno de noche o en obra con horarios estrictos de entrega.', 'Deseable: experiencia en concreto premezclado y uso de GPS y radio.'],
    escolaridad=['Primaria o secundaria terminada; saber leer y escribir.', 'Licencia federal de conductor tipo C vigente (o la licencia estatal de chofer que corresponda si la ruta no toca carretera federal) y examen psicofísico vigente.'],
    persona=['Llega descansado y a tiempo; sabe que el cansancio de noche no perdona.', 'Obedece al despachador aunque su patrón o un cabo le digan otra cosa.',
             'Dice "no" al agua sin discutir y lo reporta.', 'Maneja parejo: sin arrancones ni frenadas, respetando los límites de la ruta.', 'Avisa por radio en cuanto algo sale mal: una llanta, un cruce, un retraso.'],
    alertas=['Dice que "un poquito de agua no le hace nada al concreto".', 'Presume que llega antes porque "se va por su lado".', 'Tiene multas o accidentes que no puede explicar.', 'No quiere usar GPS ni radio.'],
    preguntas=[('Llegas al frente y el acabador te pide echarle agua a la olla porque viene dura. ¿Qué haces?', 'No le echo agua; aviso al laboratorista y al despachador. Se corrige con aditivo o se rechaza.'),
               ('Vas a medio ciclo y te marca la reserva de diésel. ¿Qué haces?', 'Aviso al despachador y cargo en el patio de planta cuando él me diga; nunca me salgo del ciclo por mi cuenta.'),
               ('Tu camión se poncha en la ruta. ¿Qué es lo primero que haces?', 'Me orillo seguro, pongo señales y aviso por radio al despachador para que mueva la reserva.'),
               ('¿Cuánto tiempo puede pasar desde que se mezcla el concreto hasta que se coloca?', 'Entre 60 y 90 minutos como máximo, y menos con calor.')],
    prueba='Prueba práctica de 2 horas: revisión preoperativa del camión con una falla sembrada (luz, llanta o alarma de reversa), un ciclo completo planta–frente–planta en la ruta real o en patio, con reversa guiada por el controlador de descarga hasta la colocadora, y una situación simulada en la que alguien le pide añadir agua. Aprueba si encuentra la falla, cumple el tiempo del ciclo, maniobra sin riesgo, se niega al agua y avisa por radio.',
    indicadores=['Cumplimiento de su lugar en el ciclo (GPS).', 'Veces fuera de ciclo: cero.', 'Cero camiones rechazados por agua añadida o por tiempo excedido por su causa.',
                 'Revisión preoperativa hecha cada noche.', 'Cero accidentes e incidentes en la ruta.'],
    dia=[('17:30', 'Llegas descansado; el despachador te da tu número de ciclo y la ruta de la noche.'), ('18:00', 'Revisión del camión: llantas, frenos, luces, alarma de reversa, olla y llave de agua sellada.'),
         ('19:00–05:00', 'Ciclos: carga, ida, descarga guiada por el controlador, maniobra y regreso. Todo cambio, por radio y con el despachador.'),
         ('05:00', 'Lavas la olla en la zona autorizada y reportas cualquier falla al mecánico.'), ('Después', 'Descanso completo; nunca se dobla turno.')],
    saber=['El tren pide 227 m³ por hora: 28 descargas de 8 m³, un camión cada 2 minutos, diez horas seguidas.',
           'El ciclo se mide: 6 minutos de carga, la ida, 6 de descarga, 5 de maniobra y el regreso, a unos 40 km/h de promedio. A 10 km de la planta, el ciclo dura unos 47 minutos.',
           'El concreto se coloca dentro de 60 a 90 minutos desde el mezclado, y menos con calor. Tu ticket de planta dice la hora de mezclado: cuídala.',
           'Cero agua añadida: la llave del agua de la olla va cerrada y sellada mientras llevas concreto. El agua de tu tanque sólo sirve para lavar después de descargar.',
           'El despachador manda sobre ti, seas propio o subcontratado. Diésel y baños están en el patio de planta: nadie deja el ciclo para cargar.',
           'En el frente, la reversa se hace sólo guiado por el controlador de descarga, con la alarma sonando y sin gente detrás; nunca cruces el carril abierto al tránsito.',
           'La olla gira siempre mientras llevas concreto; si se detiene, el concreto empieza a fraguar adentro.'],
    numeros=[('2 min', 'un camión en el frente, toda la noche'), ('8 m³', 'lo que lleva tu olla'), ('60–90 min', 'máximo del mezclado a la colocación'),
             ('≤ 30 °C', 'temperatura máxima del concreto al descargar'), ('≈ 47 min', 'tu ciclo con la planta a 10 km'), ('15 %', 'de camiones de reserva para cubrir fallas')],
    errores=['Añadir agua a la olla, o dejar que otro lo haga.', 'Salirse del ciclo a cargar diésel o a comer por tu cuenta.', 'Hacer reversa sin el controlador de descarga.',
             'Lavar la olla en la cuneta o en el dren.', 'Manejar cansado.'],
    capacitacion=[('Días 2 a 5', 'Con el Despachador: la ruta cronometrada, el radio, el GPS y el ticket de planta; con Seguridad e higiene, el plan de tránsito nocturno.'),
                  ('Semana 1', 'Ciclos acompañado por un chofer con experiencia; práctica de reversa guiada con el Controlador de descarga.'),
                  ('Tramo de prueba', 'Todos los ciclos de los 500 m de prueba; ahí se afina el ritmo real.'),
                  ('Cada año', 'Manejo defensivo y renovación del examen psicofísico.')],
    certificaciones=['Licencia federal de conductor tipo C vigente y examen psicofísico integral vigente.', 'NOM-087-SCT-2-2017 (tiempos de conducción y pausas).',
                     'Manejo defensivo nocturno.', 'NOM-031-STPS-2011 (seguridad en construcción) en su parte de frentes y tránsito.'],
    comprobacion=['¿Cada cuánto llega un camión al frente?', '¿Cuánto tiempo máximo tiene el concreto desde el mezclado?', '¿A quién le haces caso en la ruta y en el frente?',
                  '¿Qué haces si te piden echarle agua a la olla?'],
    siguiente='Chofer de relevo líder y después Despachador de camiones.',
    pedimos=['La llave del agua de tu olla va sellada mientras lleves concreto, sin excepción.', 'Tu radio encendido y contigo toda la noche.'],
)
